# Generated by Django 6.0.2 on 2026-02-09 16:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Event title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Event description (supports Markdown)')),
                ('start_date', models.DateTimeField(help_text='Event start date and time')),
                ('end_date', models.DateTimeField(help_text='Event end date and time')),
                ('visible', models.BooleanField(default=True, help_text='Whether the event is visible to team members')),
                ('url', models.URLField(blank=True, help_text='External URL for event details or signup', max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the event was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the event was last updated')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-start_date'],
            },
        ),
    ]
