# Generated by Django 6.0.2 on 2026-02-09 17:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Race title', max_length=200)),
                ('description', models.TextField(help_text='Race description')),
                ('zwift_category', models.CharField(blank=True, help_text='Zwift category (e.g., A, B, C, D, E)', max_length=20)),
                ('zwift_rating', models.CharField(blank=True, help_text='Zwift Racing rating range or threshold', max_length=50)),
                ('start_date', models.DateField(help_text='Race date')),
                ('start_time', models.TimeField(blank=True, help_text='Scheduled start time', null=True)),
                ('end_date', models.DateField(blank=True, help_text='End date if race spans multiple days', null=True)),
                ('url', models.URLField(blank=True, help_text='External URL for race details', max_length=500)),
                ('race_pass', models.URLField(blank=True, help_text='Zwift race pass/join link URL', max_length=500)),
                ('discord_channel_id', models.BigIntegerField(default=0, help_text='Discord channel ID for race coordination (0 = none)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the race was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the race was last updated')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this race', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_races', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(help_text='The event this race belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='races', to='events.event')),
            ],
            options={
                'verbose_name': 'Race',
                'verbose_name_plural': 'Races',
                'ordering': ['start_date', 'start_time'],
            },
        ),
    ]
