# Generated by Django 6.0.2 on 2026-02-09 17:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_race'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('confirmed', 'Confirmed'), ('withdrawn', 'Withdrawn'), ('no_show', 'No Show')], default='registered', help_text='Registration status', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Optional notes from the user or admin')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the registration was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the registration was last updated')),
                ('race', models.ForeignKey(help_text='The race the user registered for', on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.race')),
                ('user', models.ForeignKey(help_text='The registered user', on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event Registration',
                'verbose_name_plural': 'Event Registrations',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'race')},
            },
        ),
    ]
