# Generated by Django 6.0.2 on 2026-02-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='discord_channel_id',
            field=models.BigIntegerField(default=0, help_text='Discord channel ID for event coordination (0 = none)'),
        ),
    ]
