# Generated by Django 6.0.2 on 2026-02-17 15:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_discord_channel_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Squad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Squad name', max_length=200)),
                ('squad_timezone', models.CharField(blank=True, help_text='Optional timezone string', max_length=50)),
                ('discord_channel_id', models.BigIntegerField(default=0, help_text='Discord channel ID for squad coordination (0 = none)')),
                ('team_discord_role', models.BigIntegerField(default=0, help_text='Discord role ID for the squad (0 = none)')),
                ('status', models.CharField(choices=[('member', 'Member'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='pending', help_text='Squad membership status', max_length=20)),
                ('min_zwift_category', models.CharField(blank=True, help_text='Minimum Zwift category (e.g., A, B, C)', max_length=20)),
                ('max_zwift_category', models.CharField(blank=True, help_text='Maximum Zwift category (e.g., A, B, C)', max_length=20)),
                ('min_zwift_racing_category', models.CharField(blank=True, choices=[('Diamond', 'Diamond'), ('Ruby', 'Ruby'), ('Emerald', 'Emerald'), ('Sapphire', 'Sapphire'), ('Amethyst', 'Amethyst'), ('Platinum', 'Platinum'), ('Gold', 'Gold'), ('Silver', 'Silver'), ('Bronze', 'Bronze'), ('Copper', 'Copper')], help_text='Minimum Zwift Racing category', max_length=20)),
                ('max_zwift_racing_category', models.CharField(blank=True, choices=[('Diamond', 'Diamond'), ('Ruby', 'Ruby'), ('Emerald', 'Emerald'), ('Sapphire', 'Sapphire'), ('Amethyst', 'Amethyst'), ('Platinum', 'Platinum'), ('Gold', 'Gold'), ('Silver', 'Silver'), ('Bronze', 'Bronze'), ('Copper', 'Copper')], help_text='Maximum Zwift Racing category', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the squad was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the squad was last updated')),
                ('captain', models.ForeignKey(blank=True, help_text='Squad captain', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captain_squads', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this squad', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_squads', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(help_text='The event this squad belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='squads', to='events.event')),
                ('user', models.ForeignKey(help_text='The squad member', on_delete=django.db.models.deletion.CASCADE, related_name='squads', to=settings.AUTH_USER_MODEL)),
                ('vice_captain', models.ForeignKey(blank=True, help_text='Squad vice captain', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vice_captain_squads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Squad',
                'verbose_name_plural': 'Squads',
                'ordering': ['name'],
                'unique_together': {('event', 'user')},
            },
        ),
    ]
