# Generated by Django 6.0.2 on 2026-02-17 16:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_squad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='squad',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='SquadMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('member', 'Member'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='pending', help_text='Membership status', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the membership was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the membership was last updated')),
                ('squad', models.ForeignKey(help_text='The squad', on_delete=django.db.models.deletion.CASCADE, related_name='squad_members', to='events.squad')),
                ('user', models.ForeignKey(help_text='The squad member', on_delete=django.db.models.deletion.CASCADE, related_name='squad_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Squad Member',
                'verbose_name_plural': 'Squad Members',
                'ordering': ['user__first_name', 'user__last_name'],
                'unique_together': {('squad', 'user')},
            },
        ),
        migrations.AddField(
            model_name='squad',
            name='members',
            field=models.ManyToManyField(help_text='Squad members', related_name='squads', through='events.SquadMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='squad',
            name='status',
        ),
        migrations.RemoveField(
            model_name='squad',
            name='user',
        ),
    ]
