# Generated by Django 6.0.2 on 2026-02-18 02:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_squad_unique_together_squadmember_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='signups_open',
            field=models.BooleanField(default=False, help_text='Whether signups are currently open'),
        ),
        migrations.AddField(
            model_name='event',
            name='timezone_options',
            field=models.JSONField(blank=True, default=list, help_text='JSON list of timezone options, e.g. ["WEMA", "AMER", "APAC"]'),
        ),
        migrations.AddField(
            model_name='event',
            name='timezone_required',
            field=models.BooleanField(default=False, help_text='Whether timezone selection is required at signup'),
        ),
        migrations.CreateModel(
            name='EventSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signup_timezone', models.CharField(blank=True, help_text='Selected timezone from event options', max_length=50)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('withdrawn', 'Withdrawn')], default='registered', help_text='Signup status', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Optional notes')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the signup was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the signup was last updated')),
                ('event', models.ForeignKey(help_text='The event the user signed up for', on_delete=django.db.models.deletion.CASCADE, related_name='signups', to='events.event')),
                ('user', models.ForeignKey(help_text='The signed-up user', on_delete=django.db.models.deletion.CASCADE, related_name='event_signups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event Signup',
                'verbose_name_plural': 'Event Signups',
                'ordering': ['-created_at'],
                'unique_together': {('event', 'user')},
            },
        ),
    ]
