# Generated by Django 6.0.2 on 2026-02-18 13:20

import apps.events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_signups_open_event_timezone_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='timezone_options',
            field=models.JSONField(blank=True, default=apps.events.models._default_timezone_options, help_text='Timezone options available at signup'),
        ),
    ]
