# Generated by Django 6.0.2 on 2026-02-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_event_timezone_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='signup_instructions',
            field=models.TextField(blank=True, help_text='Instructions shown at the top of the signup form'),
        ),
    ]
