# Generated by Django 6.0.2 on 2026-02-18 15:17

import json

from django.db import migrations, models


def convert_timezone_strings_to_json(apps, schema_editor):
    """Convert existing signup_timezone CharField values to JSON-encoded list strings.

    Must run while the field is still a CharField so the raw string is accessible.
    On both SQLite and PostgreSQL, we write a JSON-encoded list string so the
    subsequent AlterField can parse/validate it.
    """
    EventSignup = apps.get_model("events", "EventSignup")
    for signup in EventSignup.objects.all():
        old_val = signup.signup_timezone
        if old_val:
            signup.signup_timezone = json.dumps([old_val])
        else:
            signup.signup_timezone = json.dumps([])
        signup.save(update_fields=["signup_timezone"])


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_event_signup_instructions'),
    ]

    operations = [
        migrations.RunPython(convert_timezone_strings_to_json, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='eventsignup',
            name='signup_timezone',
            field=models.JSONField(blank=True, default=list, help_text='Selected timezones from event options'),
        ),
    ]
