# Generated by Django 6.0.2 on 2026-02-18 15:28

from django.db import connection, migrations, models


def convert_datetime_to_date(apps, schema_editor):
    """Convert datetime values to date strings before SQLite table recreation.

    SQLite cannot implicitly cast datetime to date during ALTER TABLE (table
    recreation). We extract the date portion so the value survives the copy.
    PostgreSQL handles the cast natively, but running this is harmless there.
    """
    if connection.vendor == "sqlite":
        with connection.cursor() as cursor:
            cursor.execute(
                "UPDATE events_event SET start_date = DATE(start_date), end_date = DATE(end_date)"
            )


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_convert_signup_timezone_to_json'),
    ]

    operations = [
        migrations.RunPython(convert_datetime_to_date, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(help_text='Event start date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateField(help_text='Event end date'),
        ),
    ]
