# Generated by Django 6.0.2 on 2026-02-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_event_date_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='head_captain_role_id',
            field=models.BigIntegerField(default=0, help_text='Discord role ID for the head captain of this event (0 = none)'),
        ),
    ]
