# Generated by Django 6.0.2 on 2026-02-20 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_event_head_captain_role_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='squad',
            name='invite_url',
            field=models.URLField(blank=True, help_text='Invite URL for joining the squad', max_length=500),
        ),
        migrations.AddField(
            model_name='squad',
            name='url',
            field=models.URLField(blank=True, help_text='External URL for squad details', max_length=500),
        ),
    ]
