# Generated by Django 6.0.2 on 2026-02-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_squad_url_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='logo',
            field=models.ImageField(blank=True, help_text='Optional logo image for the event', upload_to='event_logos/'),
        ),
    ]
