# Generated by Django 6.0.2 on 2026-02-26 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_event_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='squad',
            name='audio_channel_id',
            field=models.BigIntegerField(default=0, help_text='Discord voice/stage channel ID for squad audio (0 = none)'),
        ),
    ]
