# Generated by Django 6.0.2 on 2026-02-26 18:44

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_squad_audio_channel_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilityGrid',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, help_text='Optional label for this grid', max_length=200)),
                ('start_date', models.DateField(help_text='Grid start date')),
                ('end_date', models.DateField(help_text='Grid end date')),
                ('start_time', models.CharField(help_text='UTC start time as "HH:MM"', max_length=5)),
                ('end_time', models.CharField(help_text='UTC end time as "HH:MM"', max_length=5)),
                ('slot_duration', models.PositiveSmallIntegerField(help_text='Minutes per time slot (15, 30, or 60)')),
                ('blocked_cells', models.JSONField(blank=True, default=list, help_text='List of blocked cells, each {"date": "YYYY-MM-DD", "time": "HH:MM"}')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed')], default='draft', help_text='Grid lifecycle status', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the grid was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the grid was last updated')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this grid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_availability_grids', to=settings.AUTH_USER_MODEL)),
                ('squad', models.ForeignKey(help_text='The squad this availability grid belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='availability_grids', to='events.squad')),
            ],
            options={
                'verbose_name': 'Availability Grid',
                'verbose_name_plural': 'Availability Grids',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AvailabilityResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_cells', models.JSONField(blank=True, default=list, help_text='List of available cells, each {"date": "YYYY-MM-DD", "time": "HH:MM"}')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the response was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the response was last updated')),
                ('grid', models.ForeignKey(help_text='The availability grid this response belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='events.availabilitygrid')),
                ('user', models.ForeignKey(help_text='The responding member', on_delete=django.db.models.deletion.CASCADE, related_name='availability_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Availability Response',
                'verbose_name_plural': 'Availability Responses',
                'ordering': ['user__first_name', 'user__last_name'],
                'unique_together': {('grid', 'user')},
            },
        ),
    ]
