# Generated by Django 6.0.2 on 2026-02-26 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_availabilitygrid_availabilityresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabilitygrid',
            name='grid_timezone',
            field=models.CharField(default='UTC', help_text='IANA timezone used when creating this grid', max_length=50),
        ),
    ]
