# Generated by Django 6.0.2 on 2026-02-27 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_add_grid_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='prefix',
            field=models.CharField(blank=True, help_text='Short prefix for the event (e.g. team abbreviation)', max_length=50),
        ),
    ]
