# Generated by Django 6.0.2 on 2026-02-28 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_add_event_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='prefix',
            field=models.CharField(blank=True, help_text='Channel/role prefix, e.g. "$" in $DRS', max_length=50),
        ),
    ]
