# Generated by Django 6.0.2 on 2026-03-01 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_alter_event_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_role',
            field=models.BigIntegerField(default=0, help_text='Discord role ID for the event (0 = none)'),
        ),
    ]
