# Generated by Django 6.0.2 on 2026-03-02 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_add_event_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='squad',
            name='invite_token',
            field=models.UUIDField(blank=True, editable=False, help_text='Token for shareable squad invite links', null=True, unique=True),
        ),
    ]
