# Generated by Django 6.0.2 on 2026-03-02 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_squad_invite_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabilitygrid',
            name='expires',
            field=models.DateField(blank=True, help_text='Date when this grid expires and is no longer visible', null=True),
        ),
    ]
