# Generated by Django 6.0.2 on 2026-03-03 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_availabilitygrid_expires'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabilitygrid',
            name='max_races_question',
            field=models.BooleanField(default=False, help_text='Ask responders: What is the max number of races you would like to do?'),
        ),
        migrations.AddField(
            model_name='availabilitygrid',
            name='rest_days_question',
            field=models.BooleanField(default=False, help_text='Ask responders: How many days rest between races do you require?'),
        ),
        migrations.AddField(
            model_name='availabilityresponse',
            name='max_races',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Max number of races the responder wants to do', null=True),
        ),
        migrations.AddField(
            model_name='availabilityresponse',
            name='rest_days',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Number of rest days required between races', null=True),
        ),
    ]
