# Generated by Django 6.0.2 on 2026-03-04 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_rename_eventregistration_to_raceregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='squad',
            name='discord_captain_role',
            field=models.BigIntegerField(default=0, help_text='Discord role ID for the squad captain (0 = none)'),
        ),
    ]
