# Generated by Django 6.0.3 on 2026-03-12 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_squad_discord_captain_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilitySlotSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name for this slot selection', max_length=200)),
                ('slot_date', models.DateField(help_text='UTC date of the selected cell')),
                ('slot_time', models.CharField(help_text='UTC time as "HH:MM"', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the selection was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the selection was last modified')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this selection', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_slot_selections', to=settings.AUTH_USER_MODEL)),
                ('grid', models.ForeignKey(help_text='The availability grid this selection belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='slot_selections', to='events.availabilitygrid')),
                ('selected_users', models.ManyToManyField(blank=True, help_text='Users selected for this slot', related_name='availability_selections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Availability Slot Selection',
                'verbose_name_plural': 'Availability Slot Selections',
                'ordering': ['slot_date', 'slot_time'],
                'unique_together': {('grid', 'slot_date', 'slot_time')},
            },
        ),
    ]
