# Generated by Django 6.0.3 on 2026-03-19 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_availabilityslotselection'),
    ]

    operations = [
        migrations.AddField(
            model_name='squad',
            name='captain_notifications',
            field=models.BooleanField(default=True, help_text="Notify captain/vice-captain via Discord DM when squad members' verification records change"),
        ),
    ]
