# Generated by Django 6.0.5 on 2026-05-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_squad_captain_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabilityslotselection',
            name='course_url',
            field=models.URLField(blank=True, default='', help_text='Optional link to the course/route page'),
        ),
        migrations.AddField(
            model_name='availabilityslotselection',
            name='event_invite_url',
            field=models.URLField(blank=True, default='', help_text='Optional invite link to the scheduled event/race'),
        ),
    ]
