# Generated by Django 6.0.5 on 2026-05-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0028_availabilityslotselection_course_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabilityslotselection',
            name='status',
            field=models.CharField(choices=[('none', 'None'), ('pending', 'Pending'), ('confirmed', 'Confirmed')], default='none', help_text='Scheduling status (none, pending, confirmed)', max_length=10),
        ),
    ]
