# Generated by Django 6.0.5 on 2026-05-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0029_availabilityslotselection_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabilityslotselection',
            name='thread_link',
            field=models.URLField(blank=True, default='', help_text='Optional URL to a Discord thread for this race'),
        ),
    ]
