# Generated by Django 6.0.5 on 2026-05-12 03:27

from django.db import migrations, models

import apps.events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0030_availabilityslotselection_thread_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='squad_gender_options',
            field=models.JSONField(blank=True, default=apps.events.models._default_squad_gender_options, help_text='Squad gender preference options available at signup'),
        ),
        migrations.AddField(
            model_name='event',
            name='squad_gender_required',
            field=models.BooleanField(default=False, help_text='Require squad gender preference at signup (also gates whether the field appears)'),
        ),
        migrations.AddField(
            model_name='eventsignup',
            name='signup_squad_gender',
            field=models.JSONField(blank=True, default=list, help_text='Selected squad gender preferences from event options'),
        ),
    ]
