# Generated by Django 6.0.5 on 2026-05-12 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0031_event_squad_gender_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='squad',
            name='gender',
            field=models.CharField(blank=True, help_text="Optional squad gender; must be one of the parent event's squad_gender_options when set", max_length=50),
        ),
    ]
