# Generated by Django 6.0.5 on 2026-05-13 02:45

from django.db import migrations, models


def copy_prefix_to_prefixes(apps, schema_editor):
    """Copy the existing single-string ``prefix`` value to the new ``prefixes`` list."""
    Event = apps.get_model("events", "Event")
    for event in Event.objects.all():
        existing = (event.prefix or "").strip()
        event.prefixes = [existing] if existing else []
        event.save(update_fields=["prefixes"])


def copy_prefixes_back_to_prefix(apps, schema_editor):
    """Reverse: take the first entry of ``prefixes`` and write it back to ``prefix``."""
    Event = apps.get_model("events", "Event")
    for event in Event.objects.all():
        first = event.prefixes[0] if event.prefixes else ""
        event.prefix = first
        event.save(update_fields=["prefix"])


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0032_squad_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='prefixes',
            field=models.JSONField(blank=True, default=list, help_text='Channel/role prefixes (list), e.g. ["$", "~"]. Roles matching any of these prefixes appear in event/squad selectors.'),
        ),
        migrations.RunPython(copy_prefix_to_prefixes, reverse_code=copy_prefixes_back_to_prefix),
        migrations.RemoveField(
            model_name='event',
            name='prefix',
        ),
    ]
