# Generated by Django 6.0.5 on 2026-05-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0033_remove_event_prefix_event_prefixes'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='coordinator_role_ids',
            field=models.JSONField(blank=True, default=list, help_text='List of Discord role IDs (strings) for regional/group coordinators'),
        ),
    ]
