# Generated by Django 6.0.5 on 2026-05-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0034_event_coordinator_role_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='signup_notification_channel_id',
            field=models.BigIntegerField(default=0, help_text='Discord channel ID for rider signup notifications (0 = disabled)'),
        ),
    ]
