# Generated by Django 6.0.5 on 2026-05-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0035_event_signup_notification_channel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabilityslotselection',
            name='opponent',
            field=models.CharField(blank=True, default='', help_text='Optional opponent team or rider name for this scheduled race', max_length=200),
        ),
    ]
