# Generated by Django 6.0.5 on 2026-05-19 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0036_availabilityslotselection_opponent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='availabilityslotselection',
            name='substitute',
            field=models.ForeignKey(blank=True, help_text='Optional substitute rider available to step in', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substitute_slot_selections', to=settings.AUTH_USER_MODEL),
        ),
    ]
