# Generated by Django 6.0.5 on 2026-05-16 02:56

from datetime import date, timedelta

from django.db import migrations


def convert_date_forward(apps, schema_editor):
    AvailabilityResponse = apps.get_model("events", "AvailabilityResponse")
    for response in AvailabilityResponse.objects.all():
        for cell in response.available_cells:
            if cell['time'] < response.grid.start_time:
                converted_date = date.fromisoformat(cell['date']) + timedelta(days=1)
                cell['date'] = converted_date.strftime("%Y-%m-%d")
        response.save()

    AvailabilitySlotSelection = apps.get_model("events", "AvailabilitySlotSelection")
    for selection in AvailabilitySlotSelection.objects.all():
        if selection.slot_time < selection.grid.start_time:
            selection.slot_date = selection.slot_date + timedelta(days=1)
            selection.save()


def convert_date_reverse(apps, schema_editor):
    AvailabilityResponse = apps.get_model("events", "AvailabilityResponse")
    for response in AvailabilityResponse.objects.all():
        for cell in response.available_cells:
            if cell['time'] < response.grid.start_time:
                converted_date = date.fromisoformat(cell['date']) - timedelta(days=1)
                cell['date'] = converted_date.strftime("%Y-%m-%d")
        response.save()

    AvailabilitySlotSelection = apps.get_model("events", "AvailabilitySlotSelection")
    for selection in AvailabilitySlotSelection.objects.all():
        if selection.slot_time < selection.grid.start_time:
            selection.slot_date = selection.slot_date - timedelta(days=1)
            selection.save()


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0037_availabilityslotselection_substitute'),
    ]

    operations = [
        migrations.RunPython(convert_date_forward, reverse_code=convert_date_reverse),
    ]
