# Generated by Django 6.0.6 on 2026-06-06 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0038_fix_availability_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='show_signups',
            field=models.BooleanField(default=False, help_text='Let all logged-in team members expand and see the signup list (names only); event admins always see full details'),
        ),
    ]
