# Generated by Django 6.0.6 on 2026-06-07 00:13

from django.conf import settings
from django.db import migrations, models


def copy_captains_to_m2m(apps, schema_editor):
    """Copy each squad's single captain/vice_captain FK into the new M2M fields."""
    Squad = apps.get_model("events", "Squad")
    for squad in Squad.objects.all():
        if squad.captain_id:
            squad.captains.add(squad.captain_id)
        if squad.vice_captain_id:
            squad.vice_captains.add(squad.vice_captain_id)


def restore_captains_from_m2m(apps, schema_editor):
    """Reverse: pick the first captain/vice_captain from the M2M back into the FK."""
    Squad = apps.get_model("events", "Squad")
    for squad in Squad.objects.all():
        first_captain = squad.captains.first()
        first_vice = squad.vice_captains.first()
        squad.captain_id = first_captain.pk if first_captain else None
        squad.vice_captain_id = first_vice.pk if first_vice else None
        squad.save(update_fields=["captain", "vice_captain"])


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0039_event_show_signups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # 1. Add the new M2M fields while the old FKs still exist.
        migrations.AddField(
            model_name='squad',
            name='captains',
            field=models.ManyToManyField(blank=True, help_text='Squad captains', related_name='captain_squads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='squad',
            name='vice_captains',
            field=models.ManyToManyField(blank=True, help_text='Squad vice captains', related_name='vice_captain_squads', to=settings.AUTH_USER_MODEL),
        ),
        # 2. Copy existing single captain/vice_captain into the M2M.
        migrations.RunPython(copy_captains_to_m2m, restore_captains_from_m2m),
        # 3. Drop the old single FKs.
        migrations.RemoveField(
            model_name='squad',
            name='captain',
        ),
        migrations.RemoveField(
            model_name='squad',
            name='vice_captain',
        ),
    ]
