# Generated by Django 6.0.6 on 2026-06-07 18:01

from django.conf import settings
from django.db import migrations, models


def copy_substitute_to_m2m(apps, schema_editor):
    """Copy each slot selection's single substitute FK into the new M2M field."""
    AvailabilitySlotSelection = apps.get_model("events", "AvailabilitySlotSelection")
    for selection in AvailabilitySlotSelection.objects.all():
        if selection.substitute_id:
            selection.substitutes.add(selection.substitute_id)


def restore_substitute_from_m2m(apps, schema_editor):
    """Reverse: pick the first substitute from the M2M back into the FK."""
    AvailabilitySlotSelection = apps.get_model("events", "AvailabilitySlotSelection")
    for selection in AvailabilitySlotSelection.objects.all():
        first_sub = selection.substitutes.first()
        selection.substitute_id = first_sub.pk if first_sub else None
        selection.save(update_fields=["substitute"])


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0040_squad_multiple_captains'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # 1. Add the new M2M field while the old FK still exists.
        migrations.AddField(
            model_name='availabilityslotselection',
            name='substitutes',
            field=models.ManyToManyField(blank=True, help_text='Optional substitute riders available to step in', related_name='substitute_slot_selections', to=settings.AUTH_USER_MODEL),
        ),
        # 2. Copy the existing single substitute into the M2M.
        migrations.RunPython(copy_substitute_to_m2m, restore_substitute_from_m2m),
        # 3. Drop the old single FK.
        migrations.RemoveField(
            model_name='availabilityslotselection',
            name='substitute',
        ),
        # Unrelated metadata tidy: shortened show_signups help text.
        migrations.AlterField(
            model_name='event',
            name='show_signups',
            field=models.BooleanField(default=False, help_text='Let all logged-in members expand the signup list (names only); admins see full details'),
        ),
    ]
