# Generated by Django 6.0.6 on 2026-06-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0041_slot_multiple_substitutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='config_option',
            field=models.CharField(blank=True, choices=[('LADDER', 'Ladder'), ('SERIES', 'Series'), ('TTT', 'TTT')], default='', help_text='Configuration profile used to enable optional event behaviors', max_length=20),
        ),
    ]
