# Generated by Django 6.0.6 on 2026-06-13 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0042_event_config_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='squad',
            name='enforce_max_zwift_racing_category',
            field=models.BooleanField(default=False, help_text='Block adding a rider stronger than the maximum Zwift Racing category'),
        ),
        migrations.AddField(
            model_name='squad',
            name='enforce_min_zwift_racing_category',
            field=models.BooleanField(default=False, help_text='Block adding a rider weaker than the minimum Zwift Racing category'),
        ),
    ]
