# Generated by Django 6.0.6 on 2026-06-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0043_squad_enforce_max_zwift_racing_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='squad',
            name='enforce_gender',
            field=models.BooleanField(default=False, help_text='Block adding a rider whose gender does not match the squad gender (COED allows any)'),
        ),
        migrations.AlterField(
            model_name='squad',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('COED', 'COED')], help_text='Squad gender (Male, Female, or COED)', max_length=50),
        ),
    ]
