# Generated by Django 6.0.6 on 2026-06-13 16:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0045_overwrite_squad_gender_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilityGridTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Label shown in the template picker', max_length=200)),
                ('start_time', models.CharField(help_text='Local start time as "HH:MM"', max_length=5)),
                ('end_time', models.CharField(help_text='Local end time as "HH:MM"', max_length=5)),
                ('grid_timezone', models.CharField(default='UTC', help_text='IANA timezone the times are expressed in', max_length=50)),
                ('slot_duration', models.PositiveSmallIntegerField(help_text='Minutes per time slot (15, 30, or 60)')),
                ('default_length_days', models.PositiveSmallIntegerField(default=7, help_text='Number of days a created grid spans (used to derive the end date on apply)')),
                ('max_races_question', models.BooleanField(default=False, help_text='Carry the max-races question onto grids created from this template')),
                ('rest_days_question', models.BooleanField(default=False, help_text='Carry the rest-days question onto grids created from this template')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the template was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the template was last updated')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this template', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_availability_templates', to=settings.AUTH_USER_MODEL)),
                ('squad', models.ForeignKey(help_text='The squad this template belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='availability_templates', to='events.squad')),
            ],
            options={
                'verbose_name': 'Availability Grid Template',
                'verbose_name_plural': 'Availability Grid Templates',
                'ordering': ['name'],
            },
        ),
    ]
