# Generated by Django 6.0.6 on 2026-06-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0046_availabilitygridtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabilitygrid',
            name='hide_empty_days',
            field=models.BooleanField(default=False, help_text='Hide days where every time slot is blocked from the response/results grids'),
        ),
    ]
