# Generated by Django 6.0.6 on 2026-06-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0047_availabilitygrid_hide_empty_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='squad',
            name='max_womens_zwift_category',
            field=models.CharField(blank=True, help_text="Maximum women's Zwift category (e.g., A, B, C)", max_length=20),
        ),
        migrations.AddField(
            model_name='squad',
            name='min_womens_zwift_category',
            field=models.CharField(blank=True, help_text="Minimum women's Zwift category (e.g., A, B, C)", max_length=20),
        ),
    ]
