# Generated by Django 6.0.6 on 2026-06-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0048_squad_max_womens_zwift_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='squad',
            name='enforce_max_womens_zwift_category',
            field=models.BooleanField(default=False, help_text="Block adding a woman stronger than the maximum women's Zwift category"),
        ),
        migrations.AddField(
            model_name='squad',
            name='enforce_min_womens_zwift_category',
            field=models.BooleanField(default=False, help_text="Block adding a woman weaker than the minimum women's Zwift category"),
        ),
        migrations.AlterField(
            model_name='squad',
            name='max_womens_zwift_category',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], help_text="Maximum women's Zwift category (strongest allowed; A high, E low)", max_length=20),
        ),
        migrations.AlterField(
            model_name='squad',
            name='min_womens_zwift_category',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], help_text="Minimum women's Zwift category (weakest allowed; A high, E low)", max_length=20),
        ),
    ]
