# Generated by Django 6.0.6 on 2026-06-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0049_squad_enforce_max_womens_zwift_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='squad',
            name='enforce_max_zwift_category',
            field=models.BooleanField(default=False, help_text='Block adding a rider stronger than the maximum Zwift category'),
        ),
        migrations.AddField(
            model_name='squad',
            name='enforce_min_zwift_category',
            field=models.BooleanField(default=False, help_text='Block adding a rider weaker than the minimum Zwift category'),
        ),
        migrations.AlterField(
            model_name='squad',
            name='max_zwift_category',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], help_text='Maximum Zwift category (strongest allowed; A high, E low)', max_length=20),
        ),
        migrations.AlterField(
            model_name='squad',
            name='min_zwift_category',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], help_text='Minimum Zwift category (weakest allowed; A high, E low)', max_length=20),
        ),
    ]
