# Generated by Django 6.0.6 on 2026-06-15 01:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0050_squad_enforce_max_zwift_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SlotDS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_was_assigned', models.BooleanField(default=False, help_text='Whether we added the squad role (only then do we remove it later)')),
                ('role_removed_at', models.DateTimeField(blank=True, help_text='When the squad role was removed/handled for this DS (null while active)', null=True)),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the DS was added')),
                ('added_by', models.ForeignKey(blank=True, help_text='Admin who added this DS', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_ds_assignments', to=settings.AUTH_USER_MODEL)),
                ('selection', models.ForeignKey(help_text='The scheduled race this DS helps with', on_delete=django.db.models.deletion.CASCADE, related_name='ds_assignments', to='events.availabilityslotselection')),
                ('user', models.ForeignKey(help_text='The Directeur Sportif', on_delete=django.db.models.deletion.CASCADE, related_name='ds_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Slot Directeur Sportif',
                'verbose_name_plural': 'Slot Directeurs Sportifs',
                'ordering': ['added_at'],
                'unique_together': {('selection', 'user')},
            },
        ),
        migrations.AddField(
            model_name='availabilityslotselection',
            name='directeurs_sportifs',
            field=models.ManyToManyField(help_text='Team members helping with this race (DS); given the squad role while assigned', related_name='directing_slot_selections', through='events.SlotDS', through_fields=('selection', 'user'), to=settings.AUTH_USER_MODEL),
        ),
    ]
