# Generated by Django 6.0.6 on 2026-06-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0051_slotds_availabilityslotselection_directeurs_sportifs'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabilityslotselection',
            name='custom_finish_km',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional custom finish distance in km (e.g. 13.5)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='availabilityslotselection',
            name='laps',
            field=models.PositiveIntegerField(blank=True, help_text='Optional number of laps for this race', null=True),
        ),
        migrations.AddField(
            model_name='availabilityslotselection',
            name='powerups',
            field=models.JSONField(blank=True, default=list, help_text='Optional list of enabled Zwift power-ups (values from PowerUp choices)'),
        ),
    ]
