# Generated by Django 6.0.6 on 2026-06-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0052_availabilityslotselection_custom_finish_km_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabilityslotselection',
            name='powerups',
            field=models.JSONField(blank=True, default=list, help_text='Optional list of enabled Zwift power-up slugs (ttt_planner.PowerUp.slug values)'),
        ),
    ]
