# Generated by Django 6.0.6 on 2026-07-07 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0053_alter_availabilityslotselection_powerups'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='require_race_verified_availability',
            field=models.BooleanField(default=False, help_text='Require Race Verified status before a member can submit availability for this event'),
        ),
    ]
