# Generated by Django 6.0.6 on 2026-07-07 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0054_event_require_race_verified_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabilitygrid',
            name='require_race_verified_availability',
            field=models.BooleanField(default=False, help_text='Require Race Verified status before a member can submit this grid. Forced on when the parent event requires it.'),
        ),
    ]
