# Generated by Django 6.0.7 on 2026-08-06 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0055_availabilitygrid_require_race_verified_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='squad',
            name='regional_coordinator_role',
            field=models.BigIntegerField(default=0, help_text="Discord role ID for this squad's regional coordinator, chosen from the event's coordinator roles (0 = none)"),
        ),
    ]
