# Generated by Django 6.0.7 on 2026-08-11 14:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0056_squad_regional_coordinator_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsignup',
            name='custom_answers',
            field=models.JSONField(blank=True, default=dict, help_text="Answers to the event's custom signup questions, keyed by question id (as a string)"),
        ),
        migrations.CreateModel(
            name='SignupQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='The question shown to riders', max_length=200)),
                ('question_type', models.CharField(choices=[('text', 'Short text'), ('single', 'Single choice'), ('multi', 'Multiple choice'), ('boolean', 'Yes / No')], default='text', help_text='Answer type', max_length=20)),
                ('options', models.JSONField(blank=True, default=list, help_text='Choices for single/multiple-choice questions (ignored for text and yes/no)')),
                ('required', models.BooleanField(default=False, help_text='Riders must answer before signing up')),
                ('help_text', models.CharField(blank=True, help_text='Optional helper text shown under the question', max_length=300)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the question was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the question was last updated')),
                ('event', models.ForeignKey(help_text='The event this signup question belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='signup_questions', to='events.event')),
            ],
            options={
                'verbose_name': 'Signup Question',
                'verbose_name_plural': 'Signup Questions',
                'ordering': ['order', 'id'],
            },
        ),
    ]
