# Generated by Django 6.0.7 on 2026-08-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0057_eventsignup_custom_answers_signupquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='squad',
            name='region_role',
            field=models.BigIntegerField(default=0, help_text='Discord role added to riders assigned to this squad and removed when they leave — unless they still belong to another squad with the same region role (0 = none)'),
        ),
    ]
