# Generated by Django 6.0.7 on 2026-08-17 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0058_squad_region_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='timezone_role_map',
            field=models.JSONField(blank=True, default=dict, help_text='Optional map of timezone/region option -> Discord role ID, granted on signup. Empty means the feature is off for this event.'),
        ),
    ]
