# Generated by Django 6.0.7 on 2026-08-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0059_event_timezone_role_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='squad',
            name='enforce_max_zftp_w',
            field=models.BooleanField(default=False, help_text='Block adding a rider above the maximum zFTP in watts'),
        ),
        migrations.AddField(
            model_name='squad',
            name='enforce_max_zftp_wkg',
            field=models.BooleanField(default=False, help_text='Block adding a rider above the maximum zFTP in W/kg'),
        ),
        migrations.AddField(
            model_name='squad',
            name='enforce_max_zmap_w',
            field=models.BooleanField(default=False, help_text='Block adding a rider above the maximum zMAP in watts'),
        ),
        migrations.AddField(
            model_name='squad',
            name='enforce_max_zmap_wkg',
            field=models.BooleanField(default=False, help_text='Block adding a rider above the maximum zMAP in W/kg'),
        ),
        migrations.AddField(
            model_name='squad',
            name='enforce_min_zftp_w',
            field=models.BooleanField(default=False, help_text='Block adding a rider below the minimum zFTP in watts'),
        ),
        migrations.AddField(
            model_name='squad',
            name='enforce_min_zftp_wkg',
            field=models.BooleanField(default=False, help_text='Block adding a rider below the minimum zFTP in W/kg'),
        ),
        migrations.AddField(
            model_name='squad',
            name='enforce_min_zmap_w',
            field=models.BooleanField(default=False, help_text='Block adding a rider below the minimum zMAP in watts'),
        ),
        migrations.AddField(
            model_name='squad',
            name='enforce_min_zmap_wkg',
            field=models.BooleanField(default=False, help_text='Block adding a rider below the minimum zMAP in W/kg'),
        ),
        migrations.AddField(
            model_name='squad',
            name='max_zftp_w',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Maximum zFTP in watts', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='squad',
            name='max_zftp_wkg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum zFTP in W/kg', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='squad',
            name='max_zmap_w',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Maximum zMAP in watts', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='squad',
            name='max_zmap_wkg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum zMAP in W/kg', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='squad',
            name='min_zftp_w',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Minimum zFTP in watts', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='squad',
            name='min_zftp_wkg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum zFTP in W/kg', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='squad',
            name='min_zmap_w',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Minimum zMAP in watts', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='squad',
            name='min_zmap_wkg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum zMAP in W/kg', max_digits=4, null=True),
        ),
    ]
