# Generated by Django 6.0.7 on 2026-08-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0060_squad_enforce_max_zftp_w_squad_enforce_max_zftp_wkg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='squad',
            name='require_zauth',
            field=models.BooleanField(default=False, help_text='Require members to have connected their Zwift account through zauth'),
        ),
    ]
