# Generated by Django 6.0.7 on 2026-08-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0061_squad_require_zauth'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabilitygrid',
            name='course_url',
            field=models.URLField(blank=True, help_text='Course or route details', max_length=500),
        ),
        migrations.AddField(
            model_name='availabilitygrid',
            name='description',
            field=models.TextField(blank=True, help_text='Markdown shown above the grid. Captain-authored, so markdown is rendered.'),
        ),
        migrations.AddField(
            model_name='availabilitygrid',
            name='expanded_features',
            field=models.BooleanField(default=False, help_text='Show the description and links below to riders filling in this grid'),
        ),
        migrations.AddField(
            model_name='availabilitygrid',
            name='invite_url',
            field=models.URLField(blank=True, help_text='Event invite / sign-up link', max_length=500),
        ),
        migrations.AddField(
            model_name='availabilitygrid',
            name='recon_url',
            field=models.URLField(blank=True, help_text='Event recon (ride-through, preview)', max_length=500),
        ),
        migrations.AddField(
            model_name='availabilitygrid',
            name='website_url',
            field=models.URLField(blank=True, help_text='Event website', max_length=500),
        ),
    ]
