# Generated by Django 6.0.7 on 2026-08-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0062_availabilitygrid_course_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabilitygrid',
            name='single_slot',
            field=models.BooleanField(default=False, help_text='One date and time rather than a grid; riders answer available yes/no'),
        ),
    ]
