# Generated by Django 6.0.7 on 2026-08-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0063_availabilitygrid_single_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='grid_default_expanded_features',
            field=models.BooleanField(blank=True, help_text='Default for "Expand Features" on new availability grids. Unset leaves it to the captain.', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='grid_default_hide_empty_days',
            field=models.BooleanField(blank=True, help_text='Default for "Hide days with no available times" on new availability grids. Unset leaves it to the captain.', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='grid_default_max_races_question',
            field=models.BooleanField(blank=True, help_text='Default for "Ask: Max number of races" on new availability grids. Unset leaves it to the captain.', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='grid_default_rest_days_question',
            field=models.BooleanField(blank=True, help_text='Default for "Ask: Rest days between races" on new availability grids. Unset leaves it to the captain.', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='grid_default_single_slot',
            field=models.BooleanField(blank=True, help_text='Default for "Single Time Slot" on new availability grids. Unset leaves it to the captain.', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='grid_enforce_expanded_features',
            field=models.BooleanField(default=False, help_text='Lock "Expand Features" to the event default; captains cannot change it.'),
        ),
        migrations.AddField(
            model_name='event',
            name='grid_enforce_hide_empty_days',
            field=models.BooleanField(default=False, help_text='Lock "Hide days with no available times" to the event default; captains cannot change it.'),
        ),
        migrations.AddField(
            model_name='event',
            name='grid_enforce_max_races_question',
            field=models.BooleanField(default=False, help_text='Lock "Ask: Max number of races" to the event default; captains cannot change it.'),
        ),
        migrations.AddField(
            model_name='event',
            name='grid_enforce_rest_days_question',
            field=models.BooleanField(default=False, help_text='Lock "Ask: Rest days between races" to the event default; captains cannot change it.'),
        ),
        migrations.AddField(
            model_name='event',
            name='grid_enforce_single_slot',
            field=models.BooleanField(default=False, help_text='Lock "Single Time Slot" to the event default; captains cannot change it.'),
        ),
    ]
