# Generated by Django 6.0.7 on 2026-08-21 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0064_event_grid_default_expanded_features_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabilitygridtemplate',
            name='shared',
            field=models.BooleanField(default=False, help_text='Offer this template to every squad, not just this one. Shared templates carry the times and timezone they were built with, so the squad using one is told to check both.'),
        ),
    ]
