# Generated by Django 6.0.7 on 2026-08-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0065_availabilitygridtemplate_shared'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabilitygridtemplate',
            name='course_url',
            field=models.URLField(blank=True, help_text='Course or route details', max_length=500),
        ),
        migrations.AddField(
            model_name='availabilitygridtemplate',
            name='description',
            field=models.TextField(blank=True, help_text='Markdown shown above the grid'),
        ),
        migrations.AddField(
            model_name='availabilitygridtemplate',
            name='expanded_features',
            field=models.BooleanField(default=False, help_text='Show the description and links below on grids made from this template'),
        ),
        migrations.AddField(
            model_name='availabilitygridtemplate',
            name='hide_empty_days',
            field=models.BooleanField(default=False, help_text='Hide days with no available times on grids made from this template'),
        ),
        migrations.AddField(
            model_name='availabilitygridtemplate',
            name='invite_url',
            field=models.URLField(blank=True, help_text='Event invite / sign-up link', max_length=500),
        ),
        migrations.AddField(
            model_name='availabilitygridtemplate',
            name='recon_url',
            field=models.URLField(blank=True, help_text='Event recon', max_length=500),
        ),
        migrations.AddField(
            model_name='availabilitygridtemplate',
            name='single_slot',
            field=models.BooleanField(default=False, help_text='Grids from this template are a single date and time'),
        ),
        migrations.AddField(
            model_name='availabilitygridtemplate',
            name='website_url',
            field=models.URLField(blank=True, help_text='Event website', max_length=500),
        ),
    ]
