# Generated by Django 6.1 on 2026-08-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0066_availabilitygridtemplate_course_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squad',
            name='enforce_max_womens_zwift_category',
            field=models.BooleanField(default=False, help_text="Block adding a woman higher than the maximum women's Zwift category"),
        ),
        migrations.AlterField(
            model_name='squad',
            name='enforce_max_zwift_category',
            field=models.BooleanField(default=False, help_text='Block adding a rider higher than the maximum Zwift category'),
        ),
        migrations.AlterField(
            model_name='squad',
            name='enforce_max_zwift_racing_category',
            field=models.BooleanField(default=False, help_text='Block adding a rider higher than the maximum Zwift Racing category'),
        ),
        migrations.AlterField(
            model_name='squad',
            name='enforce_min_womens_zwift_category',
            field=models.BooleanField(default=False, help_text="Block adding a woman lower than the minimum women's Zwift category"),
        ),
        migrations.AlterField(
            model_name='squad',
            name='enforce_min_zwift_category',
            field=models.BooleanField(default=False, help_text='Block adding a rider lower than the minimum Zwift category'),
        ),
        migrations.AlterField(
            model_name='squad',
            name='enforce_min_zwift_racing_category',
            field=models.BooleanField(default=False, help_text='Block adding a rider lower than the minimum Zwift Racing category'),
        ),
        migrations.AlterField(
            model_name='squad',
            name='max_womens_zwift_category',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], help_text="Maximum women's Zwift category (highest allowed; A high, E low)", max_length=20),
        ),
        migrations.AlterField(
            model_name='squad',
            name='max_zwift_category',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], help_text='Maximum Zwift category (highest allowed; A high, E low)', max_length=20),
        ),
        migrations.AlterField(
            model_name='squad',
            name='min_womens_zwift_category',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], help_text="Minimum women's Zwift category (lowest allowed; A high, E low)", max_length=20),
        ),
        migrations.AlterField(
            model_name='squad',
            name='min_zwift_category',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], help_text='Minimum Zwift category (lowest allowed; A high, E low)', max_length=20),
        ),
    ]
