# Generated by Django 6.1 on 2026-08-26 12:08

from django.db import migrations, models


def seed_region_role_ids(apps, schema_editor):
    """Seed each event's allowed region roles from what its squads already use.

    Squads could previously pick any prefix-matching role as their Region Role. Now the
    choice is limited to Event.region_role_ids, so without this every existing squad's
    region role would fall outside the allowed list and be silently dropped the next time
    anyone edited that squad.
    """
    Event = apps.get_model("events", "Event")
    Squad = apps.get_model("events", "Squad")
    for event in Event.objects.all():
        in_use = sorted(
            {
                str(rid)
                for rid in Squad.objects.filter(event=event)
                .exclude(region_role=0)
                .exclude(region_role__isnull=True)
                .values_list("region_role", flat=True)
                if rid
            }
        )
        if in_use:
            event.region_role_ids = in_use
            event.save(update_fields=["region_role_ids"])


def unseed(apps, schema_editor):
    """No-op reverse: the column is dropped by the AddField's own reversal."""


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0067_alter_squad_enforce_max_womens_zwift_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='region_role_ids',
            field=models.JSONField(blank=True, default=list, help_text="List of Discord role IDs (strings) a squad's Region Role may be chosen from"),
        ),
        migrations.RunPython(seed_region_role_ids, unseed),
    ]
