# Generated by Django 6.1 on 2026-08-26 12:49

from django.db import migrations, models


def seed_captain_role_ids(apps, schema_editor):
    """Seed each event's allowed captain roles from what its squads already use.

    Squads could previously pick any prefix-matching role as their Captain Discord Role.
    Now the choice is limited to Event.captain_role_ids, so without this every existing
    squad's captain role would fall outside the allowed list and be dropped the next time
    anyone edited that squad.

    Unlike the region-role seed in 0068, this filters to roles that actually match the
    event's prefixes. Seeding an off-prefix id makes the Role Setup page un-saveable --
    clean() rejects it, and the checkbox list hides anything off-prefix, so there is no
    way to untick it. A squad using an off-prefix captain role is a misconfiguration to
    surface on the Discord Roles "By Squad" tab, not something to bless silently.
    """
    Event = apps.get_model("events", "Event")
    Squad = apps.get_model("events", "Squad")
    DiscordRole = apps.get_model("team", "DiscordRole")

    for event in Event.objects.all():
        prefixes = [str(p) for p in (event.prefixes or []) if str(p)]
        if not prefixes:
            continue
        in_use = {
            str(rid)
            for rid in Squad.objects.filter(event=event)
            .exclude(discord_captain_role=0)
            .exclude(discord_captain_role__isnull=True)
            .values_list("discord_captain_role", flat=True)
            if rid
        }
        if not in_use:
            continue
        names = dict(DiscordRole.objects.filter(role_id__in=in_use).values_list("role_id", "name"))
        allowed = sorted(
            rid for rid in in_use if any((names.get(rid) or "").startswith(p) for p in prefixes)
        )
        if allowed:
            event.captain_role_ids = allowed
            event.save(update_fields=["captain_role_ids"])


def unseed(apps, schema_editor):
    """No-op reverse: the column is dropped by the AddField's own reversal."""


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0068_add_event_region_role_ids'),
        # seed_captain_role_ids reads team.DiscordRole to check role names against prefixes
        ('team', '0019_recordview'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='captain_role_ids',
            field=models.JSONField(blank=True, default=list, help_text="List of Discord role IDs (strings) a squad's Captain Discord Role may be chosen from"),
        ),
        migrations.RunPython(seed_captain_role_ids, unseed),
    ]
