# Generated by Django 6.1 on 2026-09-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0069_add_event_captain_role_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabilitygrid',
            name='last_notified_at',
            field=models.DateTimeField(blank=True, help_text='When the squad was last notified in Discord about this sheet', null=True),
        ),
    ]
