# Generated by Django 6.1 on 2026-09-03 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0070_add_grid_last_notified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='squad',
            name='notify_captain_expiring_verification',
            field=models.BooleanField(default=False, help_text="Show the squad's captains a banner listing members whose Race Verified status is expiring soon, while the event is still running"),
        ),
    ]
