# Generated by Django 6.1 on 2026-09-10 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0071_add_squad_notify_expiring_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squad',
            name='notify_captain_expiring_verification',
            field=models.BooleanField(default=False, help_text="Show this squad's captains and vice-captains a banner listing members whose Race Verified status is expiring or has lapsed, until the event's end date passes"),
        ),
    ]
