# Generated by Django 6.1 on 2026-09-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0072_squad_notify_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='require_complete_profile_signup',
            field=models.BooleanField(default=True, help_text='Only riders with a complete profile can sign up (or be added by a captain)'),
        ),
        migrations.AddField(
            model_name='event',
            name='require_race_verified_signup',
            field=models.BooleanField(default=False, help_text='Only Race Verified riders can sign up (or be added by a captain)'),
        ),
    ]
