# Generated by Django 6.1.1 on 2026-09-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0073_signup_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='squad_tags',
            field=models.JSONField(blank=True, default=list, help_text='Labels a squad in this event can carry, e.g. Red, Blue, Tall, Short. Removing a tag here removes it from every squad.'),
        ),
        migrations.AddField(
            model_name='squad',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text="Tags from the event's squad tags that this squad carries"),
        ),
    ]
