# Generated by Django 6.0 on 2025-12-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZPTeamRiders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zwid', models.PositiveIntegerField(help_text='Zwift ID', unique=True)),
                ('aid', models.CharField(blank=True, help_text='ZwiftPower athlete ID', max_length=20)),
                ('name', models.CharField(help_text='Rider display name', max_length=255)),
                ('flag', models.CharField(blank=True, help_text='Country code', max_length=10)),
                ('age', models.CharField(blank=True, help_text="Age category (e.g., '50+', 'Mas', '-')", max_length=10)),
                ('div', models.PositiveSmallIntegerField(default=0, help_text='Division')),
                ('divw', models.PositiveSmallIntegerField(default=0, help_text="Women's division")),
                ('r', models.CharField(blank=True, help_text='Rank position', max_length=10)),
                ('rank', models.DecimalField(blank=True, decimal_places=2, help_text='Ranking score', max_digits=10, null=True)),
                ('ftp', models.PositiveSmallIntegerField(blank=True, help_text='FTP in watts', null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=1, help_text='Weight in kg', max_digits=5, null=True)),
                ('skill', models.PositiveIntegerField(default=0, help_text='Total skill score')),
                ('skill_race', models.PositiveIntegerField(default=0, help_text='Racing skill score')),
                ('skill_seg', models.PositiveIntegerField(default=0, help_text='Segment skill score')),
                ('skill_power', models.PositiveIntegerField(default=0, help_text='Power skill score')),
                ('distance', models.PositiveBigIntegerField(default=0, help_text='Total distance in meters')),
                ('climbed', models.PositiveIntegerField(default=0, help_text='Total elevation in meters')),
                ('energy', models.PositiveIntegerField(default=0, help_text='Total energy in kJ')),
                ('time', models.PositiveIntegerField(default=0, help_text='Total time in seconds')),
                ('h_1200_watts', models.PositiveSmallIntegerField(blank=True, help_text='20-min power in watts', null=True)),
                ('h_1200_wkg', models.DecimalField(blank=True, decimal_places=1, help_text='20-min w/kg', max_digits=4, null=True)),
                ('h_15_watts', models.PositiveSmallIntegerField(blank=True, help_text='15-sec power in watts', null=True)),
                ('h_15_wkg', models.DecimalField(blank=True, decimal_places=1, help_text='15-sec w/kg', max_digits=4, null=True)),
                ('status', models.CharField(blank=True, help_text='Member status', max_length=50)),
                ('reg', models.BooleanField(default=False, help_text='Registered flag')),
                ('email', models.EmailField(blank=True, help_text='Email address (if available)', max_length=254)),
                ('zada', models.PositiveSmallIntegerField(default=0, help_text='ZADA status flag')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_left', models.DateTimeField(blank=True, help_text='Date member left team', null=True)),
            ],
            options={
                'verbose_name': 'ZP Team Member',
                'verbose_name_plural': 'ZP Team Members',
                'ordering': ['name'],
            },
        ),
    ]
