# Generated by Django 6.0 on 2026-01-06 14:48

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zwiftpower', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalZPTeamRiders',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('zwid', models.PositiveIntegerField(db_index=True, help_text='Zwift ID')),
                ('aid', models.CharField(blank=True, help_text='ZwiftPower athlete ID', max_length=20)),
                ('name', models.CharField(help_text='Rider display name', max_length=255)),
                ('flag', models.CharField(blank=True, help_text='Country code', max_length=10)),
                ('age', models.CharField(blank=True, help_text="Age category (e.g., '50+', 'Mas', '-')", max_length=10)),
                ('div', models.PositiveSmallIntegerField(default=0, help_text='Division')),
                ('divw', models.PositiveSmallIntegerField(default=0, help_text="Women's division")),
                ('r', models.CharField(blank=True, help_text='Rank position', max_length=10)),
                ('rank', models.DecimalField(blank=True, decimal_places=2, help_text='Ranking score', max_digits=10, null=True)),
                ('ftp', models.PositiveSmallIntegerField(blank=True, help_text='FTP in watts', null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=1, help_text='Weight in kg', max_digits=5, null=True)),
                ('skill', models.PositiveIntegerField(default=0, help_text='Total skill score')),
                ('skill_race', models.PositiveIntegerField(default=0, help_text='Racing skill score')),
                ('skill_seg', models.PositiveIntegerField(default=0, help_text='Segment skill score')),
                ('skill_power', models.PositiveIntegerField(default=0, help_text='Power skill score')),
                ('distance', models.PositiveBigIntegerField(default=0, help_text='Total distance in meters')),
                ('climbed', models.PositiveIntegerField(default=0, help_text='Total elevation in meters')),
                ('energy', models.PositiveIntegerField(default=0, help_text='Total energy in kJ')),
                ('time', models.PositiveIntegerField(default=0, help_text='Total time in seconds')),
                ('h_1200_watts', models.PositiveSmallIntegerField(blank=True, help_text='20-min power in watts', null=True)),
                ('h_1200_wkg', models.DecimalField(blank=True, decimal_places=1, help_text='20-min w/kg', max_digits=4, null=True)),
                ('h_15_watts', models.PositiveSmallIntegerField(blank=True, help_text='15-sec power in watts', null=True)),
                ('h_15_wkg', models.DecimalField(blank=True, decimal_places=1, help_text='15-sec w/kg', max_digits=4, null=True)),
                ('status', models.CharField(blank=True, help_text='Member status', max_length=50)),
                ('reg', models.BooleanField(default=False, help_text='Registered flag')),
                ('email', models.EmailField(blank=True, help_text='Email address (if available)', max_length=254)),
                ('zada', models.SmallIntegerField(default=0, help_text='ZADA status flag (-1=not checked, 0=clean)')),
                ('date_created', models.DateTimeField(blank=True, editable=False)),
                ('date_modified', models.DateTimeField(blank=True, editable=False)),
                ('date_left', models.DateTimeField(blank=True, help_text='Date member left team', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical ZP Team Member',
                'verbose_name_plural': 'historical ZP Team Members',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
