# Generated by Django 6.1 on 2026-08-30 21:47

from django.db import migrations


class Migration(migrations.Migration):
    """Drop the scraped ZwiftPower email.

    The field was populated straight from the ZwiftPower team payload and never read by
    anything except a bot API response. It has been empty for every rider on record, so
    nothing is lost -- but it was personal data we held without a purpose, and it survived
    account deletion in the historical table, which a privacy audit flagged.

    Removing it from ``historicalzpteamriders`` as well is the point: that is where the
    audit found it persisting after erasure.
    """

    dependencies = [
        ('zwiftpower', '0002_historicalzpteamriders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalzpteamriders',
            name='email',
        ),
        migrations.RemoveField(
            model_name='zpteamriders',
            name='email',
        ),
    ]
