# Generated by Django 6.0 on 2025-12-30 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zwiftpower', '0002_add_event_and_results_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zpriderresults',
            name='zada',
            field=models.SmallIntegerField(default=0, help_text='ZADA status (-1=not checked, 0=clean)'),
        ),
        migrations.AlterField(
            model_name='zpteamriders',
            name='zada',
            field=models.SmallIntegerField(default=0, help_text='ZADA status flag (-1=not checked, 0=clean)'),
        ),
    ]
