# Generated by Django 6.1 on 2026-09-12 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zwiftpower', '0003_drop_zp_rider_email'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='zpevent',
            index=models.Index(fields=['event_date'], name='zpevent_event_date_idx'),
        ),
    ]
