# Generated by Django 6.0 on 2026-01-04 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MagicLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, help_text='Unique token for URL', max_length=64, unique=True)),
                ('redirect_url', models.CharField(default='/', help_text='URL to redirect after successful authentication', max_length=500)),
                ('used', models.BooleanField(default=False, help_text='Whether this link has been used')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_expires', models.DateTimeField(help_text='When this link expires')),
                ('user', models.ForeignKey(help_text='User this magic link authenticates', on_delete=django.db.models.deletion.CASCADE, related_name='magic_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Magic Link',
                'verbose_name_plural': 'Magic Links',
                'ordering': ['-date_created'],
            },
        ),
    ]
