# Generated by Django 6.0.6 on 2026-06-15 21:56

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Route",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="Route name", max_length=200)),
                ("world", models.CharField(blank=True, help_text="Zwift world (e.g. Watopia)", max_length=100)),
                ("distance_km", models.DecimalField(decimal_places=2, help_text="Route distance in km", max_digits=6)),
                ("elevation_m", models.PositiveIntegerField(default=0, help_text="Total elevation gain in metres")),
                (
                    "zwift_route_id",
                    models.CharField(blank=True, help_text="Zwift route identifier, if known", max_length=50),
                ),
                ("is_active", models.BooleanField(default=True, help_text="Show in the route picker")),
            ],
            options={
                "verbose_name": "TTT Route",
                "verbose_name_plural": "TTT Routes",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TttPlan",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, help_text="Plan name", max_length=200)),
                ("team_name", models.CharField(blank=True, help_text="Team name shown on the plan", max_length=200)),
                (
                    "target_speed_kph",
                    models.DecimalField(
                        decimal_places=1, default=40.0, help_text="Target flat speed in km/h", max_digits=5
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created the plan",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ttt_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        blank=True,
                        help_text="Selected route",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="plans",
                        to="ttt_planner.route",
                    ),
                ),
            ],
            options={
                "verbose_name": "TTT Plan",
                "verbose_name_plural": "TTT Plans",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="PlanRider",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order", models.PositiveIntegerField(default=0, help_text="Pull order (0-based)")),
                (
                    "zwid",
                    models.PositiveIntegerField(blank=True, help_text="Zwift ID, if linked to team data", null=True),
                ),
                ("name", models.CharField(help_text="Rider display name", max_length=200)),
                (
                    "weight_kg",
                    models.DecimalField(
                        blank=True, decimal_places=1, help_text="Weight in kg", max_digits=5, null=True
                    ),
                ),
                ("height_cm", models.PositiveSmallIntegerField(blank=True, help_text="Height in cm", null=True)),
                ("ftp_w", models.PositiveSmallIntegerField(blank=True, help_text="FTP in watts", null=True)),
                (
                    "pull_power_w",
                    models.PositiveSmallIntegerField(blank=True, help_text="Override pull power in watts", null=True),
                ),
                ("pull_duration_s", models.PositiveIntegerField(default=60, help_text="Pull duration in seconds")),
                (
                    "zero_pull",
                    models.BooleanField(default=False, help_text="Rider takes no pulls (sits in for recovery)"),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="riders", to="ttt_planner.tttplan"
                    ),
                ),
            ],
            options={
                "verbose_name": "Plan Rider",
                "verbose_name_plural": "Plan Riders",
                "ordering": ["order", "id"],
            },
        ),
    ]
