# Generated by Django 6.0.6 on 2026-06-16 03:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ttt_planner", "0002_seed_routes"),
    ]

    operations = [
        migrations.AddField(
            model_name="tttplan",
            name="draft_savings",
            field=models.CharField(
                blank=True,
                help_text="Per-plan aero draft savings by wheel position (e.g. '0, 23.3, 30, 36.6'). Blank uses the global TTT_DRAFT_SAVINGS default.",
                max_length=200,
            ),
        ),
    ]
