# Generated by Django 6.0.6 on 2026-06-16 03:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ttt_planner", "0004_draft_savings_json"),
    ]

    operations = [
        migrations.AddField(
            model_name="tttplan",
            name="cda_coef",
            field=models.FloatField(
                blank=True,
                help_text="Per-plan aero CdA coefficient. Blank uses the global TTT_CDA_COEF default.",
                null=True,
            ),
        ),
    ]
