# Generated by Django 6.0.6 on 2026-06-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ttt_planner", "0005_tttplan_cda_coef"),
    ]

    operations = [
        migrations.AddField(
            model_name="tttplan",
            name="zwiftgopher_error",
            field=models.CharField(blank=True, help_text="Error from the last zwiftgopher run", max_length=300),
        ),
        migrations.AddField(
            model_name="tttplan",
            name="zwiftgopher_fetched_at",
            field=models.DateTimeField(blank=True, help_text="When the last zwiftgopher result was fetched", null=True),
        ),
        migrations.AddField(
            model_name="tttplan",
            name="zwiftgopher_result",
            field=models.JSONField(
                blank=True, help_text="Normalized result from the last zwiftgopher optimize run", null=True
            ),
        ),
        migrations.AddField(
            model_name="tttplan",
            name="zwiftgopher_status",
            field=models.CharField(
                blank=True,
                choices=[("", "Not run"), ("pending", "Running"), ("done", "Done"), ("error", "Error")],
                default="",
                help_text="zwiftgopher run status",
                max_length=10,
            ),
        ),
    ]
