# Generated by Django 6.0.6 on 2026-06-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ttt_planner", "0007_import_full_routes"),
    ]

    operations = [
        migrations.AddField(
            model_name="tttplan",
            name="zwiftgopher_raw_response",
            field=models.JSONField(
                blank=True, help_text="Raw JSON response from the zwiftgopher optimize API", null=True
            ),
        ),
        migrations.AddField(
            model_name="tttplan",
            name="zwiftgopher_request",
            field=models.JSONField(
                blank=True, help_text="Raw request body sent to the zwiftgopher optimize API", null=True
            ),
        ),
    ]
