# Generated by Django 6.0.6 on 2026-06-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ttt_planner", "0008_tttplan_zwiftgopher_raw_response_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tttplan",
            name="event_type",
            field=models.CharField(
                blank=True,
                choices=[("zrl", "ZRL"), ("drs", "DRS"), ("wtrl_ttt", "WTRL TTT"), ("other", "Other")],
                default="",
                help_text="Event this plan targets",
                max_length=20,
            ),
        ),
    ]
