# Generated by Django 6.0.6 on 2026-06-16 19:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ttt_planner", "0009_tttplan_event_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="tttplan",
            name="target_if",
            field=models.FloatField(
                default=0.95, help_text="Target intensity factor used by Calculate / Auto-balance (e.g. 0.95)"
            ),
        ),
    ]
