# Generated by Django 6.0.6 on 2026-06-17 23:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ttt_planner", "0010_tttplan_target_if"),
    ]

    operations = [
        migrations.AddField(
            model_name="tttplan",
            name="course_name",
            field=models.CharField(blank=True, help_text="Course / route name (free text)", max_length=200),
        ),
        migrations.AddField(
            model_name="tttplan",
            name="course_type",
            field=models.CharField(
                blank=True,
                choices=[("flat", "Flat"), ("rolling", "Rolling"), ("hilly", "Hilly"), ("mountainous", "Mountainous")],
                help_text="Terrain type (informational; prefilled from the route)",
                max_length=20,
            ),
        ),
    ]
