# Generated by Django 6.0.6 on 2026-06-17 23:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ttt_planner", "0011_tttplan_course_name_tttplan_course_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RouteGpx",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "label",
                    models.CharField(
                        blank=True, help_text="Label for this track (e.g. spawn point / lead-in)", max_length=200
                    ),
                ),
                ("file", models.FileField(help_text="The uploaded .gpx file", upload_to="route_gpx/")),
                ("notes", models.TextField(blank=True, help_text="Free-text notes: start point and lead-in")),
                (
                    "distance_km",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Distance parsed from the GPX (km)",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "elevation_m",
                    models.PositiveIntegerField(
                        blank=True, help_text="Elevation gain parsed from the GPX (m)", null=True
                    ),
                ),
                (
                    "terrain",
                    models.CharField(blank=True, help_text="Terrain type derived from the parsed GPX", max_length=20),
                ),
                ("point_count", models.PositiveIntegerField(default=0, help_text="Number of track points parsed")),
                (
                    "parse_error",
                    models.CharField(blank=True, help_text="Error from parsing the GPX, if any", max_length=300),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="gpx_files", to="ttt_planner.route"
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Route GPX",
                "verbose_name_plural": "Route GPX files",
                "ordering": ["route", "label", "id"],
            },
        ),
    ]
