# Generated by Django 6.0.6 on 2026-06-17 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttt_planner', '0012_routegpx'),
    ]

    operations = [
        migrations.AddField(
            model_name='routegpx',
            name='profile',
            field=models.JSONField(blank=True, default=list, help_text='Downsampled elevation profile: [[distance_km, elevation_m], ...]'),
        ),
    ]
