# Generated by Django 6.0.6 on 2026-06-24 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttt_planner', '0013_routegpx_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_type', models.CharField(choices=[('kqom', 'KQOM'), ('sprint', 'Sprint')], help_text='King/Queen of the Mountain or Sprint', max_length=10)),
                ('name', models.CharField(help_text='Segment name', max_length=200)),
                ('notes', models.TextField(blank=True, help_text='Free-text notes')),
                ('length_m', models.PositiveIntegerField(default=0, help_text='Segment length in metres')),
                ('elevation_m', models.PositiveIntegerField(default=0, help_text='Segment elevation gain in metres')),
                ('world', models.CharField(blank=True, help_text='Zwift world (e.g. Watopia)', max_length=100)),
                ('strava_url', models.URLField(blank=True, help_text='Strava segment URL')),
                ('zwiftinsider_url', models.URLField(blank=True, help_text='ZwiftInsider segment URL')),
                ('whatsonzwift_url', models.URLField(blank=True, help_text='whatsonzwift.com segment URL')),
            ],
            options={
                'verbose_name': 'Segment',
                'verbose_name_plural': 'Segments',
                'ordering': ['world', 'name'],
            },
        ),
        migrations.AddField(
            model_name='route',
            name='lead_in_distance_km',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Lead-in distance in km (before the lap starts)', max_digits=6),
        ),
        migrations.AddField(
            model_name='route',
            name='lead_in_elevation_m',
            field=models.PositiveIntegerField(default=0, help_text='Lead-in elevation gain in metres'),
        ),
        migrations.AddField(
            model_name='route',
            name='recommended_laps',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Club Ladder recommended number of laps', null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='supports_laps',
            field=models.BooleanField(default=False, help_text='Route can be ridden as multiple laps'),
        ),
        migrations.AddField(
            model_name='route',
            name='zwiftinsider_url',
            field=models.URLField(blank=True, help_text='ZwiftInsider route page URL'),
        ),
        migrations.AddField(
            model_name='route',
            name='segments',
            field=models.ManyToManyField(blank=True, help_text='Climbs and sprints (KQOM / Sprint) on this route', related_name='routes', to='ttt_planner.segment'),
        ),
    ]
