# Generated by Django 6.0.6 on 2026-06-24 14:19

from django.db import migrations, models


def kqom_to_climb(apps, schema_editor):
    """Convert any existing segment_type 'kqom' rows to 'climb'."""
    Segment = apps.get_model("ttt_planner", "Segment")
    Segment.objects.filter(segment_type="kqom").update(segment_type="climb")


def climb_to_kqom(apps, schema_editor):
    """Reverse: 'climb' -> 'kqom'."""
    Segment = apps.get_model("ttt_planner", "Segment")
    Segment.objects.filter(segment_type="climb").update(segment_type="kqom")


class Migration(migrations.Migration):

    dependencies = [
        ('ttt_planner', '0014_segment_route_lead_in_distance_km_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='segments',
            field=models.ManyToManyField(blank=True, help_text='Climbs and sprints on this route', related_name='routes', to='ttt_planner.segment'),
        ),
        migrations.AlterField(
            model_name='segment',
            name='segment_type',
            field=models.CharField(choices=[('climb', 'Climb'), ('sprint', 'Sprint')], help_text='Climb or Sprint', max_length=10),
        ),
        migrations.RunPython(kqom_to_climb, climb_to_kqom),
    ]
