# Generated by Django 6.0.6 on 2026-06-24 14:48

from django.db import migrations, models

import apps.ttt_planner.worlds


class Migration(migrations.Migration):

    dependencies = [
        ('ttt_planner', '0015_alter_route_segments_alter_segment_segment_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='segment',
            options={'ordering': ['world', 'name', 'direction'], 'verbose_name': 'Segment', 'verbose_name_plural': 'Segments'},
        ),
        migrations.AddField(
            model_name='segment',
            name='category',
            field=models.CharField(blank=True, help_text='Climb category (HC, 1-4) if applicable', max_length=5),
        ),
        migrations.AddField(
            model_name='segment',
            name='direction',
            field=models.CharField(blank=True, choices=[('forward', 'Forward'), ('reverse', 'Reverse')], help_text='Forward or Reverse (blank if single-direction)', max_length=10),
        ),
        migrations.AddField(
            model_name='segment',
            name='grade_pct',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Average grade %', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='world',
            field=models.CharField(blank=True, choices=apps.ttt_planner.worlds.world_choices, help_text='Zwift world', max_length=100),
        ),
        migrations.AlterField(
            model_name='segment',
            name='segment_type',
            field=models.CharField(choices=[('climb', 'Climb'), ('sprint', 'Sprint'), ('segment', 'Segment')], help_text='Climb, Sprint, or generic Segment', max_length=10),
        ),
        migrations.AlterField(
            model_name='segment',
            name='world',
            field=models.CharField(blank=True, choices=apps.ttt_planner.worlds.world_choices, help_text='Zwift world', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='segment',
            constraint=models.UniqueConstraint(fields=('name', 'world', 'direction'), name='unique_segment_name_world_direction'),
        ),
    ]
