# Generated by Django 6.0.6 on 2026-06-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttt_planner', '0016_alter_segment_options_segment_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='PowerUp name (e.g. Feather)', max_length=100, unique=True)),
                ('aka', models.CharField(blank=True, help_text='Alternate name (e.g. Lightweight)', max_length=100)),
                ('slug', models.SlugField(blank=True, help_text='URL/icon slug (auto from name)', max_length=120, unique=True)),
                ('effect', models.TextField(blank=True, help_text='What the PowerUp does, including duration')),
                ('duration_seconds', models.PositiveIntegerField(default=0, help_text='Effect duration in seconds (0 = instant/none)')),
                ('event_only', models.BooleanField(default=False, help_text='Only available in events')),
                ('excluded_from_ladder', models.BooleanField(default=False, help_text='Does not count for the Club Ladder')),
                ('icon', models.ImageField(blank=True, help_text='PowerUp icon image', upload_to='powerup_icons/')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order on the routes page')),
                ('is_active', models.BooleanField(default=True, help_text='Show in the PowerUps list')),
            ],
            options={
                'verbose_name': 'PowerUp',
                'verbose_name_plural': 'PowerUps',
                'ordering': ['order', 'name'],
            },
        ),
    ]
