# Generated by Django 6.0.6 on 2026-06-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttt_planner', '0018_seed_powerups'),
    ]

    operations = [
        migrations.AddField(
            model_name='powerup',
            name='discord_emoji',
            field=models.CharField(blank=True, help_text='Discord custom-emoji code to show in race threads, e.g. <:feather:123456789012345678>', max_length=100),
        ),
    ]
