# Generated by Django 6.0.6 on 2026-07-01 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttt_planner', '0019_powerup_discord_emoji'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='velo_climb',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='vELO2 Race weight: Climb (%)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='velo_endurance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='vELO2 Race weight: Endurance (%)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='velo_punch',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='vELO2 Race weight: Punch (%)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='velo_pursuit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='vELO2 Race weight: Pursuit (%)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='velo_sprint',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='vELO2 Race weight: Sprint (%)', max_digits=5, null=True),
        ),
    ]
