# Generated by Django 6.0.7 on 2026-07-20 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ttt_planner', '0020_route_velo_climb_route_velo_endurance_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RouteGpx',
        ),
    ]
