# Generated by Django 6.0.7 on 2026-07-27 14:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ttt_planner", "0022_repoint_plan_route_delete_route_segment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planrider",
            name="pull_duration_s",
            field=models.PositiveIntegerField(
                default=60,
                help_text="Pull duration in seconds",
                validators=[django.core.validators.MaxValueValidator(300)],
            ),
        ),
        migrations.AlterField(
            model_name="planrider",
            name="pull_power_w",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Override pull power in watts",
                null=True,
                validators=[django.core.validators.MaxValueValidator(1500)],
            ),
        ),
    ]
