# Generated by Django 6.0.7 on 2026-07-27 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0055_availabilitygrid_require_race_verified_availability"),
        ("ttt_planner", "0023_alter_planrider_pull_duration_s_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tttplan",
            name="edit_squad",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional squad whose members (incl. captains/vice-captains) may also edit this plan",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="events.squad",
            ),
        ),
    ]
