# Generated by Django 6.1.1 on 2026-10-01 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0074_squad_tags"),
        ("ttt_planner", "0024_tttplan_edit_squad"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="tttplan",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Who last changed the plan",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="tttplan",
            name="edit_squad",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional squad whose members (incl. captains/vice-captains) edit this plan as its creator does; any other team member is asked to confirm first (gotta_bike_platform/planner_access.py)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="events.squad",
            ),
        ),
    ]
