# Generated by Django 6.0 on 2026-01-04 00:09

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('discord_id', models.CharField(blank=True, help_text='Discord user ID (snowflake)', max_length=20)),
                ('discord_username', models.CharField(blank=True, help_text='Discord username', max_length=100)),
                ('discord_nickname', models.CharField(blank=True, help_text='Discord server nickname', max_length=100)),
                ('discord_avatar', models.CharField(blank=True, help_text='Discord avatar hash', max_length=100)),
                ('discord_roles', models.JSONField(blank=True, default=dict, help_text='Discord roles as {role_id: role_name}')),
                ('zwid', models.PositiveIntegerField(blank=True, help_text='Zwift user ID', null=True)),
                ('zwid_verified', models.BooleanField(default=False, help_text='Zwift user ID has been verified')),
                ('birth_year', models.PositiveSmallIntegerField(blank=True, help_text='Year of birth (e.g., 1990)', null=True)),
                ('city', models.CharField(blank=True, help_text='City of residence', max_length=100)),
                ('country', models.CharField(blank=True, help_text='Country of residence', max_length=100)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], help_text='Gender', max_length=10)),
                ('timezone', models.CharField(blank=True, help_text="User's timezone (e.g., America/New_York)", max_length=50)),
                ('youtube_channel', models.URLField(blank=True, help_text='YouTube channel URL')),
                ('roles', models.JSONField(blank=True, default=list, help_text='List of user roles (legacy - use permission_overrides for new grants)')),
                ('permission_overrides', models.JSONField(blank=True, default=dict, help_text='Manual permission overrides: {permission_name: True/False}. True grants, False revokes.')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='GuildMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_id', models.CharField(db_index=True, help_text='Discord user ID (snowflake)', max_length=20, unique=True)),
                ('username', models.CharField(help_text='Discord username', max_length=100)),
                ('display_name', models.CharField(blank=True, help_text='Discord global display name', max_length=100)),
                ('nickname', models.CharField(blank=True, help_text='Server-specific nickname', max_length=100)),
                ('avatar_hash', models.CharField(blank=True, help_text='Discord avatar hash for CDN URL', max_length=100)),
                ('roles', models.JSONField(blank=True, default=list, help_text='List of Discord role IDs')),
                ('joined_at', models.DateTimeField(blank=True, help_text='When the member joined the guild', null=True)),
                ('is_bot', models.BooleanField(default=False, help_text='Whether this member is a bot')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('date_left', models.DateTimeField(blank=True, help_text='When the member left the guild (null if still present)', null=True)),
                ('user', models.OneToOneField(blank=True, help_text='Linked Django User account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guild_member', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Guild Member',
                'verbose_name_plural': 'Guild Members',
                'ordering': ['-date_modified'],
            },
        ),
    ]
