# Generated by Django 6.0 on 2025-12-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='zwid_verified',
            field=models.BooleanField(default=False, help_text='Zwift user ID has been verified'),
        ),
    ]
