# Generated by Django 6.0.1 on 2026-01-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='unit_preference',
            field=models.CharField(choices=[('metric', 'Metric (kg, cm)'), ('imperial', 'Imperial (lbs, in)')], default='metric', help_text='Preferred unit system for weight and height', max_length=10),
        ),
    ]
