# Generated by Django 6.0 on 2025-12-28 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_zwid_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.JSONField(blank=True, default=list, help_text='List of user roles'),
        ),
    ]
