# Generated by Django 6.0.1 on 2026-01-08 15:41

import django_countries.fields
from django.db import migrations


def set_all_countries_to_us(apps, schema_editor):
    """Set all existing country values to 'US' for migration to CountryField."""
    User = apps.get_model("accounts", "User")
    User.objects.update(country="US")


def reverse_noop(apps, schema_editor):
    """No-op reverse migration - country values cannot be restored."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_unit_preference'),
    ]

    operations = [
        # First, convert all existing values to 'US' (valid 2-letter ISO code)
        migrations.RunPython(set_all_countries_to_us, reverse_noop),
        # Then change the field type to CountryField (max_length=2)
        migrations.AlterField(
            model_name='user',
            name='country',
            field=django_countries.fields.CountryField(blank=True, help_text='Country of residence', max_length=2),
        ),
    ]
