# Generated by Django 6.0.1 on 2026-01-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_convert_country_to_countryfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='emergency_contact_email',
            field=models.EmailField(blank=True, default='', help_text='Emergency contact email address', max_length=254),
        ),
        migrations.AddField(
            model_name='user',
            name='emergency_contact_name',
            field=models.CharField(blank=True, default='', help_text='Emergency contact full name', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, default='', help_text='Emergency contact phone number', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='emergency_contact_relation',
            field=models.CharField(blank=True, default='', help_text='Relationship to emergency contact (e.g., spouse, parent, friend)', max_length=100),
        ),
    ]
