# Generated by Django 6.0 on 2025-12-28 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_roles_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='discord_avatar',
            field=models.CharField(blank=True, help_text='Discord avatar hash', max_length=100),
        ),
    ]
