# Generated by Django 6.0.1 on 2026-01-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_emergency_contact_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bluesky_url',
            field=models.URLField(blank=True, help_text='BlueSky profile URL'),
        ),
        migrations.AddField(
            model_name='user',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Facebook profile URL'),
        ),
        migrations.AddField(
            model_name='user',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Instagram profile URL'),
        ),
        migrations.AddField(
            model_name='user',
            name='mastodon_url',
            field=models.URLField(blank=True, help_text='Mastodon profile URL'),
        ),
        migrations.AddField(
            model_name='user',
            name='tiktok_url',
            field=models.URLField(blank=True, help_text='TikTok profile URL'),
        ),
        migrations.AddField(
            model_name='user',
            name='twitch_channel',
            field=models.URLField(blank=True, help_text='Twitch channel URL'),
        ),
        migrations.AddField(
            model_name='user',
            name='twitter_url',
            field=models.URLField(blank=True, help_text='Twitter/X profile URL'),
        ),
    ]
