# Generated by Django 6.0 on 2025-12-30 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_discord_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Year of birth (e.g., 1990)', null=True),
        ),
    ]
