# Generated by Django 6.0.1 on 2026-01-15 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_social_account_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dual_recording',
            field=models.BooleanField(blank=True, default=None, help_text='Do you dual record data?', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='powermeter',
            field=models.CharField(blank=True, default='', help_text='Powermeter on trainer bike, if any (options from POWERMETER_OPTIONS)', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='trainer',
            field=models.CharField(blank=True, default='', help_text='Indoor trainer model (options from TRAINER_OPTIONS)', max_length=100),
        ),
    ]
