# Generated by Django 6.0 on 2025-12-30 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_birth_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='discord_roles',
            field=models.JSONField(blank=True, default=dict, help_text='Discord roles as {role_id: role_name}'),
        ),
    ]
