# Generated by Django 6.0.1 on 2026-01-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_dual_recording_user_powermeter_user_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='garmin_url',
            field=models.URLField(blank=True, help_text='Garmin Connect profile URL (e.g., https://connect.garmin.com/modern/profile/username)'),
        ),
        migrations.AddField(
            model_name='user',
            name='strava_url',
            field=models.URLField(blank=True, help_text='Strava profile URL (e.g., https://www.strava.com/athletes/1234)'),
        ),
    ]
