# Generated by Django 6.0.1 on 2026-01-17 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_add_strava_garmin_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='heartrate_monitor',
            field=models.CharField(blank=True, default='', help_text='Heart rate monitor brand (options from HEARTRATE_MONITOR_OPTIONS)', max_length=100),
        ),
    ]
