# Generated by Django 6.0 on 2025-12-31 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_add_user_profile_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='youtube_channel',
            field=models.URLField(blank=True, help_text='YouTube channel URL'),
        ),
    ]
