# Generated by Django 6.0.1 on 2026-01-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_heartrate_monitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tpv_profile_url',
            field=models.URLField(blank=True, help_text='TrainingPeaks Virtual profile URL (e.g., https://tpvirtualhub.com/profile/GGGTTTRRRDDD123)'),
        ),
    ]
