# Generated by Django 6.0 on 2026-01-01 22:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_add_youtube_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuildMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_id', models.CharField(db_index=True, help_text='Discord user ID (snowflake)', max_length=20, unique=True)),
                ('username', models.CharField(help_text='Discord username', max_length=100)),
                ('display_name', models.CharField(blank=True, help_text='Discord global display name', max_length=100)),
                ('nickname', models.CharField(blank=True, help_text='Server-specific nickname', max_length=100)),
                ('avatar_hash', models.CharField(blank=True, help_text='Discord avatar hash for CDN URL', max_length=100)),
                ('roles', models.JSONField(blank=True, default=list, help_text='List of Discord role IDs')),
                ('joined_at', models.DateTimeField(blank=True, help_text='When the member joined the guild', null=True)),
                ('is_bot', models.BooleanField(default=False, help_text='Whether this member is a bot')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('date_left', models.DateTimeField(blank=True, help_text='When the member left the guild (null if still present)', null=True)),
                ('user', models.OneToOneField(blank=True, help_text='Linked Django User account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guild_member', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Guild Member',
                'verbose_name_plural': 'Guild Members',
                'ordering': ['-date_modified'],
            },
        ),
    ]
