# Generated by Django 6.0.1 on 2026-02-02 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_tpv_profile_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='youtube_channel_id',
            field=models.CharField(blank=True, help_text='YouTube channel ID (auto-extracted from URL)', max_length=30),
        ),
    ]
