# Generated by Django 6.0.1 on 2026-02-03 02:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_add_youtube_channel_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(help_text='YouTube video ID', max_length=20)),
                ('title', models.CharField(help_text='Video title', max_length=500)),
                ('thumbnail_url', models.URLField(blank=True, help_text='Video thumbnail URL', max_length=300)),
                ('published_at', models.DateTimeField(blank=True, help_text='Video publish date', null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text="User who owns this video's channel", on_delete=django.db.models.deletion.CASCADE, related_name='youtube_videos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'YouTube Video',
                'verbose_name_plural': 'YouTube Videos',
                'ordering': ['-published_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'video_id'), name='unique_user_video')],
            },
        ),
    ]
