# Generated by Django 6.0.2 on 2026-02-25 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_add_youtube_video_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='zwid',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='Zwift user ID', null=True),
        ),
    ]
