# Generated by Django 6.0.2 on 2026-02-27 02:39

from django.db import migrations, models


def populate_race_ready(apps, schema_editor):
    """Populate is_race_ready for existing users using the live model's calculate_race_ready()."""
    from apps.accounts.models import User

    users = (
        User.objects
        .exclude(discord_id="")
        .exclude(discord_id__isnull=True)
        .prefetch_related("race_ready_records")
    )
    to_update = []
    for user in users:
        if user.calculate_race_ready():
            user.is_race_ready = True
            to_update.append(user)
    if to_update:
        User.objects.bulk_update(to_update, ["is_race_ready"])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_user_zwid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_race_ready',
            field=models.BooleanField(default=False, help_text='Cached race ready status. Updated when verification records change and by periodic cron task.'),
        ),
        migrations.RunPython(populate_race_ready, migrations.RunPython.noop),
    ]
