# Generated by Django 6.0.2 on 2026-03-03 13:35

from django.db import migrations, models


def populate_extra_verified(apps, schema_editor):
    """Populate is_extra_verified for existing users using the live model's calculate_extra_verified()."""
    from apps.accounts.models import User

    users = User.objects.exclude(discord_id="").exclude(discord_id__isnull=True).prefetch_related("race_ready_records")
    to_update = []
    for user in users:
        if user.calculate_extra_verified():
            user.is_extra_verified = True
            to_update.append(user)
    if to_update:
        User.objects.bulk_update(to_update, ["is_extra_verified"])


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0013_add_is_race_ready_cached_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_extra_verified",
            field=models.BooleanField(
                default=False,
                help_text="Cached extra verified status. True when weight_full + height + power are all verified and non-expired.",
            ),
        ),
        migrations.RunPython(populate_extra_verified, migrations.RunPython.noop),
    ]
