# Generated by Django 6.0.2 on 2026-03-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_add_is_extra_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_extra_verified',
            field=models.BooleanField(default=False, help_text='Cached extra verified status (weight_full + height + power all verified and non-expired).'),
        ),
    ]
