# Generated by Django 6.0.4 on 2026-04-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_unique_social_account_per_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_jersey',
            field=models.BooleanField(default=False, help_text='User has a team jersey'),
        ),
    ]
