# Generated by Django 6.0.7 on 2026-07-25 19:51

from django.db import migrations, models


def grandfather_legacy_verifications(apps, schema_editor):
    """Mark every already-verified user as legacy-method.

    Existing ``zwid_verified=True`` users were verified via the old Sauce-mod
    flow (or admin) — there's no retroactive signal to distinguish the two, so
    they are all grandfathered as ``legacy``. ``zwid_verified_at`` is left null
    (the original verification date is unknown). New verifications going forward
    set the method explicitly. Uses the historical model, never the live one.
    """
    user_model = apps.get_model("accounts", "User")
    # Only rows without a method yet (all of them at migration time). Filtering on
    # empty keeps the backfill idempotent and unable to clobber a method already set.
    user_model.objects.filter(zwid_verified=True, zwid_verification_method="").update(
        zwid_verification_method="legacy"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_add_has_jersey'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='zwid_verification_method',
            field=models.CharField(blank=True, choices=[('legacy', 'Legacy (Sauce mod)'), ('zauth', 'Zwift OAuth (zauth)'), ('admin', 'Admin (manual)')], default='', help_text='How the current Zwift verification was obtained (legacy / zauth / admin)', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='zwid_verified_at',
            field=models.DateTimeField(blank=True, help_text='When the current Zwift verification was recorded', null=True),
        ),
        migrations.RunPython(grandfather_legacy_verifications, migrations.RunPython.noop),
    ]
