# Generated by Django 6.0.7 on 2026-08-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_user_zwid_verification_method_user_zwid_verified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='z_ftp',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='zFTP in watts, from the official Zwift racing profile', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='z_map',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='zMAP in watts, from the official Zwift racing profile', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='z_metrics_updated_at',
            field=models.DateTimeField(blank=True, help_text='When zFTP/zMAP were last mirrored from the zauth service', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='z_metrics_weight_grams',
            field=models.PositiveIntegerField(blank=True, help_text='Weight Zwift used when it computed zFTP/zMAP - the denominator for W/kg', null=True),
        ),
    ]
