# Generated by Django 6.1 on 2026-08-28 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_user_z_ftp_user_z_map_user_z_metrics_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedDiscordId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_id', models.CharField(help_text='Discord user ID to block', max_length=20, unique=True)),
                ('note', models.CharField(blank=True, help_text='Why this account is blocked', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the block was added')),
                ('blocked_by', models.ForeignKey(blank=True, help_text='Admin who added this block', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_discord_ids', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blocked Discord ID',
                'verbose_name_plural': 'Blocked Discord IDs',
                'ordering': ['-created_at'],
            },
        ),
    ]
