# Generated by Django 6.1 on 2026-08-30 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_add_blocked_discord_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='discord_dm_opt_out',
            field=models.BooleanField(default=False, help_text='If set, the bot sends this member no direct messages'),
        ),
    ]
