# Generated by Django 6.1 on 2026-09-10 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_add_discord_dm_opt_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='team_kit',
            field=models.JSONField(blank=True, default=dict, help_text='Team kit status per kit, as {kit_slug: status}'),
        ),
    ]
