# Generated by Django 6.1 on 2026-09-15 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_team_kit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='has_jersey',
        ),
    ]
