# Generated by Django 6.0 on 2025-12-25 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZRRider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rider_id', models.PositiveIntegerField(help_text='Zwift Racing rider ID', unique=True)),
                ('name', models.CharField(help_text='Rider display name', max_length=255)),
                ('gender', models.CharField(blank=True, help_text='Gender (M/F)', max_length=10)),
                ('country', models.CharField(blank=True, help_text='Country code', max_length=10)),
                ('age', models.CharField(blank=True, help_text='Age category', max_length=10)),
                ('height', models.PositiveSmallIntegerField(blank=True, help_text='Height in cm', null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=1, help_text='Weight in kg', max_digits=5, null=True)),
                ('zp_category', models.CharField(blank=True, help_text='ZwiftPower category (A/B/C/D/E)', max_length=5)),
                ('zp_ftp', models.PositiveSmallIntegerField(blank=True, help_text='ZwiftPower FTP', null=True)),
                ('power_wkg5', models.DecimalField(blank=True, decimal_places=2, help_text='5-sec w/kg', max_digits=6, null=True)),
                ('power_wkg15', models.DecimalField(blank=True, decimal_places=2, help_text='15-sec w/kg', max_digits=6, null=True)),
                ('power_wkg30', models.DecimalField(blank=True, decimal_places=2, help_text='30-sec w/kg', max_digits=6, null=True)),
                ('power_wkg60', models.DecimalField(blank=True, decimal_places=2, help_text='60-sec w/kg', max_digits=6, null=True)),
                ('power_wkg120', models.DecimalField(blank=True, decimal_places=2, help_text='2-min w/kg', max_digits=6, null=True)),
                ('power_wkg300', models.DecimalField(blank=True, decimal_places=2, help_text='5-min w/kg', max_digits=6, null=True)),
                ('power_wkg1200', models.DecimalField(blank=True, decimal_places=2, help_text='20-min w/kg', max_digits=6, null=True)),
                ('power_w5', models.PositiveSmallIntegerField(blank=True, help_text='5-sec watts', null=True)),
                ('power_w15', models.PositiveSmallIntegerField(blank=True, help_text='15-sec watts', null=True)),
                ('power_w30', models.PositiveSmallIntegerField(blank=True, help_text='30-sec watts', null=True)),
                ('power_w60', models.PositiveSmallIntegerField(blank=True, help_text='60-sec watts', null=True)),
                ('power_w120', models.PositiveSmallIntegerField(blank=True, help_text='2-min watts', null=True)),
                ('power_w300', models.PositiveSmallIntegerField(blank=True, help_text='5-min watts', null=True)),
                ('power_w1200', models.PositiveSmallIntegerField(blank=True, help_text='20-min watts', null=True)),
                ('power_cp', models.DecimalField(blank=True, decimal_places=2, help_text='Critical Power', max_digits=7, null=True)),
                ('power_awc', models.DecimalField(blank=True, decimal_places=2, help_text='Anaerobic Work Capacity', max_digits=10, null=True)),
                ('power_compound_score', models.DecimalField(blank=True, decimal_places=2, help_text='Compound score', max_digits=10, null=True)),
                ('race_current_rating', models.DecimalField(blank=True, decimal_places=2, help_text='Current race rating', max_digits=10, null=True)),
                ('race_current_date', models.BigIntegerField(blank=True, help_text='Current rating date (timestamp)', null=True)),
                ('race_current_category', models.CharField(blank=True, help_text='Current mixed category', max_length=20)),
                ('race_current_category_num', models.PositiveSmallIntegerField(blank=True, help_text='Current category number', null=True)),
                ('race_last_rating', models.DecimalField(blank=True, decimal_places=2, help_text='Last race rating', max_digits=10, null=True)),
                ('race_last_date', models.BigIntegerField(blank=True, help_text='Last rating date (timestamp)', null=True)),
                ('race_last_category', models.CharField(blank=True, help_text='Last mixed category', max_length=20)),
                ('race_last_category_num', models.PositiveSmallIntegerField(blank=True, help_text='Last category number', null=True)),
                ('race_max30_rating', models.DecimalField(blank=True, decimal_places=2, help_text='Max 30-day rating', max_digits=10, null=True)),
                ('race_max30_date', models.BigIntegerField(blank=True, help_text='Max 30-day date (timestamp)', null=True)),
                ('race_max30_expires', models.BigIntegerField(blank=True, help_text='Max 30-day expires (timestamp)', null=True)),
                ('race_max30_category', models.CharField(blank=True, help_text='Max 30-day category', max_length=20)),
                ('race_max30_category_num', models.PositiveSmallIntegerField(blank=True, help_text='Max 30-day category number', null=True)),
                ('race_max90_rating', models.DecimalField(blank=True, decimal_places=2, help_text='Max 90-day rating', max_digits=10, null=True)),
                ('race_max90_date', models.BigIntegerField(blank=True, help_text='Max 90-day date (timestamp)', null=True)),
                ('race_max90_expires', models.BigIntegerField(blank=True, help_text='Max 90-day expires (timestamp)', null=True)),
                ('race_max90_category', models.CharField(blank=True, help_text='Max 90-day category', max_length=20)),
                ('race_max90_category_num', models.PositiveSmallIntegerField(blank=True, help_text='Max 90-day category number', null=True)),
                ('race_finishes', models.PositiveIntegerField(default=0, help_text='Total race finishes')),
                ('race_dnfs', models.PositiveIntegerField(default=0, help_text='Total DNFs')),
                ('race_wins', models.PositiveIntegerField(default=0, help_text='Total wins')),
                ('race_podiums', models.PositiveIntegerField(default=0, help_text='Total podiums')),
                ('handicap_flat', models.DecimalField(blank=True, decimal_places=2, help_text='Flat profile handicap', max_digits=8, null=True)),
                ('handicap_rolling', models.DecimalField(blank=True, decimal_places=2, help_text='Rolling profile handicap', max_digits=8, null=True)),
                ('handicap_hilly', models.DecimalField(blank=True, decimal_places=2, help_text='Hilly profile handicap', max_digits=8, null=True)),
                ('handicap_mountainous', models.DecimalField(blank=True, decimal_places=2, help_text='Mountainous profile handicap', max_digits=8, null=True)),
                ('phenotype_value', models.CharField(blank=True, help_text='Phenotype classification', max_length=50)),
                ('phenotype_bias', models.DecimalField(blank=True, decimal_places=2, help_text='Phenotype bias', max_digits=6, null=True)),
                ('phenotype_sprinter', models.DecimalField(blank=True, decimal_places=1, help_text='Sprinter score', max_digits=5, null=True)),
                ('phenotype_puncheur', models.DecimalField(blank=True, decimal_places=1, help_text='Puncheur score', max_digits=5, null=True)),
                ('phenotype_pursuiter', models.DecimalField(blank=True, decimal_places=1, help_text='Pursuiter score', max_digits=5, null=True)),
                ('phenotype_climber', models.DecimalField(blank=True, decimal_places=1, help_text='Climber score', max_digits=5, null=True)),
                ('phenotype_tt', models.DecimalField(blank=True, decimal_places=1, help_text='Time trial score', max_digits=5, null=True)),
                ('club_id', models.PositiveIntegerField(blank=True, help_text='Club ID', null=True)),
                ('club_name', models.CharField(blank=True, help_text='Club name', max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='Record created date')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='Record last modified date')),
                ('date_left', models.DateTimeField(blank=True, help_text='Date rider left club', null=True)),
            ],
            options={
                'verbose_name': 'ZR Rider',
                'verbose_name_plural': 'ZR Riders',
                'ordering': ['name'],
            },
        ),
    ]
