# Generated by Django 6.0 on 2025-12-28 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zwiftracing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zrrider',
            old_name='rider_id',
            new_name='zwid',
        ),
    ]
