# Generated by Django 6.0 on 2025-12-28 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zwiftracing', '0002_rename_rider_id_to_zwid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zrrider',
            name='zwid',
            field=models.PositiveIntegerField(help_text='Zwift ID', unique=True),
        ),
    ]
