# Generated by Django 6.0.1 on 2026-01-30 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zwiftracing', '0002_historicalzrrider'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalzrrider',
            name='seed_climb',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Seed climb factor', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalzrrider',
            name='seed_endurance',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Seed endurance factor', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalzrrider',
            name='seed_punch',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Seed punch factor', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalzrrider',
            name='seed_pursuit',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Seed pursuit factor', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalzrrider',
            name='seed_race',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Seed race rating', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalzrrider',
            name='seed_sprint',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Seed sprint factor', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalzrrider',
            name='seed_time_trial',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Seed time trial rating', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalzrrider',
            name='seed_tt_factor',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Seed time trial factor', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalzrrider',
            name='velo_climb',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Velo climb factor', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalzrrider',
            name='velo_endurance',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Velo endurance factor', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalzrrider',
            name='velo_punch',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Velo punch factor', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalzrrider',
            name='velo_pursuit',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Velo pursuit factor', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalzrrider',
            name='velo_race',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Velo race rating', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalzrrider',
            name='velo_sprint',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Velo sprint factor', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalzrrider',
            name='velo_time_trial',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Velo time trial rating', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalzrrider',
            name='velo_tt_factor',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Velo time trial factor', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='zrrider',
            name='seed_climb',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Seed climb factor', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='zrrider',
            name='seed_endurance',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Seed endurance factor', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='zrrider',
            name='seed_punch',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Seed punch factor', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='zrrider',
            name='seed_pursuit',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Seed pursuit factor', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='zrrider',
            name='seed_race',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Seed race rating', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='zrrider',
            name='seed_sprint',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Seed sprint factor', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='zrrider',
            name='seed_time_trial',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Seed time trial rating', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='zrrider',
            name='seed_tt_factor',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Seed time trial factor', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='zrrider',
            name='velo_climb',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Velo climb factor', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='zrrider',
            name='velo_endurance',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Velo endurance factor', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='zrrider',
            name='velo_punch',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Velo punch factor', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='zrrider',
            name='velo_pursuit',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Velo pursuit factor', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='zrrider',
            name='velo_race',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Velo race rating', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='zrrider',
            name='velo_sprint',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Velo sprint factor', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='zrrider',
            name='velo_time_trial',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Velo time trial rating', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='zrrider',
            name='velo_tt_factor',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Velo time trial factor', max_digits=10, null=True),
        ),
    ]
