# Generated by Django 6.0 on 2026-01-04 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title for this data connection', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of this data connection')),
                ('spreadsheet_url', models.URLField(help_text='Google Sheets URL (e.g., https://docs.google.com/spreadsheets/d/.../edit)', max_length=500)),
                ('data_sheet', models.CharField(default='DATA_CONN', help_text='Name of the sheet tab where data will be sent', max_length=100, verbose_name='Sheet Name (tab)')),
                ('selected_fields', models.JSONField(blank=True, default=list, help_text='List of fields to include in export (User, ZwiftPower, ZwiftRacing fields)')),
                ('filters', models.JSONField(blank=True, default=dict, help_text='Filter criteria for data export')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='When this connection was created')),
                ('date_updated', models.DateTimeField(auto_now=True, help_text='When this connection was last updated')),
                ('date_last_synced', models.DateTimeField(blank=True, help_text='When data was last synced to the spreadsheet', null=True)),
                ('date_expires', models.DateTimeField(help_text='When this connection expires')),
                ('owner_email', models.EmailField(blank=True, help_text='Email of the Google Sheet owner', max_length=254)),
                ('created_by', models.ForeignKey(help_text='User who created this connection', on_delete=django.db.models.deletion.CASCADE, related_name='data_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Data Connection',
                'verbose_name_plural': 'Data Connections',
                'ordering': ['-date_created'],
            },
        ),
    ]
