# Generated by Django 6.0.1 on 2026-01-20 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_connection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataconnection',
            name='date_expires',
            field=models.DateField(help_text='When this connection expires'),
        ),
    ]
