# Generated by Django 6.0 on 2026-01-01 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_connection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataconnection',
            name='data_sheet',
            field=models.CharField(default='DATA_CONN', help_text='Name of the sheet tab where data will be sent', max_length=100, verbose_name='Sheet Name (tab)'),
        ),
    ]
