# Generated by Django 6.0.1 on 2026-01-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_connection', '0002_change_date_expires_to_datefield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataconnection',
            name='title',
            field=models.CharField(help_text='Title for this data connection', max_length=255, unique=True),
        ),
    ]
