# Generated by Django 6.0 on 2026-01-01 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_connection', '0002_change_data_sheet_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataconnection',
            name='owner_email',
            field=models.EmailField(blank=True, help_text='Email of the Google Sheet owner', max_length=254),
        ),
    ]
