# Generated by Django 6.0.1 on 2026-01-20 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_connection', '0003_title_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataconnection',
            name='is_broken',
            field=models.BooleanField(default=False, help_text='True if the linked spreadsheet no longer exists or is inaccessible'),
        ),
    ]
