# Generated by Django 6.0 on 2026-01-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_connection', '0003_add_owner_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataconnection',
            name='filters',
            field=models.JSONField(blank=True, default=dict, help_text='Filter criteria for data export'),
        ),
    ]
