# Generated by Django 6.0.3 on 2026-03-16 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_connection', '0004_add_is_broken_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataconnection',
            name='auto_sync',
            field=models.BooleanField(default=False, help_text='Enable automatic scheduled sync'),
        ),
    ]
