# Generated by Django 6.0.7 on 2026-07-20 22:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ZwiftDataset",
            fields=[
                ("id", models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ("source_url", models.URLField(help_text="Bundle URL it was fetched from")),
                ("synced_at", models.DateTimeField(blank=True, help_text="When the last sync completed", null=True)),
                (
                    "bundle_last_modified",
                    models.CharField(blank=True, help_text="Last-Modified/ETag reported by the source", max_length=100),
                ),
                ("bundle_bytes", models.PositiveBigIntegerField(default=0, help_text="Downloaded bundle size")),
                ("routes_count", models.PositiveIntegerField(default=0)),
                ("segments_count", models.PositiveIntegerField(default=0)),
                ("worlds_count", models.PositiveIntegerField(default=0)),
                ("profiles_count", models.PositiveIntegerField(default=0)),
                (
                    "last_error",
                    models.CharField(blank=True, help_text="Error from the last failed sync", max_length=500),
                ),
                ("syncing", models.BooleanField(default=False, help_text="A sync is currently in progress")),
            ],
            options={
                "verbose_name": "Zwift dataset",
                "verbose_name_plural": "Zwift dataset",
            },
        ),
        migrations.CreateModel(
            name="ZwiftWorld",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("world_id", models.PositiveIntegerField(help_text="Zwift numeric world id", unique=True)),
                ("name", models.CharField(help_text="World display name", max_length=100, unique=True)),
                ("route_count", models.PositiveIntegerField(default=0, help_text="Routes in this world (dataset)")),
                ("segment_count", models.PositiveIntegerField(default=0, help_text="Segments in this world (dataset)")),
            ],
            options={
                "verbose_name": "Zwift world",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ZwiftRoute",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="Route name", max_length=200)),
                ("world", models.CharField(help_text="Zwift world name", max_length=100)),
                ("world_id", models.PositiveIntegerField(help_text="Zwift numeric world id")),
                ("name_hash", models.CharField(help_text="Route id within its world (join key)", max_length=32)),
                (
                    "sport",
                    models.CharField(
                        choices=[("cycling", "Cycling"), ("running", "Running")], default="cycling", max_length=10
                    ),
                ),
                ("distance_km", models.FloatField(default=0.0, help_text="Route length, excludes lead-in")),
                ("ascent_m", models.PositiveIntegerField(default=0, help_text="Elevation gain, excludes lead-in")),
                ("avg_gradient_pct", models.FloatField(default=0.0, help_text="ascent / distance")),
                ("leadin_km", models.FloatField(default=0.0, help_text="Neutral roll-in distance before the route")),
                ("leadin_ascent_m", models.PositiveIntegerField(default=0, help_text="Lead-in elevation gain")),
                ("supports_tt", models.BooleanField(default=False, help_text="Can be ridden in time-trial mode")),
                ("event_only", models.BooleanField(default=False, help_text="Only available inside an event")),
                ("level_locked", models.PositiveIntegerField(default=0, help_text="Rider level required (0 = none)")),
            ],
            options={
                "verbose_name": "Zwift route",
                "ordering": ["world", "name"],
                "indexes": [models.Index(fields=["world", "name"], name="zwift_data__world_23fb59_idx")],
                "constraints": [
                    models.UniqueConstraint(fields=("world_id", "name_hash"), name="uniq_zwiftroute_world_hash")
                ],
            },
        ),
        migrations.CreateModel(
            name="ZwiftSegment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("segment_id", models.BigIntegerField(help_text="Signed 64-bit live-segment id", unique=True)),
                ("name", models.CharField(blank=True, help_text="Segment name (blank if unresolved)", max_length=200)),
                (
                    "segment_type",
                    models.CharField(
                        choices=[
                            ("sprint", "Sprint"),
                            ("kom", "KOM"),
                            ("climb", "Climb"),
                            ("lap", "Lap"),
                            ("segment", "Segment"),
                        ],
                        default="segment",
                        max_length=10,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        blank=True, choices=[("Forward", "Forward"), ("Reverse", "Reverse")], max_length=10
                    ),
                ),
                ("world", models.CharField(help_text="Zwift world name", max_length=100)),
                ("world_id", models.PositiveIntegerField(help_text="Zwift numeric world id")),
                ("course_id", models.PositiveIntegerField(default=0, help_text="Zwift course id")),
                ("road_id", models.IntegerField(default=0, help_text="Zwift road id")),
                ("length_m", models.PositiveIntegerField(default=0, help_text="Segment length in metres")),
                ("ascent_m", models.FloatField(default=0.0, help_text="Elevation gain in metres")),
                ("avg_grade_pct", models.FloatField(default=0.0, help_text="Average grade %")),
                ("max_grade_pct", models.FloatField(default=0.0, help_text="Maximum grade %")),
                ("gives_powerup", models.BooleanField(default=False, help_text="Crossing awards a power-up")),
                ("route_count", models.PositiveIntegerField(default=0, help_text="Distinct routes that cross it")),
            ],
            options={
                "verbose_name": "Zwift segment",
                "ordering": ["world", "name"],
                "indexes": [models.Index(fields=["world", "segment_type"], name="zwift_data__world_fb7007_idx")],
            },
        ),
    ]
