# Generated by Django 6.0.7 on 2026-07-21 20:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zwift_data", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="zwiftroute",
            name="recommended_laps",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="Club Ladder recommended number of laps (curated)", null=True
            ),
        ),
        migrations.AddField(
            model_name="zwiftroute",
            name="supports_laps",
            field=models.BooleanField(default=False, help_text="Route can be ridden as multiple laps (curated)"),
        ),
        migrations.AddField(
            model_name="zwiftroute",
            name="velo_climb",
            field=models.DecimalField(
                blank=True, decimal_places=2, help_text="vELO2 Race weight: Climb (%)", max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="zwiftroute",
            name="velo_endurance",
            field=models.DecimalField(
                blank=True, decimal_places=2, help_text="vELO2 Race weight: Endurance (%)", max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="zwiftroute",
            name="velo_num_events",
            field=models.PositiveIntegerField(
                blank=True, help_text="ZwiftRacing sample size the vELO2 weights are derived from", null=True
            ),
        ),
        migrations.AddField(
            model_name="zwiftroute",
            name="velo_punch",
            field=models.DecimalField(
                blank=True, decimal_places=2, help_text="vELO2 Race weight: Punch (%)", max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="zwiftroute",
            name="velo_pursuit",
            field=models.DecimalField(
                blank=True, decimal_places=2, help_text="vELO2 Race weight: Pursuit (%)", max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="zwiftroute",
            name="velo_sprint",
            field=models.DecimalField(
                blank=True, decimal_places=2, help_text="vELO2 Race weight: Sprint (%)", max_digits=5, null=True
            ),
        ),
    ]
