# Generated by Django 6.0.6 on 2026-06-17 13:51

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LadderMatchup",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, help_text="Matchup name", max_length=200)),
                (
                    "our_team_name",
                    models.CharField(blank=True, help_text="Our team name shown on the matchup", max_length=200),
                ),
                ("opponent_team_name", models.CharField(blank=True, help_text="Opponent team name", max_length=200)),
                (
                    "course_name",
                    models.CharField(blank=True, help_text="Course / route name (free text)", max_length=200),
                ),
                (
                    "course_profile",
                    models.CharField(
                        choices=[
                            ("flat", "Flat"),
                            ("rolling", "Rolling"),
                            ("hilly", "Hilly"),
                            ("mountainous", "Mountainous"),
                        ],
                        default="rolling",
                        help_text="Terrain profile; selects which ZR handicap drives the projected score",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created the matchup",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ladder_matchups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ladder Matchup",
                "verbose_name_plural": "Ladder Matchups",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="LadderRider",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "side",
                    models.CharField(
                        choices=[("ours", "Our team"), ("opponent", "Opponent")],
                        help_text="Which team the rider races for",
                        max_length=10,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, help_text="Display order within the side")),
                ("zwid", models.PositiveIntegerField(help_text="Zwift ID")),
                ("name", models.CharField(help_text="Rider display name", max_length=255)),
                (
                    "zr_data",
                    models.JSONField(default=dict, help_text="Normalized ZR snapshot used by the comparison views"),
                ),
                (
                    "is_racing",
                    models.BooleanField(default=True, help_text="Include this rider in comparisons and scoring"),
                ),
                (
                    "fetched_at",
                    models.DateTimeField(blank=True, help_text="When the ZR snapshot was last fetched", null=True),
                ),
                (
                    "matchup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="riders",
                        to="ladder_planner.laddermatchup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ladder Rider",
                "verbose_name_plural": "Ladder Riders",
                "ordering": ["side", "order", "id"],
                "constraints": [
                    models.UniqueConstraint(fields=("matchup", "side", "zwid"), name="unique_rider_per_side")
                ],
            },
        ),
    ]
