# Generated by Django 6.0.6 on 2026-06-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ladder_planner", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CachedClub",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("club_id", models.PositiveIntegerField(help_text="Club ID", unique=True)),
                ("name", models.CharField(blank=True, help_text="Club name", max_length=255)),
                ("rider_count", models.PositiveIntegerField(default=0, help_text="Riders cached at last refresh")),
                (
                    "last_refreshed_at",
                    models.DateTimeField(blank=True, help_text="When the club was last refreshed", null=True),
                ),
                (
                    "auto_refresh",
                    models.BooleanField(default=True, help_text="Include in the periodic background refresh"),
                ),
                (
                    "last_error",
                    models.CharField(blank=True, help_text="Error from the last refresh, if any", max_length=300),
                ),
            ],
            options={
                "verbose_name": "Cached Club",
                "verbose_name_plural": "Cached Clubs",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CachedRider",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("zwid", models.PositiveIntegerField(help_text="Zwift ID", unique=True)),
                ("name", models.CharField(db_index=True, help_text="Rider display name", max_length=255)),
                ("club_id", models.PositiveIntegerField(blank=True, db_index=True, help_text="Club ID", null=True)),
                ("club_name", models.CharField(blank=True, help_text="Club name", max_length=255)),
                (
                    "zr_data",
                    models.JSONField(default=dict, help_text="Normalized ZR snapshot (see services.normalize)"),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("rider", "Rider fetch"), ("club", "Club refresh")],
                        default="rider",
                        help_text="Snapshot origin",
                        max_length=10,
                    ),
                ),
                ("fetched_at", models.DateTimeField(help_text="When this snapshot was fetched from ZR")),
            ],
            options={
                "verbose_name": "Cached Rider",
                "verbose_name_plural": "Cached Riders",
                "ordering": ["name"],
            },
        ),
    ]
