# Generated by Django 6.0.6 on 2026-06-17 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ladder_planner", "0002_cachedclub_cachedrider"),
        ("ttt_planner", "0010_tttplan_target_if"),
    ]

    operations = [
        migrations.AddField(
            model_name="laddermatchup",
            name="route",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional route picked from the shared route library (prefills name + profile)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="ttt_planner.route",
            ),
        ),
    ]
