# Generated by Django 6.0.6 on 2026-06-22 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladder_planner', '0003_laddermatchup_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='laddermatchup',
            name='cda_coef',
            field=models.FloatField(blank=True, help_text='Per-matchup aero CdA coefficient for the Climb compare tab. Blank uses the global TTT_CDA_COEF.', null=True),
        ),
    ]
