# Generated by Django 6.0.7 on 2026-07-23 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0055_availabilitygrid_require_race_verified_availability'),
        ('ladder_planner', '0005_repoint_route_to_zwiftroute'),
    ]

    operations = [
        migrations.AddField(
            model_name='laddermatchup',
            name='edit_squad',
            field=models.ForeignKey(blank=True, help_text='Optional squad whose members (incl. captains/vice-captains) may also edit this matchup', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='events.squad'),
        ),
    ]
