# Generated by Django 6.0.1 on 2026-01-14 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_logo', models.ImageField(blank=True, help_text='Site logo displayed in the header (recommended: 200x50 PNG with transparency)', null=True, upload_to='site/')),
                ('hero_image', models.ImageField(blank=True, help_text='Hero image for the home page (recommended: 1920x600)', null=True, upload_to='site/')),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
