# Generated by Django 6.0.1 on 2026-01-14 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gotta_bike_platform', '0001_site_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Favicon for browser tabs (recommended: 32x32 or 64x64 PNG)', null=True, upload_to='site/'),
        ),
    ]
