# Generated by Django 6.0.2 on 2026-02-23 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gotta_bike_platform', '0002_add_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='extra_verified_emoji',
            field=models.ImageField(blank=True, help_text='Emoji/icon shown for extra-verified status (recommended: 64x64 PNG)', null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='not_verified_emoji',
            field=models.ImageField(blank=True, help_text='Emoji/icon shown for not-verified status (recommended: 64x64 PNG)', null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='verified_emoji',
            field=models.ImageField(blank=True, help_text='Emoji/icon shown for verified status (recommended: 64x64 PNG)', null=True, upload_to='site/'),
        ),
    ]
