# Generated by Django 6.0.2 on 2026-02-28 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gotta_bike_platform', '0003_add_verification_emojis'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='zp_a_emoji',
            field=models.ImageField(blank=True, help_text='Emoji/icon for ZwiftPower A category (recommended: 64x64 PNG)', null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='zp_b_emoji',
            field=models.ImageField(blank=True, help_text='Emoji/icon for ZwiftPower B category (recommended: 64x64 PNG)', null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='zp_c_emoji',
            field=models.ImageField(blank=True, help_text='Emoji/icon for ZwiftPower C category (recommended: 64x64 PNG)', null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='zp_d_emoji',
            field=models.ImageField(blank=True, help_text='Emoji/icon for ZwiftPower D category (recommended: 64x64 PNG)', null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='zp_e_emoji',
            field=models.ImageField(blank=True, help_text='Emoji/icon for ZwiftPower E category (recommended: 64x64 PNG)', null=True, upload_to='site/'),
        ),
    ]
