# Generated by Django 6.0.2 on 2026-02-28 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gotta_bike_platform', '0004_add_zp_category_emojis'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='zr_amethyst_emoji',
            field=models.ImageField(blank=True, help_text='Emoji/icon for Zwift Racing Amethyst category (recommended: 64x64 PNG)', null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='zr_bronze_emoji',
            field=models.ImageField(blank=True, help_text='Emoji/icon for Zwift Racing Bronze category (recommended: 64x64 PNG)', null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='zr_copper_emoji',
            field=models.ImageField(blank=True, help_text='Emoji/icon for Zwift Racing Copper category (recommended: 64x64 PNG)', null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='zr_diamond_emoji',
            field=models.ImageField(blank=True, help_text='Emoji/icon for Zwift Racing Diamond category (recommended: 64x64 PNG)', null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='zr_emerald_emoji',
            field=models.ImageField(blank=True, help_text='Emoji/icon for Zwift Racing Emerald category (recommended: 64x64 PNG)', null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='zr_gold_emoji',
            field=models.ImageField(blank=True, help_text='Emoji/icon for Zwift Racing Gold category (recommended: 64x64 PNG)', null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='zr_platinum_emoji',
            field=models.ImageField(blank=True, help_text='Emoji/icon for Zwift Racing Platinum category (recommended: 64x64 PNG)', null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='zr_ruby_emoji',
            field=models.ImageField(blank=True, help_text='Emoji/icon for Zwift Racing Ruby category (recommended: 64x64 PNG)', null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='zr_sapphire_emoji',
            field=models.ImageField(blank=True, help_text='Emoji/icon for Zwift Racing Sapphire category (recommended: 64x64 PNG)', null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='zr_silver_emoji',
            field=models.ImageField(blank=True, help_text='Emoji/icon for Zwift Racing Silver category (recommended: 64x64 PNG)', null=True, upload_to='site/'),
        ),
    ]
