# Generated by Django 6.0.2 on 2026-03-01 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gotta_bike_platform', '0005_add_zr_category_emojis'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='zp_a_plus_emoji',
            field=models.ImageField(blank=True, help_text='Emoji/icon for ZwiftPower A+ category (recommended: 64x64 PNG)', null=True, upload_to='site/'),
        ),
    ]
