# Generated by Django 6.0.3 on 2026-03-04 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gotta_bike_platform', '0006_add_zp_a_plus_emoji'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='phenotype_allrounder_emoji',
            field=models.ImageField(blank=True, help_text='Emoji/icon for All-Rounder phenotype (recommended: 64x64 PNG)', null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='phenotype_climber_emoji',
            field=models.ImageField(blank=True, help_text='Emoji/icon for Climber phenotype (recommended: 64x64 PNG)', null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='phenotype_puncheur_emoji',
            field=models.ImageField(blank=True, help_text='Emoji/icon for Puncheur phenotype (recommended: 64x64 PNG)', null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='phenotype_sprinter_emoji',
            field=models.ImageField(blank=True, help_text='Emoji/icon for Sprinter phenotype (recommended: 64x64 PNG)', null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='phenotype_tt_emoji',
            field=models.ImageField(blank=True, help_text='Emoji/icon for Time Trialist phenotype (recommended: 64x64 PNG)', null=True, upload_to='site/'),
        ),
    ]
