# Generated by Django 6.0.3 on 2026-03-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gotta_bike_platform', '0007_sitesettings_phenotype_allrounder_emoji_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='phenotype_pursuiter_emoji',
            field=models.ImageField(blank=True, help_text='Emoji/icon for Pursuiter phenotype (recommended: 64x64 PNG)', null=True, upload_to='site/'),
        ),
    ]
