# Generated by Django 6.0.3 on 2026-03-15 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gotta_bike_platform', '0008_sitesettings_phenotype_pursuiter_emoji'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='new_member_icon',
            field=models.ImageField(blank=True, help_text='Icon for New Member status (recommended: 64x64 PNG)', null=True, upload_to='site/'),
        ),
    ]
