# Generated by Django 6.1 on 2026-09-13 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gotta_bike_platform', '0009_sitesettings_new_member_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='age_50plus_emoji',
            field=models.ImageField(blank=True, help_text='Icon for the 50+ age bracket. Leave empty to use the bundled default', null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='age_60plus_emoji',
            field=models.ImageField(blank=True, help_text='Icon for the 60+ age bracket. Leave empty to use the bundled default', null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='age_70plus_emoji',
            field=models.ImageField(blank=True, help_text='Icon for the 70+ age bracket. Leave empty to use the bundled default', null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='age_jnr_emoji',
            field=models.ImageField(blank=True, help_text='Icon for the Jnr age bracket. Leave empty to use the bundled default', null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='age_mas_emoji',
            field=models.ImageField(blank=True, help_text='Icon for the Mas age bracket. Leave empty to use the bundled default', null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='age_snr_emoji',
            field=models.ImageField(blank=True, help_text='Icon for the Snr age bracket. Leave empty to use the bundled default', null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='age_u23_emoji',
            field=models.ImageField(blank=True, help_text='Icon for the U23 age bracket. Leave empty to use the bundled default', null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='age_vet_emoji',
            field=models.ImageField(blank=True, help_text='Icon for the Vet age bracket. Leave empty to use the bundled default', null=True, upload_to='site/'),
        ),
    ]
