# Generated by Django 6.1 on 2026-09-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gotta_bike_platform', '0010_sitesettings_age_50plus_emoji_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='kit_emoji',
            field=models.ImageField(blank=True, help_text='Icon for a rider who has the team kit. Leave empty to use the bundled default', null=True, upload_to='site/'),
        ),
    ]
