# Generated by Django 6.0.5 on 2026-05-07 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='User-chosen label for the key', max_length=80)),
                ('key_hash', models.CharField(db_index=True, help_text='SHA-256 hex digest of the raw key', max_length=64, unique=True)),
                ('prefix', models.CharField(help_text='Display-only prefix of the raw key', max_length=8)),
                ('last4', models.CharField(help_text='Display-only last 4 chars of the raw key', max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='Set to created_at + 30 days at issuance')),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(help_text='Owner of the API key', on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User API Key',
                'verbose_name_plural': 'User API Keys',
                'ordering': ['-created_at'],
            },
        ),
    ]
