# Generated by Django 6.0.5 on 2026-05-12 12:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short summary of the issue', max_length=200)),
                ('details', models.TextField(help_text='Full description (supports Markdown)')),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('closed', 'Closed')], default='new', help_text='Workflow state', max_length=20)),
                ('category', models.CharField(choices=[('support', 'Member Support'), ('verification', 'Verification'), ('equipment', 'Equipment'), ('discord', 'Discord'), ('event', 'Event'), ('squad', 'Squad'), ('other', 'Other')], default='support', help_text='Coarse topic for the ticket queue filter', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', help_text='Triage priority', max_length=20)),
                ('resolution', models.TextField(blank=True, help_text='Closing note shown on resolved tickets')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the ticket was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the ticket was last modified')),
                ('closed_at', models.DateTimeField(blank=True, help_text='When the ticket was closed', null=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='User currently handling the ticket', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('closed_by', models.ForeignKey(blank=True, help_text='User who closed the ticket', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_tickets', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(help_text='User who raised the ticket', on_delete=django.db.models.deletion.CASCADE, related_name='submitted_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='tickets_tic_status_15eec8_idx'), models.Index(fields=['assigned_to', 'status'], name='tickets_tic_assigne_e36302_idx')],
            },
        ),
    ]
