# Generated by Django 6.0.5 on 2026-05-12 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_add_has_jersey'),
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='guild_member',
            field=models.ForeignKey(blank=True, help_text='Discord guild member this ticket is about, for system-generated membership tickets', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_tickets', to='accounts.guildmember'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('support', 'Member Support'), ('membership', 'Membership'), ('verification', 'Verification'), ('equipment', 'Equipment'), ('discord', 'Discord'), ('event', 'Event'), ('squad', 'Squad'), ('other', 'Other')], default='support', help_text='Coarse topic for the ticket queue filter', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='submitted_by',
            field=models.ForeignKey(blank=True, help_text='User who raised the ticket (null for system-generated tickets)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_tickets', to=settings.AUTH_USER_MODEL),
        ),
    ]
