# Generated by Django 6.1 on 2026-09-01 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RiderProfile',
            fields=[
                ('zwid', models.BigIntegerField(help_text='Zwift ID (the join key everywhere)', primary_key=True, serialize=False)),
                ('zwift_user_id', models.CharField(blank=True, db_index=True, help_text='Zwift account UUID; only riders connected through zauth have one', max_length=64)),
                ('name', models.CharField(blank=True, db_index=True, max_length=200)),
                ('gender', models.CharField(blank=True, help_text='Filtered in the roster and the Sheets export', max_length=16)),
                ('country', models.CharField(blank=True, max_length=64)),
                ('age', models.CharField(blank=True, help_text='A bracket string upstream, not a number', max_length=16)),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('height_cm', models.FloatField(blank=True, null=True)),
                ('ftp', models.FloatField(blank=True, null=True)),
                ('zftp', models.FloatField(blank=True, null=True)),
                ('category_open', models.CharField(blank=True, max_length=16)),
                ('category_women', models.CharField(blank=True, max_length=16)),
                ('category_racing', models.CharField(blank=True, max_length=16)),
                ('velo', models.FloatField(blank=True, help_text='Overall racing rating', null=True)),
                ('zwift_racing_score', models.FloatField(blank=True, null=True)),
                ('zp_skill', models.FloatField(blank=True, null=True)),
                ('compound_score', models.FloatField(blank=True, null=True)),
                ('phenotype_value', models.CharField(blank=True, max_length=32)),
                ('club_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('club_name', models.CharField(blank=True, max_length=200)),
                ('payload', models.JSONField(default=dict, help_text='The full ProfileFull document: power curves, handicaps, seed, phenotype scores, known clubs')),
                ('fetched_at', models.DateTimeField(db_index=True, help_text='When we last called zauth for this rider')),
                ('sources', models.JSONField(default=dict, help_text='Per-source {present, fetched_at} as returned')),
                ('has_account', models.JSONField(default=dict, help_text="Per-source booleans. False means no record stored, which is usually 'no account' but for a never-fetched source also means 'not looked up yet' -- read it with sources.*.fetched_at")),
                ('last_race_at', models.DateTimeField(blank=True, db_index=True, help_text='Most recent known race, from the clubs block; the retention anchor', null=True)),
            ],
            options={
                'verbose_name': 'Rider Profile',
                'verbose_name_plural': 'Rider Profiles',
                'ordering': ('name',),
            },
        ),
    ]
