# Generated by Django 6.0 on 2025-12-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_id', models.CharField(help_text='Discord user ID who triggered the API call', max_length=20)),
                ('discord_guild_id', models.CharField(help_text='Discord guild/server ID', max_length=20)),
                ('api', models.CharField(help_text='API endpoint path', max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the API call was made')),
            ],
            options={
                'verbose_name': 'Bot Stats',
                'verbose_name_plural': 'Bot Stats',
            },
        ),
    ]
