# Generated by Django 6.0 on 2026-01-04 00:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_id', models.CharField(help_text='Discord role ID (snowflake)', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Role name', max_length=100)),
                ('color', models.IntegerField(default=0, help_text='Role color as integer')),
                ('position', models.IntegerField(default=0, help_text='Role position in hierarchy (higher = more authority)')),
                ('managed', models.BooleanField(default=False, help_text='Whether this role is managed by an integration/bot')),
                ('mentionable', models.BooleanField(default=False, help_text='Whether this role can be mentioned')),
                ('date_synced', models.DateTimeField(auto_now=True, help_text='When this role was last synced from Discord')),
            ],
            options={
                'verbose_name': 'Discord Role',
                'verbose_name_plural': 'Discord Roles',
                'ordering': ['-position'],
            },
        ),
        migrations.CreateModel(
            name='TeamLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the link', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the link')),
                ('url', models.URLField(help_text='URL to the resource', max_length=500)),
                ('link_types', models.JSONField(blank=True, default=list, help_text="Types/tags for this link (e.g., ['form', 'signup', 'zrl'])")),
                ('active', models.BooleanField(default=True, help_text='Whether this link is active')),
                ('date_open', models.DateTimeField(blank=True, help_text='When this link becomes visible (blank = immediately)', null=True)),
                ('date_closed', models.DateTimeField(blank=True, help_text='When this link stops being visible (blank = never)', null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, help_text='When this link was added')),
                ('date_edited', models.DateTimeField(auto_now=True, help_text='When this link was last edited')),
            ],
            options={
                'verbose_name': 'Team Link',
                'verbose_name_plural': 'Team Links',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='RaceReadyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verify_type', models.CharField(choices=[('weight_full', 'Weight Full'), ('weight_light', 'Weight Light'), ('height', 'Height'), ('power', 'Power')], help_text='Type of verification', max_length=15)),
                ('media_type', models.CharField(choices=[('video', 'Video'), ('photo', 'Photo'), ('link', 'Link'), ('other', 'Other')], help_text='Type of media', max_length=10)),
                ('media_file', models.FileField(blank=True, help_text='Uploaded photo or video file', null=True, upload_to='race_ready/%Y/%m/')),
                ('url', models.URLField(blank=True, help_text='URL to external evidence (e.g., YouTube video, image link)', max_length=500)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg (for weight verification)', max_digits=5, null=True)),
                ('height', models.PositiveIntegerField(blank=True, help_text='Height in cm (for height verification)', null=True)),
                ('ftp', models.PositiveIntegerField(blank=True, help_text='Functional Threshold Power in watts (for power verification)', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', help_text='Verification status', max_length=10)),
                ('reviewed_date', models.DateTimeField(blank=True, help_text='When this record was reviewed', null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection (if rejected)')),
                ('notes', models.TextField(blank=True, help_text='Notes about the measurement')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, help_text='When this record was created')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='User who reviewed this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_records', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='race_ready_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Race Ready Record',
                'verbose_name_plural': 'Race Ready Records',
                'ordering': ['-date_created'],
            },
        ),
    ]
