# Generated by Django 6.0 on 2025-12-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RaceReadyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verify_type', models.CharField(choices=[('weight', 'Weight'), ('height', 'Height'), ('power', 'Power')], help_text='Type of verification', max_length=10)),
                ('media_type', models.CharField(choices=[('video', 'Video'), ('pictures', 'Pictures'), ('live', 'Live'), ('other', 'Other')], help_text='Type of media', max_length=10)),
                ('notes', models.TextField(blank=True, help_text='Notes about the measurement')),
            ],
            options={
                'verbose_name': 'Race Ready Record',
                'verbose_name_plural': 'Race Ready Records',
            },
        ),
        migrations.CreateModel(
            name='TeamConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(default='My Team Name', help_text='Name of the team', max_length=255)),
                ('guild_name', models.CharField(default='My Guild Name', help_text='Name of the guild', max_length=255)),
                ('guild_id', models.IntegerField(help_text='Discord id of the guild')),
                ('race_ready_role', models.IntegerField(help_text='Discord id of the race ready role')),
            ],
            options={
                'verbose_name': 'Team Configuration',
                'verbose_name_plural': 'Team Configurations',
            },
        ),
    ]
