# Generated by Django 6.0 on 2026-01-06 17:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RosterFilter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID for URL-safe access', primary_key=True, serialize=False)),
                ('discord_ids', models.JSONField(default=list, help_text='List of Discord user IDs to filter roster by')),
                ('channel_name', models.CharField(blank=True, help_text='Name of the Discord channel', max_length=100)),
                ('created_by_discord_id', models.CharField(blank=True, help_text='Discord ID of user who created this filter', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this filter was created')),
                ('expires_at', models.DateTimeField(help_text='When this filter expires')),
            ],
            options={
                'verbose_name': 'Roster Filter',
                'verbose_name_plural': 'Roster Filters',
                'ordering': ['-created_at'],
            },
        ),
    ]
