# Generated by Django 6.0 on 2025-12-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamconfig',
            name='member_role',
            field=models.IntegerField(default=0, help_text='Discord id of the member role'),
        ),
    ]
