# Generated by Django 6.0 on 2025-12-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_teamconfig_member_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamconfig',
            name='membership_admin_role',
            field=models.IntegerField(default=0, help_text='Discord id of the membership admin role'),
        ),
        migrations.AddField(
            model_name='teamconfig',
            name='team_captain_role',
            field=models.IntegerField(default=0, help_text='Discord id of the team captain role'),
        ),
    ]
