# Generated by Django 6.0 on 2026-01-07 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_add_roster_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='racereadyrecord',
            name='same_gender',
            field=models.BooleanField(default=False, help_text='Same gender as user should review record'),
        ),
    ]
