# Generated by Django 6.0 on 2025-12-28 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_teamconfig_membership_admin_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamconfig',
            name='height_verification',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='teamconfig',
            name='power_verification',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='teamconfig',
            name='weight_verification',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
