# Generated by Django 6.0.1 on 2026-01-16 18:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_add_same_gender_to_racereadyrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID for secure URL access', primary_key=True, serialize=False)),
                ('discord_id', models.CharField(db_index=True, help_text='Discord user ID', max_length=20, unique=True)),
                ('discord_username', models.CharField(help_text='Discord username at time of application', max_length=100)),
                ('server_nickname', models.CharField(blank=True, help_text='Server nickname at time of application', max_length=100)),
                ('avatar_url', models.URLField(blank=True, help_text='Discord avatar URL', max_length=500)),
                ('guild_avatar_url', models.URLField(blank=True, help_text='Server-specific avatar URL', max_length=500)),
                ('discord_user_data', models.JSONField(blank=True, default=dict, help_text='Raw discord.User data')),
                ('discord_member_data', models.JSONField(blank=True, default=dict, help_text='Raw discord.Member data')),
                ('modal_form_data', models.JSONField(blank=True, default=dict, help_text='Data from join_the_coalition modal')),
                ('first_name', models.CharField(blank=True, help_text="Applicant's first name", max_length=100)),
                ('last_name', models.CharField(blank=True, help_text="Applicant's last name", max_length=100)),
                ('agree_privacy', models.BooleanField(default=False, help_text='Whether applicant agreed to privacy policy')),
                ('agree_tos', models.BooleanField(default=False, help_text='Whether applicant agreed to terms of service')),
                ('applicant_notes', models.TextField(blank=True, help_text='Notes from the applicant')),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes from membership admins')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('in_progress', 'In Progress'), ('waiting_response', 'Waiting for User Response'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', help_text='Application status', max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='When application was created')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='When application was last modified')),
                ('modified_by', models.ForeignKey(blank=True, help_text='Admin who last modified this application', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membership Application',
                'verbose_name_plural': 'Membership Applications',
                'ordering': ['-date_created'],
            },
        ),
    ]
