# Generated by Django 6.0.1 on 2026-01-16 19:16

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_membership_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipapplication',
            name='birth_year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Year of birth', null=True),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='country',
            field=django_countries.fields.CountryField(blank=True, help_text='Country of residence', max_length=2),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='dual_recording',
            field=models.CharField(blank=True, choices=[('none', 'No dual recording'), ('trainer', 'Trainer as primary'), ('powermeter', 'Power meter as primary')], help_text='Dual recording preference', max_length=20),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], help_text='Gender', max_length=10),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='power_meter',
            field=models.CharField(blank=True, help_text='Power meter (from POWERMETER_OPTIONS)', max_length=100),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='strava_profile',
            field=models.URLField(blank=True, help_text='Strava profile URL'),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='timezone',
            field=models.CharField(blank=True, help_text="User's timezone (e.g., America/New_York)", max_length=50),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='trainer',
            field=models.CharField(blank=True, help_text='Primary trainer (from TRAINER_OPTIONS)', max_length=100),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='unit_preference',
            field=models.CharField(blank=True, choices=[('metric', 'Metric (kg, cm)'), ('imperial', 'Imperial (lbs, in)')], help_text='Preferred units for weight and height', max_length=10),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='zwift_id',
            field=models.CharField(blank=True, help_text='Zwift account ID', max_length=20),
        ),
    ]
