# Generated by Django 6.0 on 2025-12-29 00:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_add_user_and_date_to_race_ready_record'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='racereadyrecord',
            name='verified',
            field=models.BooleanField(default=False, help_text='Whether this record is verified'),
        ),
        migrations.AddField(
            model_name='racereadyrecord',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='User who verified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='racereadyrecord',
            name='verified_date',
            field=models.DateTimeField(blank=True, help_text='When this record was verified', null=True),
        ),
        migrations.AlterField(
            model_name='racereadyrecord',
            name='media_type',
            field=models.CharField(choices=[('video', 'Video'), ('photo', 'Photo'), ('link', 'Link'), ('other', 'Other')], help_text='Type of media', max_length=10),
        ),
    ]
