# Generated by Django 6.0.1 on 2026-01-17 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_add_membership_application_profile_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipapplication',
            name='heartrate_monitor',
            field=models.CharField(blank=True, help_text='Heart rate monitor brand (from HEARTRATE_MONITOR_OPTIONS)', max_length=100),
        ),
    ]
