# Generated by Django 6.0.1 on 2026-01-19 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_membershipapplication_heartrate_monitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipapplication',
            name='zwift_verified',
            field=models.BooleanField(default=False, help_text='Whether Zwift account has been verified via login'),
        ),
    ]
