# Generated by Django 6.0 on 2025-12-29 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_add_verified_by_and_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='racereadyrecord',
            name='media_file',
            field=models.FileField(blank=True, help_text='Uploaded photo or video file', null=True, upload_to='race_ready/%Y/%m/'),
        ),
    ]
