# Generated by Django 6.0 on 2025-12-29 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0007_add_media_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racereadyrecord',
            name='verify_type',
            field=models.CharField(choices=[('weight_full', 'Weight Full'), ('weight', 'Weight'), ('height', 'Height'), ('power', 'Power')], help_text='Type of verification', max_length=15),
        ),
    ]
