# Generated by Django 6.0.1 on 2026-01-19 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0007_membershipapplication_zwift_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipapplication',
            name='email',
            field=models.EmailField(blank=True, help_text='Contact email address', max_length=254),
        ),
    ]
