# Generated by Django 6.0.1 on 2026-01-22 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0008_membershipapplication_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipapplication',
            name='messages',
            field=models.JSONField(blank=True, default=list, help_text='Messages from admins to applicant'),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('in_progress', 'In Progress'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', help_text='Application status', max_length=20),
        ),
    ]
