# Generated by Django 6.0 on 2025-12-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0008_increase_verify_type_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the link', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the link')),
                ('url', models.URLField(help_text='URL to the resource', max_length=500)),
                ('link_type', models.CharField(choices=[('form', 'Form'), ('spreadsheet', 'Spreadsheet'), ('website', 'Website'), ('zrl', 'ZRL'), ('frr', 'FRR'), ('zwiftpower', 'ZwiftPower'), ('zwiftracing', 'Zwift Racing'), ('other', 'Other')], default='other', help_text='Type of link', max_length=20)),
                ('active', models.BooleanField(default=True, help_text='Whether this link is active')),
                ('date_added', models.DateTimeField(auto_now_add=True, help_text='When this link was added')),
                ('date_edited', models.DateTimeField(auto_now=True, help_text='When this link was last edited')),
            ],
            options={
                'verbose_name': 'Form Link',
                'verbose_name_plural': 'Form Links',
                'ordering': ['title'],
            },
        ),
    ]
