# Generated by Django 6.0 on 2025-12-29 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0010_rename_formlink_to_teamlink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamlink',
            options={'ordering': ['title'], 'verbose_name': 'Team Link', 'verbose_name_plural': 'Team Links'},
        ),
        migrations.RemoveField(
            model_name='teamlink',
            name='link_type',
        ),
        migrations.AddField(
            model_name='teamlink',
            name='link_types',
            field=models.JSONField(blank=True, default=list, help_text="Types/tags for this link (e.g., ['form', 'signup', 'zrl'])"),
        ),
    ]
