# Generated by Django 6.0.1 on 2026-01-28 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0010_membershipapplication_tpv_profile_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamlink',
            name='permissions',
            field=models.JSONField(blank=True, default=list, help_text='Permission mappings required to view this link (empty = all team members)'),
        ),
    ]
