# Generated by Django 6.0 on 2025-12-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0011_change_link_type_to_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamlink',
            name='date_closed',
            field=models.DateTimeField(blank=True, help_text='When this link stops being visible (blank = never)', null=True),
        ),
        migrations.AddField(
            model_name='teamlink',
            name='date_open',
            field=models.DateTimeField(blank=True, help_text='When this link becomes visible (blank = immediately)', null=True),
        ),
    ]
