# Generated by Django 6.0.2 on 2026-02-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0011_add_permissions_to_teamlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='racereadyrecord',
            name='record_date',
            field=models.DateField(blank=True, help_text='Date of the verification evidence (video/photo/link)', null=True),
        ),
    ]
