# Generated by Django 6.0.2 on 2026-02-05 17:48

from datetime import date

from django.db import migrations


def backfill_record_date(apps, schema_editor):
    """Set record_date to 2026-01-01 for all existing records with null record_date."""
    RaceReadyRecord = apps.get_model("team", "RaceReadyRecord")
    default_date = date(2026, 1, 1)
    updated = RaceReadyRecord.objects.filter(record_date__isnull=True).update(record_date=default_date)
    if updated:
        print(f"  Backfilled {updated} RaceReadyRecord(s) with record_date={default_date}")


def reverse_backfill(apps, schema_editor):
    """Reverse: set record_date back to null for records with the default date."""
    RaceReadyRecord = apps.get_model("team", "RaceReadyRecord")
    default_date = date(2026, 1, 1)
    RaceReadyRecord.objects.filter(record_date=default_date).update(record_date=None)


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0012_add_record_date_to_racereadyrecord'),
    ]

    operations = [
        migrations.RunPython(backfill_record_date, reverse_backfill),
    ]
