# Generated by Django 6.0 on 2025-12-30 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0012_add_teamlink_visibility_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='racereadyrecord',
            name='url',
            field=models.URLField(blank=True, help_text='URL to external evidence (e.g., YouTube video, image link)', max_length=500),
        ),
        migrations.AlterField(
            model_name='racereadyrecord',
            name='verify_type',
            field=models.CharField(choices=[('weight_full', 'Weight Full'), ('weight_light', 'Weight Light'), ('height', 'Height'), ('power', 'Power')], help_text='Type of verification', max_length=15),
        ),
    ]
