# Generated by Django 6.0 on 2025-12-30 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0013_add_url_to_racereadyrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='racereadyrecord',
            name='verified',
        ),
        migrations.RemoveField(
            model_name='racereadyrecord',
            name='verified_by',
        ),
        migrations.RemoveField(
            model_name='racereadyrecord',
            name='verified_date',
        ),
        migrations.AddField(
            model_name='racereadyrecord',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection (if rejected)'),
        ),
        migrations.AddField(
            model_name='racereadyrecord',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='User who reviewed this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='racereadyrecord',
            name='reviewed_date',
            field=models.DateTimeField(blank=True, help_text='When this record was reviewed', null=True),
        ),
        migrations.AddField(
            model_name='racereadyrecord',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', help_text='Verification status', max_length=10),
        ),
    ]
