# Generated by Django 6.0 on 2025-12-30 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0014_change_verified_to_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamConfig',
        ),
    ]
