# Generated by Django 6.0.2 on 2026-02-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0014_alter_membershipapplication_dual_recording'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(help_text='Discord channel ID (snowflake)', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Channel name', max_length=100)),
                ('channel_type', models.IntegerField(choices=[(0, 'Text'), (2, 'Voice'), (4, 'Category'), (5, 'Announcement'), (13, 'Stage'), (15, 'Forum'), (16, 'Media')], default=0, help_text='Discord channel type')),
                ('position', models.IntegerField(default=0, help_text='Channel position in the list')),
                ('category_id', models.CharField(blank=True, default='', help_text='Parent category channel ID (snowflake)', max_length=20)),
                ('category_name', models.CharField(blank=True, default='', help_text='Parent category name (denormalized for display)', max_length=100)),
                ('date_synced', models.DateTimeField(auto_now=True, help_text='When this channel was last synced from Discord')),
            ],
            options={
                'verbose_name': 'Discord Channel',
                'verbose_name_plural': 'Discord Channels',
                'ordering': ['category_name', 'position'],
            },
        ),
    ]
