# Generated by Django 6.0 on 2025-12-30 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0015_remove_teamconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_id', models.CharField(help_text='Discord role ID (snowflake)', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Role name', max_length=100)),
                ('color', models.IntegerField(default=0, help_text='Role color as integer')),
                ('position', models.IntegerField(default=0, help_text='Role position in hierarchy (higher = more authority)')),
                ('managed', models.BooleanField(default=False, help_text='Whether this role is managed by an integration/bot')),
                ('mentionable', models.BooleanField(default=False, help_text='Whether this role can be mentioned')),
                ('date_synced', models.DateTimeField(auto_now=True, help_text='When this role was last synced from Discord')),
            ],
            options={
                'verbose_name': 'Discord Role',
                'verbose_name_plural': 'Discord Roles',
                'ordering': ['-position'],
            },
        ),
    ]
