# Generated by Django 6.0.2 on 2026-02-24 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0015_discord_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racereadyrecord',
            name='media_type',
            field=models.CharField(choices=[('video', 'Video'), ('photo', 'Photo'), ('link', 'Link')], help_text='Type of media', max_length=10),
        ),
    ]
