# Generated by Django 6.0 on 2026-01-01 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0016_discordrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='racereadyrecord',
            name='ftp',
            field=models.PositiveIntegerField(blank=True, help_text='Functional Threshold Power in watts (for power verification)', null=True),
        ),
        migrations.AddField(
            model_name='racereadyrecord',
            name='height',
            field=models.PositiveIntegerField(blank=True, help_text='Height in cm (for height verification)', null=True),
        ),
        migrations.AddField(
            model_name='racereadyrecord',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg (for weight verification)', max_digits=5, null=True),
        ),
    ]
