# Generated by Django 6.0.3 on 2026-03-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0016_alter_racereadyrecord_media_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='racereadyrecord',
            old_name='rejection_reason',
            new_name='review_note',
        ),
        migrations.AlterField(
            model_name='racereadyrecord',
            name='review_note',
            field=models.TextField(blank=True, help_text='Reviewer note (for any status change)'),
        ),
    ]
