# Generated by Django 6.0.5 on 2026-05-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0017_rename_rejection_reason_to_review_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='racereadyrecord',
            name='last_warned_at',
            field=models.DateField(blank=True, help_text='Date of the most recent expiring-verification DM for this record. Used by warn_expiring_verifications to enforce one DM per record per day.', null=True),
        ),
    ]
