# Generated by Django 6.0.7 on 2026-08-16 15:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0018_racereadyrecord_last_warned_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_count', models.PositiveIntegerField(default=0, help_text='Times this user opened the record detail page')),
                ('media_view_count', models.PositiveIntegerField(default=0, help_text="Times the record's media (photo/video/link) was actually shown to this user")),
                ('first_viewed_at', models.DateTimeField(auto_now_add=True, help_text='When this user first viewed the record')),
                ('last_viewed_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When this user most recently viewed it')),
                ('record', models.ForeignKey(help_text='Verification record that was viewed', on_delete=django.db.models.deletion.CASCADE, related_name='record_views', to='team.racereadyrecord')),
                ('user', models.ForeignKey(help_text='User who viewed the record', on_delete=django.db.models.deletion.CASCADE, related_name='verification_record_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Record View',
                'verbose_name_plural': 'Record Views',
                'ordering': ['-last_viewed_at'],
                'indexes': [models.Index(fields=['record', '-last_viewed_at'], name='team_record_record__3fb56c_idx')],
                'constraints': [models.UniqueConstraint(fields=('record', 'user'), name='unique_record_view_per_user')],
            },
        ),
    ]
