# Generated by Django 6.1 on 2026-09-02 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0019_recordview'),
    ]

    operations = [
        migrations.AddField(
            model_name='racereadyrecord',
            name='last_warned_threshold',
            field=models.IntegerField(blank=True, help_text="Lowest EXPIRE_WARNING_DAYS threshold already warned about for this record. Without it the task could only ask 'did we DM today', never 'which warning has this rider actually had' -- so a run that missed a threshold day could never make it up.", null=True),
        ),
    ]
