# Generated by Django 6.1 on 2026-09-10 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0020_add_last_warned_threshold'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Shown to riders, e.g. '2026 Race Kit'", max_length=100)),
                ('slug', models.SlugField(help_text="Permanent key for this kit in each rider's record. Cannot be changed after creation.", max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional detail shown to riders')),
                ('active', models.BooleanField(default=True, help_text="Inactive kits are hidden and not offered, but riders' statuses for them are kept")),
                ('sort_order', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers are listed first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Team kit',
                'verbose_name_plural': 'Team kits',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
