# Generated by Django 6.1 on 2026-09-10 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0021_team_kit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamkit',
            options={'ordering': ['-is_current', 'sort_order', 'name'], 'verbose_name': 'Team kit', 'verbose_name_plural': 'Team kits'},
        ),
        migrations.AddField(
            model_name='teamkit',
            name='is_current',
            field=models.BooleanField(default=False, help_text='The kit the team is currently getting everyone into. Only one kit can be current.'),
        ),
        migrations.AddConstraint(
            model_name='teamkit',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('is_current',), name='team_kit_single_current'),
        ),
        migrations.AddConstraint(
            model_name='teamkit',
            constraint=models.CheckConstraint(condition=models.Q(('is_current', False), ('active', True), _connector='OR'), name='team_kit_current_is_active'),
        ),
    ]
