# Generated by Django 6.1 on 2026-09-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0022_team_kit_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamkit',
            name='icon',
            field=models.ImageField(blank=True, help_text='Shown on the roster card of riders who have this kit. Leave empty to use the site-wide icon.', upload_to='kit_icons/'),
        ),
    ]
