# Generated by Django 6.1 on 2026-09-16 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0023_teamkit_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racereadyrecord',
            name='media_type',
            field=models.CharField(choices=[('video', 'Video'), ('photo', 'Photo'), ('link', 'Link'), ('other', 'Other')], help_text='Type of media', max_length=10),
        ),
    ]
