"""Django settings for gotta_bike_platform project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

import dj_database_url
import logfire

from gotta_bike_platform.config import settings as config

# Configure Logfire for observability
# LOGFIRE_TOKEN is required in production; if not set, logs are local only
logfire.configure(
    service_name="coalition-platform",
    environment=config.logfire_environment,
    token=config.logfire_token,
    send_to_logfire="if-token-present",
)
# Instrument Django for automatic request/response logging
logfire.instrument_django()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

SECRET_KEY = config.secret_key

DEBUG = config.debug

ALLOWED_HOSTS = config.allowed_hosts

INTERNAL_IPS = config.internal_ips

TAILWIND_APP_NAME = "theme"

# Security settings for production (behind reverse proxy)
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    # Allauth
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.discord",
    "allauth.mfa",
    # Third-party
    "constance",
    "constance.backends.database",
    "corsheaders",
    "storages",
    "django_htmx",
    "tailwind",
    "theme",
    "reset_migrations",
    # Project apps
    "gotta_bike_platform",
    "apps.accounts.apps.AccountsConfig",
    "apps.team.apps.TeamConfig",
    "apps.zwift.apps.ZwiftConfig",
    "apps.zwiftpower.apps.ZwiftpowerConfig",
    "apps.zwiftracing.apps.ZwiftracingConfig",
    "apps.magic_links.apps.MagicLinksConfig",
    "apps.dbot_api.apps.DbotApiConfig",
    "apps.data_connection.apps.DataConnectionConfig",
    "django_tasks",
    "django_tasks.backends.database",
]

# Custom User Model
AUTH_USER_MODEL = "accounts.User"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_htmx.middleware.HtmxMiddleware",
]

# Add WhiteNoise only when NOT using S3 (local development)
if not config.use_s3_storage:
    MIDDLEWARE.insert(1, "whitenoise.middleware.WhiteNoiseMiddleware")

if DEBUG:
    INSTALLED_APPS += [
        "debug_toolbar",
        "django_browser_reload",
    ]
    MIDDLEWARE = (
        [
            "debug_toolbar.middleware.DebugToolbarMiddleware",
        ]
        + MIDDLEWARE
        + [
            "django_browser_reload.middleware.BrowserReloadMiddleware",
        ]
    )

ROOT_URLCONF = "gotta_bike_platform.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "constance.context_processors.config",
            ],
        },
    },
]

WSGI_APPLICATION = "gotta_bike_platform.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.config(
        default=config.database_url,
        conn_max_age=600,
        conn_health_checks=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Media files (user uploads)
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

# Storage configuration
if config.use_s3_storage:
    # Production: S3-compatible storage (Railway.app)
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3.S3Storage",
            "OPTIONS": {
                "bucket_name": config.aws_storage_bucket_name,
                "endpoint_url": config.aws_s3_endpoint_url,
                "region_name": config.aws_s3_region_name,
                "access_key": config.aws_access_key_id,
                "secret_key": config.aws_secret_access_key,
                "location": "media",
                "file_overwrite": False,
            },
        },
        "staticfiles": {
            "BACKEND": "storages.backends.s3.S3Storage",
            "OPTIONS": {
                "bucket_name": config.aws_storage_bucket_name,
                "endpoint_url": config.aws_s3_endpoint_url,
                "region_name": config.aws_s3_region_name,
                "access_key": config.aws_access_key_id,
                "secret_key": config.aws_secret_access_key,
                "location": "static",
            },
        },
    }
    # Update URLs for S3
    STATIC_URL = (
        f"{config.aws_s3_endpoint_url}/{config.aws_storage_bucket_name}/static/"
    )
    MEDIA_URL = f"{config.aws_s3_endpoint_url}/{config.aws_storage_bucket_name}/media/"
else:
    # Local development: WhiteNoise for static files
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }


# Background Tasks
# https://docs.djangoproject.com/en/6.0/topics/tasks/

TASKS = {
    "default": {
        "BACKEND": "django_tasks.backends.database.DatabaseBackend",
    }
}


# Django Allauth
# https://docs.allauth.org/en/latest/

SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",  # Django admin login
    "allauth.account.auth_backends.AuthenticationBackend",  # Allauth social login
]

# Account settings (allauth 65.x format)
ACCOUNT_EMAIL_VERIFICATION = "none"  # Discord emails are pre-verified
ACCOUNT_USER_MODEL_USERNAME_FIELD = "username"
ACCOUNT_LOGIN_METHODS = {"email"}  # Use email as identifier
ACCOUNT_SIGNUP_FIELDS = ["email*"]  # Only email required for signup

# Social account settings
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True
SOCIALACCOUNT_LOGIN_ON_GET = True

# Custom adapter for Discord field population
SOCIALACCOUNT_ADAPTER = "apps.accounts.adapters.DiscordSocialAccountAdapter"

# Discord provider settings
SOCIALACCOUNT_PROVIDERS = {
    "discord": {
        "VERIFIED_EMAIL": True,
        "SCOPE": ["identify", "email", "guilds"],  # guilds scope for membership check
        "AUTH_PARAMS": {
            "prompt": "consent",
        },
    }
}

# Only configure Discord app if credentials are provided
if config.discord_client_id and config.discord_client_secret:
    SOCIALACCOUNT_PROVIDERS["discord"]["APP"] = {
        "client_id": config.discord_client_id,
        "secret": config.discord_client_secret,
    }

# Redirect URLs
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"
LOGIN_URL = "account_login"

# MFA settings
MFA_TOTP_ISSUER = "The Coalition"
MFA_RECOVERY_CODE_COUNT = 10
MFA_TOTP_PERIOD = 30
MFA_TOTP_DIGITS = 6

# CORS
# https://github.com/adamchainz/django-cors-headers
if config.cors_allowed_origins:
    if config.cors_allowed_origins == ["*"]:
        CORS_ALLOW_ALL_ORIGINS = True
    else:
        CORS_ALLOWED_ORIGINS = config.cors_allowed_origins

# Logging - capture errors even with DEBUG=False
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "WARNING",
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
        "django.request": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
    },
}


# Django Constance - Dynamic Settings
# https://django-constance.readthedocs.io/

CONSTANCE_BACKEND = "constance.backends.database.DatabaseBackend"

CONSTANCE_ADDITIONAL_FIELDS = {
    "password_field": [
        "django.forms.fields.CharField",
        {
            "widget": "django.forms.PasswordInput",
            "widget_kwargs": {"render_value": True},
        },
    ],
    "json_list_field": [
        "django.forms.fields.CharField",
        {
            "widget": "django.forms.Textarea",
            "widget_kwargs": {"attrs": {"rows": 2, "placeholder": '["role_id_1", "role_id_2"]'}},
            "required": False,
        },
    ],
}

CONSTANCE_CONFIG = {
    # Team identity
    "TEAM_NAME": ("The Coalition", "Name of the team", str),
    "GUILD_NAME": ("The Coalition", "Name of the Discord guild/server", str),
    "GUILD_ID": (1317875072089981021, "Discord guild/server ID", int),
    "ZWIFTPOWER_TEAM_ID": (0, "ZwiftPower team ID for fetching team data", int),
    # Zwift credentials (for ZwiftPower API access)
    "ZWIFT_USERNAME": ("", "Zwift account username/email for API access", str),
    "ZWIFT_PASSWORD": ("", "Zwift account password for API access", "password_field"),
    # API Keys
    "DBOT_AUTH_KEY": ("", "Discord bot API authentication key", "password_field"),
    "ZRAPP_API_URL": (
        "https://api.zwiftracing.app/api/public/",
        "Zwift Racing App API base URL",
        str,
    ),
    "ZRAPP_API_KEY": ("", "Zwift Racing App API key", "password_field"),
    # Permission role mappings (JSON arrays of Discord role IDs)
    "PERM_APP_ADMIN_ROLES": ("[]", "Discord role IDs that grant app admin permission", "json_list_field"),
    "PERM_TEAM_CAPTAIN_ROLES": ("[]", "Discord role IDs that grant team captain permission", "json_list_field"),
    "PERM_VICE_CAPTAIN_ROLES": ("[]", "Discord role IDs that grant vice captain permission", "json_list_field"),
    "PERM_LINK_ADMIN_ROLES": (
        "[]",
        "Discord role IDs that allow a user to create, edit and delete links",
        "json_list_field",
    ),
    "PERM_MEMBERSHIP_ADMIN_ROLES": ("[]", "Discord role IDs that grant membership admin permission", "json_list_field"),
    "PERM_RACING_ADMIN_ROLES": ("[]", "Discord role IDs that grant racing admin permission", "json_list_field"),
    "PERM_TEAM_MEMBER_ROLES": (
        "[]",
        "Discord role IDs for team members. Without this role, users can only see the index page and their personal profile page (including verifications). All other pages require this permission.",
        "json_list_field",
    ),
    "PERM_RACE_READY_ROLES": ("[]", "Discord role IDs for race ready status", "json_list_field"),
    # Verification validity periods (in days)
    "WEIGHT_FULL_DAYS": (180, "Days a full weight verification is valid", int),
    "WEIGHT_LIGHT_DAYS": (30, "Days a light weight verification is valid", int),
    "HEIGHT_VERIFICATION_DAYS": (
        0,
        "Days a height verification is valid (0 = forever)",
        int,
    ),
    "POWER_VERIFICATION_DAYS": (365, "Days a power verification is valid", int),
    # Race Ready role assignment
    "RACE_READY_ROLE_ID": (
        0,
        "Discord role ID to assign when user meets verification requirements (0 = disabled)",
        int,
    ),
    # Verification instructions
    "WEIGHT_INSTRUCTIONS_URL": ("", "URL to weight verification instructions", str),
    "HEIGHT_INSTRUCTIONS_URL": ("", "URL to height verification instructions", str),
    # Site settings
    "SITE_ANNOUNCEMENT": ("", "Announcement message displayed on all pages", str),
    "MAINTENANCE_MODE": (False, "Enable maintenance mode (restricts access)", bool),
    "SUBTITLE": (
        "A competitive Zwift racing team bringing together cyclists from around the world.",
        "Subtitle displayed on the home page",
        str,
    ),
    "ABOUT_URL": ("#", "URL to About page", str),
    "CONTACT_URL": ("#", "URL to Contact page", str),
    "DISCORD_URL": ("#", "Discord server invite link", str),
    # Legal
    "PRIVACY_POLICY_URL": ("", "URL to Privacy Policy page", str),
    "TERMS_OF_SERVICE_URL": ("", "URL to Terms of Service page", str),
    # Google Settings
    "GOOGLE_SERVICE_ACCOUNT_EMAIL": (
        "example@example.iam.gserviceaccount.com",
        "Google service account email",
        str,
    ),
    "GOOGLE_DRIVE_FOLDER_ID": (
        "",
        "Google Drive folder ID where files are stored (shared with service account)",
        str,
    ),
}

CONSTANCE_CONFIG_FIELDSETS = {
    "Site Settings": (
        "TEAM_NAME",
        "SUBTITLE",
        "SITE_ANNOUNCEMENT",
        "MAINTENANCE_MODE",
        "ABOUT_URL",
        "CONTACT_URL",
        "DISCORD_URL",
        "DBOT_AUTH_KEY",
    ),
    "Discord Guild": (
        "GUILD_NAME",
        "GUILD_ID",
    ),
    "Zwift Credentials": (
        "ZWIFT_USERNAME",
        "ZWIFT_PASSWORD",
        "ZWIFTPOWER_TEAM_ID",
    ),
    "Zwift Racing App": (
        "ZRAPP_API_URL",
        "ZRAPP_API_KEY",
    ),
    "Permission Mappings": (
        "PERM_APP_ADMIN_ROLES",
        "PERM_TEAM_CAPTAIN_ROLES",
        "PERM_VICE_CAPTAIN_ROLES",
        "PERM_LINK_ADMIN_ROLES",
        "PERM_MEMBERSHIP_ADMIN_ROLES",
        "PERM_RACING_ADMIN_ROLES",
        "PERM_TEAM_MEMBER_ROLES",
        "PERM_RACE_READY_ROLES",
    ),
    "Verification Settings": (
        "WEIGHT_FULL_DAYS",
        "WEIGHT_LIGHT_DAYS",
        "HEIGHT_VERIFICATION_DAYS",
        "POWER_VERIFICATION_DAYS",
        "RACE_READY_ROLE_ID",
        "WEIGHT_INSTRUCTIONS_URL",
        "HEIGHT_INSTRUCTIONS_URL",
    ),
    "Legal": (
        "PRIVACY_POLICY_URL",
        "TERMS_OF_SERVICE_URL",
    ),
    "Google Settings": (
        "GOOGLE_SERVICE_ACCOUNT_EMAIL",
        "GOOGLE_DRIVE_FOLDER_ID",
    ),
}
