"""Django settings for gotta_bike_platform project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
import logfire

from gotta_bike_platform.config import settings as config

# Configure Logfire for observability
# LOGFIRE_TOKEN is required in production; if not set, logs are local only
#
# Test runs are kept local. The suite deliberately exercises failure paths --
# permission-denied assertions, bad payloads -- and exporting those spans fills the
# Logfire dashboard with `testserver` "errors" that are really passing tests.
# PYTEST_VERSION is set by pytest >= 8.0 for the whole session, so it is already
# present when Django imports this module.
_UNDER_PYTEST = "PYTEST_VERSION" in os.environ

logfire.configure(
    service_name="coalition-platform",
    environment=config.logfire_environment,
    token=config.logfire_token,
    send_to_logfire=False if _UNDER_PYTEST else "if-token-present",
)
# Note: logfire.instrument_django() is called at the end of this file
# after Django settings are fully loaded

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

SECRET_KEY = config.secret_key

DEBUG = config.debug

ALLOWED_HOSTS = config.allowed_hosts

# Requests arriving over Railway's private network carry the service's internal hostname in
# Host, not the public domain, so Django rejects them with DisallowedHost (a 400 that looks
# nothing like a networking problem). Railway injects RAILWAY_PRIVATE_DOMAIN into every
# service, so take it from there rather than asking someone to keep a variable in step --
# it is correct per-service and per-environment without anyone maintaining it.
#
# This is what lets the Discord bot reach /api/dbot/ at coalitionapp.railway.internal
# instead of going out to the public internet and back through the edge.
RAILWAY_PRIVATE_DOMAIN = os.environ.get("RAILWAY_PRIVATE_DOMAIN", "").strip()
if RAILWAY_PRIVATE_DOMAIN and RAILWAY_PRIVATE_DOMAIN not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(RAILWAY_PRIVATE_DOMAIN)

INTERNAL_IPS = config.internal_ips

TAILWIND_APP_NAME = "theme"

# Security settings for production (behind reverse proxy)
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # HSTS. SECURE_SSL_REDIRECT already sends browsers to HTTPS, but it does so with a
    # redirect -- so the very first request of a session still leaves in the clear and can be
    # intercepted before the redirect is seen. HSTS closes that window by telling the browser
    # to go straight to HTTPS next time, without asking.
    #
    # It is worth understanding what this commits to, because it is not freely reversible: for
    # max-age seconds after their last visit, browsers that have seen this header will REFUSE
    # to load the site over plain HTTP, and clearing that early means reaching every visitor's
    # browser, which you cannot do. Set SECURE_HSTS_SECONDS low (3600) to trial it and raise
    # it once satisfied.
    #
    # INCLUDE_SUBDOMAINS applies to subdomains of the host that sent the header -- that is,
    # *.app.coalitionracing.com, not the apex and not siblings like zwiftspeedlab. Nothing is
    # served under app.* today, so this costs nothing and covers anything added later.
    #
    # PRELOAD stays off deliberately. It ships the domain in browsers' built-in lists, which
    # covers the whole apex including every sibling subdomain, and removal takes months. That
    # is a decision about the domain, not about this app.
    SECURE_HSTS_SECONDS = config.hsts_seconds
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = False

    # Derived from ALLOWED_HOSTS so a new host cannot be added in one place and forgotten in
    # the other. Not currently load-bearing -- one domain, and Django accepts same-origin
    # posts without it -- but it is what makes adding a second domain a one-variable change
    # instead of a puzzling 403 on every form.
    CSRF_TRUSTED_ORIGINS = config.csrf_trusted_origins

    # W021 says we could submit to the browser preload list. Declining is the decision above,
    # so silence it rather than carry a warning we intend never to act on -- a `check --deploy`
    # that always prints something is a check nobody reads.
    SILENCED_SYSTEM_CHECKS = ["security.W021"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    # Allauth
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.discord",
    "allauth.mfa",
    # Third-party
    "constance",
    "constance.backends.database",
    "corsheaders",
    "storages",
    "django_htmx",
    "tailwind",
    "theme",
    "simple_history",
    "django_countries",
    # Project apps
    "gotta_bike_platform",
    "apps.accounts.apps.AccountsConfig",
    "apps.team.apps.TeamConfig",
    "apps.zwift.apps.ZwiftConfig",
    "apps.zwiftpower.apps.ZwiftpowerConfig",
    "apps.zwiftracing.apps.ZwiftracingConfig",
    "apps.magic_links.apps.MagicLinksConfig",
    "apps.dbot_api.apps.DbotApiConfig",
    "apps.data_connection.apps.DataConnectionConfig",
    "apps.cms.apps.CmsConfig",
    "apps.analytics.apps.AnalyticsConfig",
    "apps.club_strava.apps.ClubStravaConfig",
    "apps.events.apps.EventsConfig",
    "apps.user_api.apps.UserApiConfig",
    "apps.tickets.apps.TicketsConfig",
    "apps.ttt_planner.apps.TttPlannerConfig",
    "apps.ladder_planner.apps.LadderPlannerConfig",
    "apps.zwift_data.apps.ZwiftDataConfig",
    "apps.rider_data.apps.RiderDataConfig",
    "django_tasks",
    "django_tasks_db",
]

# Custom User Model
AUTH_USER_MODEL = "accounts.User"

MIDDLEWARE = [
    # SecurityMiddleware, except that private-network traffic is not redirected to HTTPS.
    # See the class docstring for why this is host-based rather than SECURE_REDIRECT_EXEMPT.
    "gotta_bike_platform.middleware.PrivateNetworkAwareSecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "simple_history.middleware.HistoryRequestMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_htmx.middleware.HtmxMiddleware",
]

# WhiteNoise serves static files directly from the app server
# (S3 is only used for media/user uploads)
MIDDLEWARE.insert(1, "whitenoise.middleware.WhiteNoiseMiddleware")

if DEBUG:
    INSTALLED_APPS += [
        "debug_toolbar",
        "django_browser_reload",
    ]
    MIDDLEWARE = [
        "debug_toolbar.middleware.DebugToolbarMiddleware",
        *MIDDLEWARE,
        "django_browser_reload.middleware.BrowserReloadMiddleware",
    ]

ROOT_URLCONF = "gotta_bike_platform.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "constance.context_processors.config",
                "gotta_bike_platform.context_processors.site_settings",
                "gotta_bike_platform.context_processors.deploy_info",
                "apps.cms.context_processors.cms_nav_pages",
                "apps.team.context_processors.pending_verification_count",
                "apps.team.context_processors.expiring_verifications",
                "apps.events.context_processors.pending_availability_count",
            ],
        },
    },
]

WSGI_APPLICATION = "gotta_bike_platform.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.config(
        default=config.database_url,
        conn_max_age=config.db_conn_max_age,
        conn_health_checks=True,
    )
}


# Cache
# https://docs.djangoproject.com/en/6.0/topics/cache/
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Media files (user uploads)
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

# Storage configuration
# Static files: Always use WhiteNoise (fast deploys, served from app server)
# Media files: Use S3 when configured (user uploads), otherwise local filesystem
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

if config.use_s3_storage:
    # Production: S3-compatible storage for media/user uploads only
    STORAGES["default"] = {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": {
            "bucket_name": config.aws_storage_bucket_name,
            "endpoint_url": config.aws_s3_endpoint_url,
            "region_name": config.aws_s3_region_name,
            "access_key": config.aws_access_key_id,
            "secret_key": config.aws_secret_access_key,
            "location": "media",
            "file_overwrite": False,
            # 15 minutes rather than the 1-hour default. Every URL this storage hands out
            # is a bearer token -- the signature lives in the query string, so it is not
            # tied to a session and cannot be revoked. This is the floor for ordinary media
            # (site logos, hero images); pages are never HTML-cached, so a fresh URL is
            # minted on each render and a short window costs nothing.
            #
            # Verification media does NOT rely on this. It is body photography, and it is
            # served through team:verification_record_media, which re-checks permission on
            # every request and mints a much shorter URL per click. See that view.
            #
            # default_acl is deliberately left unset (django-storages sends no ACL header).
            # The bucket is private, so objects are private by inheritance, and several
            # S3-compatible providers reject PutObject calls that carry an ACL header.
            "querystring_expire": 900,
        },
    }
    MEDIA_URL = f"{config.aws_s3_endpoint_url}/{config.aws_storage_bucket_name}/media/"
else:
    # Local development: filesystem storage for media
    STORAGES["default"] = {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    }


# Background Tasks
# https://docs.djangoproject.com/en/6.0/topics/tasks/

TASKS = {
    "default": {
        "BACKEND": "django_tasks_db.DatabaseBackend",
    }
}


# Django Allauth
# https://docs.allauth.org/en/latest/

SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",  # Django admin login
    "allauth.account.auth_backends.AuthenticationBackend",  # Allauth social login
]

# Account settings (allauth 65.x format)
ACCOUNT_DEFAULT_HTTP_PROTOCOL = "https" if not DEBUG else "http"
ACCOUNT_EMAIL_VERIFICATION = "none"  # Discord emails are pre-verified
ACCOUNT_USER_MODEL_USERNAME_FIELD = "username"
ACCOUNT_LOGIN_METHODS = {"email"}  # Use email as identifier
ACCOUNT_SIGNUP_FIELDS = ["email*"]  # Only email required for signup

# Social account settings
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True
SOCIALACCOUNT_LOGIN_ON_GET = True

# Custom adapter for Discord field population
SOCIALACCOUNT_ADAPTER = "apps.accounts.adapters.DiscordSocialAccountAdapter"

# Discord provider settings
SOCIALACCOUNT_PROVIDERS = {
    "discord": {
        "VERIFIED_EMAIL": True,
        "SCOPE": ["identify", "email", "guilds"],  # guilds scope for membership check
        "AUTH_PARAMS": {
            "prompt": "consent",
        },
    }
}

# Only configure Discord app if credentials are provided
if config.discord_client_id and config.discord_client_secret:
    SOCIALACCOUNT_PROVIDERS["discord"]["APP"] = {
        "client_id": config.discord_client_id,
        "secret": config.discord_client_secret,
    }

# Redirect URLs
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"
LOGIN_URL = "account_login"

# MFA settings
MFA_TOTP_ISSUER = "The Coalition"
MFA_RECOVERY_CODE_COUNT = 10
MFA_TOTP_PERIOD = 30
MFA_TOTP_DIGITS = 6

# CORS
# https://github.com/adamchainz/django-cors-headers
if config.cors_allowed_origins:
    if config.cors_allowed_origins == ["*"]:
        CORS_ALLOW_ALL_ORIGINS = True
    else:
        CORS_ALLOWED_ORIGINS = config.cors_allowed_origins

# Logging - capture errors even with DEBUG=False
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "WARNING",
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
        "django.request": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
    },
}


# Django Constance - Dynamic Settings
# https://django-constance.readthedocs.io/

CONSTANCE_BACKEND = "constance.backends.database.DatabaseBackend"

CONSTANCE_ADDITIONAL_FIELDS = {
    "password_field": [
        "django.forms.fields.CharField",
        {
            "widget": "django.forms.PasswordInput",
            "widget_kwargs": {"render_value": True},
        },
    ],
    "json_list_field": [
        "django.forms.fields.CharField",
        {
            "widget": "django.forms.Textarea",
            "widget_kwargs": {"attrs": {"rows": 2, "placeholder": '["role_id_1", "role_id_2"]'}},
            "required": False,
        },
    ],
    "json_field": [
        "django.forms.fields.CharField",
        {
            "widget": "django.forms.Textarea",
            "widget_kwargs": {"attrs": {"rows": 4, "placeholder": '{"key": "value"}'}},
            "required": False,
        },
    ],
    "string_list_field": [
        "django.forms.fields.CharField",
        {
            "widget": "django.forms.Textarea",
            "widget_kwargs": {"attrs": {"rows": 4, "placeholder": '["item1", "item2", "item3"]'}},
            "required": False,
        },
    ],
    "textarea_field": [
        "django.forms.fields.CharField",
        {
            "widget": "django.forms.Textarea",
            "widget_kwargs": {"attrs": {"rows": 6}},
            "required": False,
        },
    ],
}

CONSTANCE_CONFIG = {
    # Team identity
    "TEAM_NAME": ("The Coalition", "Name of the team", str),
    "GUILD_NAME": ("The Coalition", "Name of the Discord guild/server", str),
    "GUILD_ID": (1317875072089981021, "Discord guild/server ID", int),
    "UPGRADE_CHANNEL": (0, "Discord channel ID for upgrade notifications", int),
    "NEW_ARRIVALS_CHANNEL_ID": (0, "Discord channel ID for new arrival welcome messages", int),
    "USER_CHANGE_LOG": (0, "Member status changes posted to this channel", int),
    "REGISTRATION_UPDATES_CHANNEL_ID": (0, "Discord channel for membership registration updates", int),
    "EVENT_ROLE_PREFIXES": ('["$", ">", "¡", "~", "^"]', "Allowed event role prefixes", "string_list_field"),
    "ZWIFTPOWER_TEAM_ID": (0, "ZwiftPower team ID for fetching team data", int),
    # Zwift credentials (for ZwiftPower API access)
    "ZWIFT_USERNAME": ("", "Zwift account username/email for API access", str),
    "ZWIFT_PASSWORD": ("", "Zwift account password for API access", "password_field"),
    # API Keys
    "DBOT_AUTH_KEY": ("", "This is the auth key the bot uses to communicate with this apps API.", "password_field"),
    "DISCORD_BOT_TOKEN": ("", "Discord bot token for sending DMs", "password_field"),
    "ZRAPP_API_URL": (
        "https://api.zwiftracing.app/api/public/",
        "Zwift Racing App API base URL",
        str,
    ),
    "ZRAPP_API_KEY": ("", "Zwift Racing App API key", "password_field"),
    # User-facing API (per-user keys at /user/api-keys/)
    "USER_API_RATE_LIMIT": (
        "60/m",
        "django-ratelimit rate string applied per API key on /api/user/ endpoints (e.g. '60/m', '1000/h')",
        str,
    ),
    "USER_API_MAX_KEYS_PER_USER": (
        3,
        "Maximum active (non-revoked, non-expired) API keys a user may hold at one time",
        int,
    ),
    "PERM_ROLES_REQUIRED_USE_API": (
        "[]",
        "Discord role IDs required (in addition to team_member and an active user) to create or use an API key. "
        "JSON array of role IDs; user must hold ALL of them. Empty list = no extra role restriction.",
        "json_list_field",
    ),
    # TrainingPeaks Virtual
    "TPV_CLUB_URL": (
        "",
        "TrainingPeaks Virtual club URL (e.g., https://tpvirtualhub.com/teams/CLTN)",
        str,
    ),
    # Permission role mappings (JSON arrays of Discord role IDs)
    "PERM_APP_ADMIN_ROLES": ("[]", "Discord role IDs that grant app admin permission", "json_list_field"),
    "PERM_TEAM_CAPTAIN_ROLES": ("[]", "Discord role IDs that grant team captain permission", "json_list_field"),
    "PERM_VICE_CAPTAIN_ROLES": ("[]", "Discord role IDs that grant vice captain permission", "json_list_field"),
    "PERM_LINK_ADMIN_ROLES": (
        "[]",
        "Discord role IDs that allow a user to create, edit and delete links",
        "json_list_field",
    ),
    "PERM_MEMBERSHIP_ADMIN_ROLES": ("[]", "Discord role IDs that grant membership admin permission", "json_list_field"),
    "PERM_RACING_ADMIN_ROLES": ("[]", "Discord role IDs that grant racing admin permission", "json_list_field"),
    "PERM_TEAM_MEMBER_ROLES": (
        "[]",
        "Discord role IDs for team members. Without this role, users can only see the index page and "
        "their personal profile page (including verifications). All other pages require this permission.",
        "json_list_field",
    ),
    "PERM_RACE_READY_ROLES": ("[]", "Discord role IDs for race ready status", "json_list_field"),
    "PERM_APPROVE_VERIFICATION_ROLES": (
        "[]",
        "Discord role IDs that allow a user to approve/reject verification records",
        "json_list_field",
    ),
    "PERM_DATA_CONNECTION_ROLES": (
        "[]",
        "Discord role IDs that grant access to Data Connections (Google Sheets exports)",
        "json_list_field",
    ),
    "PERM_PAGES_ADMIN_ROLES": (
        "[]",
        "Discord role IDs that grant CMS page management (create, edit, delete pages)",
        "json_list_field",
    ),
    "PERM_PERFORMANCE_VERIFICATION_TEAM_ROLES": (
        "[]",
        "Discord role IDs for performance verification team members",
        "json_list_field",
    ),
    "PERM_EVENT_ADMIN_ROLES": (
        "[]",
        "Discord role IDs that grant event management permission (create, edit, delete events and races)",
        "json_list_field",
    ),
    "PERM_ASSIGN_ROLES": (
        "[]",
        "Discord role IDs that grant permission to assign Discord roles",
        "json_list_field",
    ),
    "PERM_TICKET_ADMIN_ROLES": (
        "[]",
        "Discord role IDs that grant access to every ticket at /tickets/. Without it a "
        "member sees only the tickets they submitted or are assigned.",
        "json_list_field",
    ),
    # Verification validity periods (in days)
    "WEIGHT_FULL_DAYS": (120, "Days a full weight verification is valid", int),
    "WEIGHT_LIGHT_DAYS": (30, "Days a light weight verification is valid", int),
    "HEIGHT_VERIFICATION_DAYS": (
        0,
        "Days a height verification is valid (0 = forever)",
        int,
    ),
    "POWER_VERIFICATION_DAYS": (365, "Days a power verification is valid", int),
    "SCHEDULER_SYNC_RIDER_PROFILES_HOURS": (
        24,
        "Hours between rider profile refreshes from the zauth service",
        int,
    ),
    "RIDER_PROFILE_PURGE_MAX_FRACTION": (
        0.2,
        "Refuse a rider-profile purge that would delete more than this share of the cache in "
        "one run. A sweep that large means the refresh set is wrong, not that every rider left. "
        "0 disables the check",
        float,
    ),
    "RIDER_PROFILE_MAX_DAYS": (
        120,
        "Days a cached rider profile is kept after it was last refreshed. The sync refreshes "
        "every rider we have a reason to hold, so an old fetch means the rider has dropped out "
        "of that set entirely. 0 disables eviction",
        int,
    ),
    "RIDER_PROFILE_REFRESH_HOURS": (
        24,
        "Hours before a cached rider profile is considered stale and worth refetching (0 = never stale)",
        int,
    ),
    "VERIFICATION_MEDIA_MAX_DAYS": (
        365,
        "Maximum days to keep verification photos and videos, whatever the type and even if "
        "the verification itself never expires (0 = keep indefinitely)",
        int,
    ),
    "POWER_REQUIRES_PER_VER": (
        False,
        "Require PERM_PERFORMANCE_VERIFICATION_TEAM_ROLES to review power records",
        bool,
    ),
    "EXPIRE_WARNING_DAYS": (
        "[15, 7, 3, 1]",
        "Days before expiration to warn users. JSON list of integers.",
        "json_field",
    ),
    # Category-based verification requirements
    "CATEGORY_REQUIREMENTS": (
        '{"5": ["weight_full", "height", "power"], "10": ["weight_full", "height"], '
        '"20": ["weight_full", "height"], "30": ["weight_full", "height"], '
        '"40": ["weight_full", "weight_light", "height"], "50": ["weight_full", "weight_light", "height"]}',
        "Record types required per ZwiftPower category. Keys are division numbers, values are required types.",
        "json_field",
    ),
    # Discord role assignments
    "TEAM_MEMBER_ROLE_ID": (
        0,
        "Discord role ID that identifies team members (0 = disabled)",
        int,
    ),
    "RACE_READY_ROLE_ID": (
        0,
        "Discord role ID to assign when user meets verification requirements (0 = disabled)",
        int,
    ),
    "NEW_MEMBER_ROLE_ID": (
        0,
        "Discord role ID for new members (0 = disabled)",
        int,
    ),
    "DS_ROLE_ID": (
        0,
        "Discord role ID for Directeurs Sportifs (0 = disabled)",
        int,
    ),
    "NEW_MEMBER_DAYS": (
        30,
        "Number of days a member is considered new",
        int,
    ),
    # New arrival messages (sent by Discord bot)
    # Use {member} for member mention/name, {server} for server name
    "NEW_ARRIVAL_MESSAGE_PUBLIC": (
        "Hello {member}, welcome to THE COALITION! Our membership team is here to help.\n"
        "Please complete your membership registration by clicking the button below "
        "or typing `/join_the_coalition`.",
        "Public welcome message posted in the welcome channel. Use {member} for mention, {server} for server name.",
        "textarea_field",
    ),
    "NEW_ARRIVAL_MESSAGE_PRIVATE": (
        "Welcome to The Coalition! Please complete your team registration using the button below.",
        "Private DM sent to new members. Use {member} for name, {server} for server name.",
        "textarea_field",
    ),
    "SEND_NEW_ARRIVAL_DM": (
        True,
        "Send new arrivals a DM with NEW_ARRIVAL_MESSAGE_PRIVATE and application link",
        bool,
    ),
    # Help message for Discord bot
    "HELP_MESSAGE": (
        "Racing on Zwift transcends mere exercise; it's a metaphysical confrontation "
        "between ego and algorithm — where watts become wisdom, suffering becomes synergy, "
        "and every virtual climb mirrors the uphill struggles of our digitized humanity.",
        "Message displayed by the Discord bot /help command. Supports Markdown.",
        "textarea_field",
    ),
    # Zwift OAuth (zauth) migration prompt
    "ZAUTH_BANNER_ENABLED": (
        False,
        "Show a site banner to members who have not verified via Zwift OAuth, linking them to "
        "the connect page. Separate from the profile-incomplete banner.",
        bool,
    ),
    "ZAUTH_BANNER_MESSAGE": (
        "Zwift now supports connecting your account directly. Please link your Zwift account "
        "to keep your race verification up to date.",
        "Text shown in the Zwift OAuth banner. Supports Markdown.",
        "textarea_field",
    ),
    "ZAUTH_VERIFICATION_REQUIRED": (
        False,
        "NOT YET ENFORCED — the cutover switch for Zwift OAuth. When it is wired up, turning "
        "this on will make legacy and admin verifications count as unverified for gating, so "
        "only Zwift OAuth counts. Leave off until the Zwift Verification report shows the "
        "legacy and not-verified counts at or near zero.",
        bool,
    ),
    # Verification instructions
    "VERIFICATION_FORM_MESSAGE": (
        "",
        "Message displayed at the top of the verification form. Supports Markdown.",
        "textarea_field",
    ),
    "VERIFICATION_CHECK_LIST": (
        '{"weight_full": ['
        '"Rider shows face and date/time via timeanddate.com refresh", '
        '"Rider weight shown clearly on scale", '
        '"Rider shows bottom of scale/sets back down in a different spot", '
        '"Heavy weight (labeled) and shown clearly on scale", '
        '"Combined weight (rider + weight) shown clearly on scale", '
        '"Zwift weight updated on screen and matches scale"], '
        '"weight_light": ['
        '"Photo/video shows rider on scale (centre of room)", '
        '"Weight reading clearly visible", '
        '"Date shown (screen or written, post-it is ok)", '
        '"Zwift weight updated and matches"], '
        '"height": ['
        '"Full body visible", '
        '"Book or similar flat on head against wall", '
        '"Wall mark shown", '
        '"Tape measure from floor to mark shown clearly", '
        '"Show Zwift height matches measurement"], '
        '"power": ['
        '"Dual record link on ZP looks ok"]}',
        "JSON checklist for verification reviewers. Keys are verify types, values are lists of checklist items.",
        "json_field",
    ),
    "WEIGHT_INSTRUCTIONS_URL": ("", "URL to weight verification instructions", str),
    "HEIGHT_INSTRUCTIONS_URL": ("", "URL to height verification instructions", str),
    # Equipment options
    "TRAINER_OPTIONS": (
        '["Wahoo Kickr Core", "Wahoo Kickr Move", "Wahoo Kickr", "Wahoo Kickr Bike", '
        '"Saris H3", "Elite Justo 2", "Tacx Neo", "D100", "Wattbike", '
        '"Wattbike Atom Next Gen", "Tacx Neo Bike", "Technogym Ride", "Stages Bike", '
        '"Zwift Hub", "Zwift Bike, Wahoo Kickr", "Other wheel trainer (Wheel on bike)", '
        '"Other Direct drive trainer (wheel off)"]',
        "List of trainer options for equipment selection",
        "string_list_field",
    ),
    "POWERMETER_OPTIONS": (
        '["Quarq", "Stages", "Sram", "Shimano", "4ii", "Garmin pedals", '
        '"Favero Assioma pedals", "Other power pedals", "Other power cranks", "Other"]',
        "List of powermeter options for equipment selection",
        "string_list_field",
    ),
    "HEARTRATE_MONITOR_OPTIONS": (
        '["Garmin", "Wahoo", "Polar", "Coros", "Other"]',
        "List of heart rate monitor options for equipment selection",
        "string_list_field",
    ),
    # Registration
    "REGISTRATION_FORM_INSTRUCTIONS": (
        "",
        "Instructions displayed at the top of the membership application form. Supports Markdown.",
        "textarea_field",
    ),
    # Site settings
    "SITE_ANNOUNCEMENT": (
        "",
        "Announcement banner on all pages. Supports Markdown: **bold**, *italic*, [links](url)",
        str,
    ),
    "MAINTENANCE_MODE": (False, "Enable maintenance mode (restricts access)", bool),
    "GOOGLE_ANALYTICS_ID": ("", "Google Analytics measurement ID (e.g., G-XXXXXXXXXX)", str),
    "LOGO_DISPLAY_MODE": (
        "name_only",
        "Header display mode: 'logo_only', 'logo_and_name', or 'name_only'",
        str,
    ),
    "SUBTITLE": (
        "A competitive Zwift racing team bringing together cyclists from around the world.",
        "Subtitle displayed on the home page",
        str,
    ),
    "HOME_PAGE_SLUG": (
        "",
        "CMS page slug to use as the home page for non-logged-in users (leave empty for default)",
        str,
    ),
    "HOME_PAGE_SLUG_AUTHENTICATED": (
        "",
        "CMS page slug to use as the home page for logged-in users (leave empty to use HOME_PAGE_SLUG)",
        str,
    ),
    "ABOUT_URL": ("#", "URL to About page", str),
    "CONTACT_URL": ("#", "URL to Contact page", str),
    "DISCORD_URL": ("#", "Discord server invite link", str),
    # Social Links
    "SOCIAL_LINKEDIN_URL": ("", "LinkedIn page URL", str),
    "SOCIAL_FACEBOOK_URL": ("", "Facebook page URL", str),
    "SOCIAL_INSTAGRAM_URL": ("", "Instagram profile URL", str),
    "SOCIAL_TWITTER_URL": ("", "Twitter/X profile URL", str),
    # SEO Settings
    "META_DESCRIPTION": (
        "The Coalition is a competitive Zwift racing team bringing together cyclists from around the world.",
        "Meta description for search engines (150-160 characters recommended)",
        str,
    ),
    "META_KEYWORDS": (
        "zwift, cycling, esports, racing, virtual cycling, zwift racing, coalition",
        "Meta keywords for search engines (comma-separated)",
        str,
    ),
    "OG_IMAGE_URL": (
        "",
        "Open Graph image URL for social media sharing (1200x630 recommended)",
        str,
    ),
    "ROBOTS_DISALLOW_ALL": (
        False,
        "Block all search engine crawlers from indexing the site (robots.txt Disallow: /)",
        bool,
    ),
    "ROBOTS_DISALLOW_AI": (
        False,
        "Block AI crawlers (GPTBot, ChatGPT-User, Claude-Web, Google-Extended, etc.) from the site",
        bool,
    ),
    # Legal
    "PRIVACY_POLICY_URL": ("", "URL to Privacy Policy page", str),
    "TERMS_OF_SERVICE_URL": ("", "URL to Terms of Service page", str),
    # Google Settings
    "GOOGLE_SERVICE_ACCOUNT_EMAIL": (
        "example@example.iam.gserviceaccount.com",
        "Google service account email",
        str,
    ),
    "GOOGLE_DRIVE_FOLDER_ID": (
        "",
        "Google Drive folder ID where files are stored (shared with service account)",
        str,
    ),
    # Zwift Racing Category Roles
    "ZR_UPGRADE_NOTICE_CHANNEL": (0, "Discord channel ID for ZR category upgrade notifications", int),
    "ZR_CATEGORY_SUFFIX": ("", "Suffix appended to Discord role names for ZR category roles", str),
    "ZR_ROLE_DIAMOND": (0, "Discord role ID for Diamond category", int),
    "ZR_ROLE_RUBY": (0, "Discord role ID for Ruby category", int),
    "ZR_ROLE_EMERALD": (0, "Discord role ID for Emerald category", int),
    "ZR_ROLE_SAPPHIRE": (0, "Discord role ID for Sapphire category", int),
    "ZR_ROLE_AMETHYST": (0, "Discord role ID for Amethyst category", int),
    "ZR_ROLE_PLATINUM": (0, "Discord role ID for Platinum category", int),
    "ZR_ROLE_GOLD": (0, "Discord role ID for Gold category", int),
    "ZR_ROLE_SILVER": (0, "Discord role ID for Silver category", int),
    "ZR_ROLE_BRONZE": (0, "Discord role ID for Bronze category", int),
    "ZR_ROLE_COPPER": (0, "Discord role ID for Copper category", int),
    "ZR_ROLE_UNASSIGNED": (0, "Discord role ID for unassigned category", int),
    # Events
    "EVENT_TYPES": (
        '["ZRL", "TTT", "FRR", "Club Ladder", "Other"]',
        "List of event types available for event creation",
        "string_list_field",
    ),
    # Zwift Speed Lab (canonical route/segment/world dataset)
    "ZWIFT_SPEED_LAB_URL": (
        "https://zwiftspeedlab.coalitionracing.com",
        "Base URL of the Zwift Speed Lab app; its /api/data/all.zip bundle seeds the canonical dataset",
        str,
    ),
    # Strava API
    "STRAVA_CLUB_ID": (0, "Strava club ID for fetching club activities", int),
    "STRAVA_CLUB_URL": ("", "Strava club URL (e.g., https://www.strava.com/clubs/your-club)", str),
    "STRAVA_CLIENT_ID": ("", "Strava API client ID (from your Strava app)", str),
    "STRAVA_CLIENT_SECRET": ("", "Strava API client secret", "password_field"),
    "STRAVA_ACCESS_TOKEN": ("", "Strava API access token", "password_field"),
    "STRAVA_REFRESH_TOKEN": ("", "Strava API refresh token", "password_field"),
    # Scheduler intervals
    "SCHEDULER_UPDATE_TEAM_RIDERS_HOURS": (
        6,
        "How often to fetch team riders from ZwiftPower (hours). Requires scheduler restart to take effect.",
        int,
    ),
    "SCHEDULER_UPDATE_TEAM_RESULTS_HOURS": (
        6,
        "How often to fetch team results from ZwiftPower (hours). Requires scheduler restart to take effect.",
        int,
    ),
    "SCHEDULER_REFRESH_ALL_RACE_READY_HOURS": (
        6,
        "How often to refresh cached is_race_ready status (hours). Requires scheduler restart to take effect.",
        int,
    ),
    "SCHEDULER_SYNC_YOUTUBE_CHANNEL_IDS_HOURS": (
        6,
        "How often to extract YouTube channel IDs (hours). Requires scheduler restart to take effect.",
        int,
    ),
    "SCHEDULER_SYNC_YOUTUBE_VIDEOS_HOURS": (
        6,
        "How often to fetch YouTube videos (hours). Requires scheduler restart to take effect.",
        int,
    ),
    "SCHEDULER_WARN_EXPIRING_VERIFICATIONS_HOURS": (
        24,
        "How often to check for expiring verifications and send DMs (hours). "
        "Requires scheduler restart to take effect.",
        int,
    ),
    "SCHEDULER_SYNC_DISCORD_ROLES_HOURS": (
        6,
        "How often to sync Discord roles (hours). Requires scheduler restart to take effect.",
        int,
    ),
    "SCHEDULER_SYNC_DISCORD_CHANNELS_HOURS": (
        6,
        "How often to sync Discord channels (hours). Requires scheduler restart to take effect.",
        int,
    ),
    "SCHEDULER_SYNC_ZR_RIDERS_HOURS": (
        6,
        "How often to sync riders from Zwift Racing API (hours). Requires scheduler restart to take effect.",
        int,
    ),
    "SCHEDULER_SYNC_STRAVA_ACTIVITIES_HOURS": (
        6,
        "How often to sync Strava club activities (hours). Requires scheduler restart to take effect.",
        int,
    ),
    "SCHEDULER_SYNC_RACE_READY_ROLES_HOURS": (
        6,
        "How often to sync race ready Discord roles (hours). Requires scheduler restart to take effect.",
        int,
    ),
    "SCHEDULER_GUILD_MEMBER_SYNC_STATUS_HOURS": (
        6,
        "How often to check guild member sync health (hours). Requires scheduler restart to take effect.",
        int,
    ),
    "SCHEDULER_SYNC_GUILD_MEMBERS_HOURS": (
        6,
        "How often to sync Discord guild members (hours). Requires scheduler restart to take effect.",
        int,
    ),
    "ZWIFT_METRICS_FALLBACK_MIN_MINUTES": (
        30,
        "Below this interval (minutes), the zFTP/zMAP refresh skips its per-rider "
        "fallback. That fallback makes one call per rider and can reach Zwift itself, "
        "so at a short cadence it would multiply into a rate-limit problem. The bulk "
        "path is unaffected and still runs.",
        int,
    ),
    "SCHEDULER_REFRESH_ZWIFT_METRICS_MINUTES": (
        5,
        "How often to mirror connected riders' zFTP/zMAP from the zauth service (MINUTES). "
        "One HTTP call per run against the service's own database, and the service is "
        "webhook-fresh -- Zwift pushes it a notification when a rider's metrics change -- "
        "so a short interval genuinely delivers fresher numbers. Below "
        "ZWIFT_METRICS_FALLBACK_MIN_MINUTES the per-rider fallback is skipped, since that "
        "path can reach Zwift itself. Requires scheduler restart to take effect.",
        int,
    ),
    "SCHEDULER_SYNC_NEW_MEMBER_ROLES_HOURS": (
        6,
        "How often to sync New Member Discord role based on guild join date (hours). "
        "Requires scheduler restart to take effect.",
        int,
    ),
    "SCHEDULER_SYNC_ZR_CATEGORY_ROLES_HOURS": (
        6,
        "How often to sync ZR category Discord roles (hours). Requires scheduler restart to take effect.",
        int,
    ),
    "SCHEDULER_SYNC_DATA_CONNECTIONS_HOURS": (
        6,
        "How often to sync data connections with auto_sync enabled (hours). Requires scheduler restart to take effect.",
        int,
    ),
    "ANALYTICS_ANONYMISE_DAYS": (
        90,
        "Age at which page-visit rows lose their IP address, account link and user-agent "
        "string (days). The rest of the row is kept so the dashboard's page, browser, "
        "device and timezone history still works. 0 disables.",
        int,
    ),
    "ANALYTICS_DELETE_DAYS": (
        730,
        "Age at which page-visit rows are deleted outright (days). 0 disables.",
        int,
    ),
    "SCHEDULER_PURGE_PAGE_VISITS_HOURS": (
        24,
        "How often to age out page-visit rows (hours). Requires scheduler restart.",
        int,
    ),
    "SCHEDULER_CLEAR_SESSIONS_HOURS": (
        48,
        "How often to delete expired session rows (hours). Expired sessions are already "
        "unusable for login; this is about not retaining the user id they carry. "
        "Requires scheduler restart to take effect.",
        int,
    ),
    "SCHEDULER_PURGE_EXPIRED_MEDIA_HOURS": (
        24,
        "How often to delete uploaded media from expired verification records (hours). "
        "Requires scheduler restart to take effect.",
        int,
    ),
    "SCHEDULER_PURGE_EXPIRED_API_KEYS_HOURS": (
        24,
        "How often to purge user API keys that expired more than 90 days ago (hours). "
        "Requires scheduler restart to take effect.",
        int,
    ),
    "SCHEDULER_REMOVE_EXPIRED_DS_ROLES_HOURS": (
        24,
        "How often to remove squad roles from Directeurs Sportifs after their race has finished (hours). "
        "Requires scheduler restart to take effect.",
        int,
    ),
    "SCHEDULER_REFRESH_CACHED_CLUBS_HOURS": (
        24,
        "How often to check for stale cached opponent clubs and refresh those used by recent ladder matchups (hours). "
        "Requires scheduler restart to take effect.",
        int,
    ),
    "SCHEDULER_SYNC_ZWIFT_DATA_HOURS": (
        168,
        "How often to re-sync the Zwift Speed Lab route/segment dataset (hours; default weekly). "
        "Requires scheduler restart to take effect.",
        int,
    ),
    "SCHEDULER_SYNC_ZAUTH_VERIFICATIONS_HOURS": (
        1,
        "How often to reconcile Zwift OAuth (zauth) verification status from the zwift service "
        "(hours; default hourly). Requires scheduler restart to take effect.",
        int,
    ),
    # TTT Planner physics constants (tunable; calibrate against Zwift Insider / zwiftgopher)
    "TTT_AIR_DENSITY": (1.225, "Air density rho (kg/m^3) for the TTT power model", float),
    "TTT_CRR": (0.004, "Coefficient of rolling resistance for the TTT power model", float),
    "TTT_BIKE_MASS_KG": (8.0, "Bike + wheels mass (kg) added to rider weight in the TTT power model", float),
    "TTT_DRIVETRAIN_EFFICIENCY": (1.0, "Drivetrain efficiency (1.0 = no loss) for the TTT power model", float),
    "TTT_CDA_COEF": (
        0.0318,
        "Leading coefficient of the CdA estimate (folds in Cd) for the TTT aero-tuck position",
        float,
    ),
    "STD_CDA_COEF": (
        0.0400,
        "Leading coefficient of the CdA estimate for general road/climbing racing "
        "(e.g. the ladder Climb compare); upright position, higher than the TTT tuck",
        float,
    ),
    "TTT_CDA_HEIGHT_EXP": (0.725, "Height exponent in the CdA estimate for the power model", float),
    "TTT_CDA_WEIGHT_EXP": (0.425, "Weight exponent in the CdA estimate for the power model", float),
    "TTT_DRAFT_SAVINGS": (
        "[0.0, 0.233, 0.30, 0.366, 0.39, 0.40, 0.41, 0.42]",
        "Aero-power savings fraction by wheel position (index 0 = front). JSON array.",
        "string_list_field",
    ),
}

CONSTANCE_CONFIG_FIELDSETS = {
    "Site Settings": (
        "TEAM_NAME",
        "LOGO_DISPLAY_MODE",
        "SUBTITLE",
        "HOME_PAGE_SLUG",
        "HOME_PAGE_SLUG_AUTHENTICATED",
        "SITE_ANNOUNCEMENT",
        "MAINTENANCE_MODE",
        "GOOGLE_ANALYTICS_ID",
        "ABOUT_URL",
        "CONTACT_URL",
        "PRIVACY_POLICY_URL",
        "ANALYTICS_ANONYMISE_DAYS",
        "ANALYTICS_DELETE_DAYS",
        "TERMS_OF_SERVICE_URL",
    ),
    "Social Links": (
        "SOCIAL_LINKEDIN_URL",
        "SOCIAL_FACEBOOK_URL",
        "SOCIAL_INSTAGRAM_URL",
        "SOCIAL_TWITTER_URL",
    ),
    "Discord Guild": (
        "GUILD_NAME",
        "GUILD_ID",
        "DISCORD_URL",
        "UPGRADE_CHANNEL",
        "NEW_ARRIVALS_CHANNEL_ID",
        "USER_CHANGE_LOG",
        "REGISTRATION_UPDATES_CHANNEL_ID",
        "DISCORD_BOT_TOKEN",
        "DBOT_AUTH_KEY",
        "TEAM_MEMBER_ROLE_ID",
        "RACE_READY_ROLE_ID",
        "NEW_MEMBER_ROLE_ID",
        "DS_ROLE_ID",
        "NEW_MEMBER_DAYS",
        "NEW_ARRIVAL_MESSAGE_PUBLIC",
        "NEW_ARRIVAL_MESSAGE_PRIVATE",
        "SEND_NEW_ARRIVAL_DM",
        "HELP_MESSAGE",
        "EVENT_ROLE_PREFIXES",
    ),
    "Zwift Credentials": (
        "ZWIFT_USERNAME",
        "ZWIFT_PASSWORD",
        "ZWIFTPOWER_TEAM_ID",
    ),
    "User API": (
        "USER_API_RATE_LIMIT",
        "USER_API_MAX_KEYS_PER_USER",
        "PERM_ROLES_REQUIRED_USE_API",
    ),
    "Zwift Racing App": (
        "ZRAPP_API_URL",
        "ZRAPP_API_KEY",
        "ZR_UPGRADE_NOTICE_CHANNEL",
        "ZR_CATEGORY_SUFFIX",
        "ZR_ROLE_DIAMOND",
        "ZR_ROLE_RUBY",
        "ZR_ROLE_EMERALD",
        "ZR_ROLE_SAPPHIRE",
        "ZR_ROLE_AMETHYST",
        "ZR_ROLE_PLATINUM",
        "ZR_ROLE_GOLD",
        "ZR_ROLE_SILVER",
        "ZR_ROLE_BRONZE",
        "ZR_ROLE_COPPER",
        "ZR_ROLE_UNASSIGNED",
    ),
    "TrainingPeaks Virtual": (
        "TPV_CLUB_URL",
    ),
    "Permission Mappings": (
        "PERM_APP_ADMIN_ROLES",
        "PERM_TEAM_CAPTAIN_ROLES",
        "PERM_VICE_CAPTAIN_ROLES",
        "PERM_LINK_ADMIN_ROLES",
        "PERM_MEMBERSHIP_ADMIN_ROLES",
        "PERM_RACING_ADMIN_ROLES",
        "PERM_TEAM_MEMBER_ROLES",
        "PERM_RACE_READY_ROLES",
        "PERM_APPROVE_VERIFICATION_ROLES",
        "PERM_DATA_CONNECTION_ROLES",
        "PERM_PAGES_ADMIN_ROLES",
        "PERM_PERFORMANCE_VERIFICATION_TEAM_ROLES",
        "PERM_EVENT_ADMIN_ROLES",
        "PERM_ASSIGN_ROLES",
        "PERM_TICKET_ADMIN_ROLES",
    ),
    "Verification Settings": (
        "CATEGORY_REQUIREMENTS",
        "WEIGHT_FULL_DAYS",
        "WEIGHT_LIGHT_DAYS",
        "HEIGHT_VERIFICATION_DAYS",
        "VERIFICATION_MEDIA_MAX_DAYS",
        "POWER_VERIFICATION_DAYS",
        "POWER_REQUIRES_PER_VER",
        "EXPIRE_WARNING_DAYS",
        "VERIFICATION_FORM_MESSAGE",
        "VERIFICATION_CHECK_LIST",
        "WEIGHT_INSTRUCTIONS_URL",
        "HEIGHT_INSTRUCTIONS_URL",
        "ZAUTH_BANNER_ENABLED",
        "ZAUTH_BANNER_MESSAGE",
        "ZAUTH_VERIFICATION_REQUIRED",
    ),
    "Equipment": (
        "TRAINER_OPTIONS",
        "POWERMETER_OPTIONS",
        "HEARTRATE_MONITOR_OPTIONS",
    ),
    "Registration": (
        "REGISTRATION_FORM_INSTRUCTIONS",
    ),
    "SEO Settings": (
        "META_DESCRIPTION",
        "META_KEYWORDS",
        "OG_IMAGE_URL",
        "ROBOTS_DISALLOW_ALL",
        "ROBOTS_DISALLOW_AI",
    ),
    "Google Settings": (
        "GOOGLE_SERVICE_ACCOUNT_EMAIL",
        "GOOGLE_DRIVE_FOLDER_ID",
    ),
    "Events": (
        "EVENT_TYPES",
    ),
    "Strava": (
        "STRAVA_CLUB_ID",
        "STRAVA_CLUB_URL",
        "STRAVA_CLIENT_ID",
        "STRAVA_CLIENT_SECRET",
        "STRAVA_ACCESS_TOKEN",
        "STRAVA_REFRESH_TOKEN",
    ),
    "Scheduler": (
        "SCHEDULER_UPDATE_TEAM_RIDERS_HOURS",
        "SCHEDULER_UPDATE_TEAM_RESULTS_HOURS",
        "SCHEDULER_REFRESH_ALL_RACE_READY_HOURS",
        "SCHEDULER_SYNC_YOUTUBE_CHANNEL_IDS_HOURS",
        "SCHEDULER_SYNC_YOUTUBE_VIDEOS_HOURS",
        "SCHEDULER_WARN_EXPIRING_VERIFICATIONS_HOURS",
        "SCHEDULER_SYNC_DISCORD_ROLES_HOURS",
        "SCHEDULER_SYNC_DISCORD_CHANNELS_HOURS",
        "SCHEDULER_SYNC_ZR_RIDERS_HOURS",
        "SCHEDULER_SYNC_RIDER_PROFILES_HOURS",
        "SCHEDULER_SYNC_STRAVA_ACTIVITIES_HOURS",
        "SCHEDULER_SYNC_RACE_READY_ROLES_HOURS",
        "SCHEDULER_GUILD_MEMBER_SYNC_STATUS_HOURS",
        "SCHEDULER_SYNC_GUILD_MEMBERS_HOURS",
        "SCHEDULER_REFRESH_ZWIFT_METRICS_MINUTES",
        "ZWIFT_METRICS_FALLBACK_MIN_MINUTES",
        "SCHEDULER_SYNC_NEW_MEMBER_ROLES_HOURS",
        "SCHEDULER_SYNC_ZR_CATEGORY_ROLES_HOURS",
        "SCHEDULER_SYNC_DATA_CONNECTIONS_HOURS",
        "SCHEDULER_PURGE_PAGE_VISITS_HOURS",
        "SCHEDULER_CLEAR_SESSIONS_HOURS",
        "SCHEDULER_PURGE_EXPIRED_MEDIA_HOURS",
        "SCHEDULER_PURGE_EXPIRED_API_KEYS_HOURS",
        "SCHEDULER_REMOVE_EXPIRED_DS_ROLES_HOURS",
        "SCHEDULER_REFRESH_CACHED_CLUBS_HOURS",
        "SCHEDULER_SYNC_ZWIFT_DATA_HOURS",
        "SCHEDULER_SYNC_ZAUTH_VERIFICATIONS_HOURS",
    ),
    "Zwift Data": ("ZWIFT_SPEED_LAB_URL",),
    "Rider Data": (
        "RIDER_PROFILE_MAX_DAYS",
        "RIDER_PROFILE_REFRESH_HOURS",
        "RIDER_PROFILE_PURGE_MAX_FRACTION",
    ),
    "TTT Planner": (
        "TTT_AIR_DENSITY",
        "TTT_CRR",
        "TTT_BIKE_MASS_KG",
        "TTT_DRIVETRAIN_EFFICIENCY",
        "TTT_CDA_COEF",
        "STD_CDA_COEF",
        "TTT_CDA_HEIGHT_EXP",
        "TTT_CDA_WEIGHT_EXP",
        "TTT_DRAFT_SAVINGS",
    ),
}

# -----------------------------------------------------------------------------
# Logfire Instrumentation (must be at the end after Django is fully configured)
# -----------------------------------------------------------------------------
logfire.instrument_django()
logfire.instrument_httpx()
logfire.info("Django settings loaded", environment=config.logfire_environment)
