# Generated by Django 6.0.1 on 2026-02-02 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Client IP address', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser user agent string')),
                ('path', models.CharField(help_text='URL path visited', max_length=500)),
                ('referer', models.URLField(blank=True, help_text='Referring URL', max_length=1000)),
                ('screen_width', models.PositiveSmallIntegerField(blank=True, help_text='Screen width in pixels', null=True)),
                ('screen_height', models.PositiveSmallIntegerField(blank=True, help_text='Screen height in pixels', null=True)),
                ('viewport_width', models.PositiveSmallIntegerField(blank=True, help_text='Viewport width in pixels', null=True)),
                ('timezone', models.CharField(blank=True, help_text='Client timezone (e.g., America/New_York)', max_length=50)),
                ('browser', models.CharField(blank=True, help_text='Browser name', max_length=50)),
                ('browser_version', models.CharField(blank=True, help_text='Browser version', max_length=20)),
                ('os', models.CharField(blank=True, help_text='Operating system', max_length=50)),
                ('device_type', models.CharField(blank=True, help_text='Device type (mobile/tablet/desktop)', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the visit occurred')),
                ('user', models.ForeignKey(blank=True, help_text='Authenticated user (if logged in)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Page Visit',
                'verbose_name_plural': 'Page Visits',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['path', 'timestamp'], name='analytics_p_path_27c43a_idx'), models.Index(fields=['user', 'timestamp'], name='analytics_p_user_id_d7a3b3_idx')],
            },
        ),
    ]
