# Generated by Django 6.0.1 on 2026-01-26 23:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="URL slug for the page (e.g., 'about-us' creates /page/about-us/)", max_length=100, unique=True)),
                ('title', models.CharField(help_text='Page title displayed in header and browser tab', max_length=200)),
                ('content', models.TextField(blank=True, help_text='Main content in Markdown format')),
                ('hero_enabled', models.BooleanField(default=False, help_text='Show hero section at the top of the page')),
                ('hero_image', models.ImageField(blank=True, help_text='Background image for the hero section', null=True, upload_to='cms/hero/%Y/%m/')),
                ('hero_title', models.CharField(blank=True, help_text='Hero section title (defaults to page title if empty)', max_length=200)),
                ('hero_subtitle', models.TextField(blank=True, help_text='Hero section subtitle (supports Markdown)')),
                ('cards_above', models.JSONField(blank=True, default=list, help_text='Cards above content. Format: [{"icon": "...", "title": "...", "description": "...", "link_url": "...", "link_text": "..."}]')),
                ('cards_below', models.JSONField(blank=True, default=list, help_text='Cards below content. Format: [{"icon": "...", "title": "...", "description": "...", "link_url": "...", "link_text": "..."}]')),
                ('show_in_nav', models.BooleanField(default=False, help_text='Show this page in the sidebar navigation')),
                ('nav_title', models.CharField(blank=True, help_text='Override title for navigation (uses page title if empty)', max_length=50)),
                ('nav_order', models.IntegerField(default=0, help_text='Sort order in navigation (lower numbers appear first)')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', help_text='Draft pages are only visible to admins', max_length=10)),
                ('require_login', models.BooleanField(default=False, help_text='Require user to be logged in to view this page')),
                ('require_team_member', models.BooleanField(default=False, help_text='Require team_member permission to view this page')),
                ('meta_description', models.CharField(blank=True, help_text='Meta description for search engines (160 chars max)', max_length=160)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the page was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the page was last updated')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'ordering': ['nav_order', 'title'],
            },
        ),
    ]
