# Generated by Django 6.0.1 on 2026-01-28 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='meta_description',
        ),
    ]
