# Generated by Django 6.0.1 on 2026-01-28 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_remove_page_meta_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='cards_above',
            field=models.JSONField(blank=True, default=list, help_text='Cards above content. Format: [{"icon": "...", "title": "...", "description": "...", "link_url": "...", "link_text": "...", "link_new_tab": true}]'),
        ),
        migrations.AlterField(
            model_name='page',
            name='cards_below',
            field=models.JSONField(blank=True, default=list, help_text='Cards below content. Format: [{"icon": "...", "title": "...", "description": "...", "link_url": "...", "link_text": "...", "link_new_tab": true}]'),
        ),
    ]
