# Generated by Django 6.0.2 on 2026-02-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_alter_page_cards_above_alter_page_cards_below'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='nav_location',
            field=models.CharField(choices=[('main_nav', 'Main Nav (Sidebar)'), ('user_menu', 'User Menu (Top Right)')], default='main_nav', help_text='Where to display the nav link: sidebar or user dropdown menu', max_length=20),
        ),
    ]
