# Generated by Django 6.0.2 on 2026-02-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_add_nav_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='show_in_nav',
            field=models.BooleanField(default=False, help_text='Show this page in navigation (location controlled by Nav Location)'),
        ),
    ]
