# Generated by Django 6.0.2 on 2026-02-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_update_show_in_nav_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='accordions',
            field=models.JSONField(blank=True, default=list, help_text='Accordion items. Format: [{"title": "...", "content": "...", "open": false}]'),
        ),
    ]
