# Generated by Django 6.0.2 on 2026-02-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClubActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strava_id', models.BigIntegerField(help_text='Strava activity ID', unique=True)),
                ('athlete_first_name', models.CharField(help_text='Athlete first name', max_length=255)),
                ('athlete_last_name', models.CharField(blank=True, help_text='Athlete last name (initial only)', max_length=255)),
                ('name', models.CharField(help_text='Activity name', max_length=255)),
                ('sport_type', models.CharField(help_text='Sport type (e.g., Ride, VirtualRide)', max_length=50)),
                ('workout_type', models.PositiveSmallIntegerField(blank=True, help_text='Workout type code', null=True)),
                ('distance', models.DecimalField(decimal_places=2, help_text='Distance in meters', max_digits=12)),
                ('moving_time', models.PositiveIntegerField(help_text='Moving time in seconds')),
                ('elapsed_time', models.PositiveIntegerField(help_text='Elapsed time in seconds')),
                ('total_elevation_gain', models.DecimalField(blank=True, decimal_places=2, help_text='Elevation gain in meters', max_digits=10, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='Record created in database')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='Record last modified')),
            ],
            options={
                'verbose_name': 'Club Activity',
                'verbose_name_plural': 'Club Activities',
                'ordering': ['-date_created'],
            },
        ),
    ]
