# Generated by Django 6.0.2 on 2026-02-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_strava', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubactivity',
            options={'ordering': ['-activity_date', '-date_created'], 'verbose_name': 'Club Activity', 'verbose_name_plural': 'Club Activities'},
        ),
        migrations.AddField(
            model_name='clubactivity',
            name='activity_date',
            field=models.DateTimeField(blank=True, help_text='Activity start date/time from Strava', null=True),
        ),
    ]
